<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Tahun Hingga Filter</name>
   <tag></tag>
   <elementGuidId>dcd74b13-ea44-4d37-a9b3-bdb1f372c0f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'formYear_container__gG_ns' and (. = 'Hingga')]//input[@type = 'tel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formSearchYear_container__wvuqm</value>
      <webElementGuid>170a1fbd-b525-402f-b390-477ccff214ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hingga</value>
      <webElementGuid>4d12b2e7-4bc4-440f-ac86-f0bf929475f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>7eb43a7a-327d-4f73-907a-2c6686315696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48616d17-e68e-4c28-81e0-2f647eacaa56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class = 'formYear_container__gG_ns' and (. = 'Hingga')]//input[@type = 'tel']</value>
      <webElementGuid>78636704-461a-42f6-ad8e-99863ed42dd7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
