<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_refinancing ql</name>
   <tag></tag>
   <elementGuidId>258c1f71-daf5-43c5-9748-b8d7c9992abf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category-Refinancing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='category-Refinancing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c1f6217-3a12-44d4-9f5b-2cbc094f95e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f13b3869-a230-4815-930f-e854ff99ffd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>de3b013d-e36f-4c20-b77e-d2c85bb29733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8a967f1d-c813-45eb-87fd-e5a4a328fde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>a17ac55b-3453-4822-8558-663a7c6e9ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Refinancing</value>
      <webElementGuid>125e8a24-ad56-4249-a064-288370c4a878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group aspect-square size-5 rounded-full border-2 border-line-bold bg-white outline-none transition-all duration-300 focus-within:border-line-brand-blue focus-within:ring-2 focus-within:ring-line-link focus-within:ring-offset-2 hover:ring-line-link hover:ring-offset-2 enabled:hover:ring-2 disabled:text-text-neutral disabled:cursor-not-allowed disabled:border-line-bold disabled:bg-surface-neutral disabled:hover:ring-transparent data-[state=checked]:border-line-brand-blue disabled:data-[state=checked]:border-line-bold disabled:data-[state=checked]:text-text-disabled</value>
      <webElementGuid>d50a96bd-b626-481e-b422-825e0951afa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category-Refinancing</value>
      <webElementGuid>a7d37d0b-6482-4ccd-a75c-0edcacb7a9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>35fc21ff-078f-4b89-ba81-d9f9d78104ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>vertical</value>
      <webElementGuid>3eedd66d-f6cc-4aeb-aa52-6861284c3a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category-Refinancing&quot;)</value>
      <webElementGuid>9ef460eb-9a46-4919-823e-4fddb51d9bbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='category-Refinancing']</value>
      <webElementGuid>16e29eed-9305-4a25-98bd-82734a29d6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2f:']/form/div[2]/div/div/div/div[2]/button</value>
      <webElementGuid>4a30c846-be7a-47f0-8f21-3cf603e78cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/button</value>
      <webElementGuid>d7080508-35ec-4075-8362-e3e44aa6aee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'category-Refinancing']</value>
      <webElementGuid>01ebca6d-b49d-4162-bd72-b1fc589bfcdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
