<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_used car ql</name>
   <tag></tag>
   <elementGuidId>40226066-72c1-4dbf-987f-18d98fecb595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='category-Used Car']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82d1efc3-17ed-4877-9637-a9df17771d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a549c99-7213-4310-bff7-cbea74d70e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2df819c0-9bab-4803-9dfb-e6ab7cd9696d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e677f128-689e-4bfa-bd6e-eda51981f81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>9a89fafe-23fa-43e7-a877-863db436af10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Used Car</value>
      <webElementGuid>b6373a5b-060d-4484-8f23-abcafcd69cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group aspect-square size-5 rounded-full border-2 border-line-bold bg-white outline-none transition-all duration-300 focus-within:border-line-brand-blue focus-within:ring-2 focus-within:ring-line-link focus-within:ring-offset-2 hover:ring-line-link hover:ring-offset-2 enabled:hover:ring-2 disabled:text-text-neutral disabled:cursor-not-allowed disabled:border-line-bold disabled:bg-surface-neutral disabled:hover:ring-transparent data-[state=checked]:border-line-brand-blue disabled:data-[state=checked]:border-line-bold disabled:data-[state=checked]:text-text-disabled</value>
      <webElementGuid>c9195137-7c32-4acd-b58b-57cc4ebdce92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category-Used Car</value>
      <webElementGuid>d87d71bc-d48a-482a-98d1-56f71b7accb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6e658d87-d5d2-4fbf-b128-bed4ea19c24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>vertical</value>
      <webElementGuid>a4ee5660-e32b-4c0d-a9b8-7e05c29ad656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category-Used Car&quot;)</value>
      <webElementGuid>6b8dfb92-880a-419f-b441-77688d63ba18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='category-Used Car']</value>
      <webElementGuid>20754129-f029-4f39-9218-c875d9356cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2f:']/form/div[2]/div/div/div/div[3]/button</value>
      <webElementGuid>5e84caaa-8c76-4a5c-a5b0-04a6e66578b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/button</value>
      <webElementGuid>9bd2c7f6-8456-4a42-98e5-499d772a508d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'category-Used Car']</value>
      <webElementGuid>565d9f51-86bb-4397-a961-12431eedc3ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
