<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_SPK Counter</name>
   <tag></tag>
   <elementGuidId>c3595ab4-9fa6-4ecf-8389-5e0b14b6e565</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-body-regular.text-text-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r1q:-content-SPK']/div/section/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf60281c-993e-4033-beb1-5997fe7fb0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-body-regular text-text-primary</value>
      <webElementGuid>8f482ec0-60c4-4f61-aace-b58c3af875a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1-100 of 4574 leads.</value>
      <webElementGuid>c1e13e90-74a5-4096-b411-1f9bbb40d4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1q:-content-SPK&quot;)/div[1]/section[@class=&quot;flex w-full items-center justify-between mb-4&quot;]/div[@class=&quot;flex items-center&quot;]/div[@class=&quot;text-body-regular text-text-primary&quot;]</value>
      <webElementGuid>92d146f2-8076-4490-953b-dfccc3b1dafe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1q:-content-SPK']/div/section/div/div</value>
      <webElementGuid>ec97b214-5de9-4c59-b23d-1138e847afe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Data'])[1]/preceding::div[1]</value>
      <webElementGuid>d43ece5b-acd6-4247-a8b3-e8a9e31d22fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1-100 of 4574 leads.']/parent::*</value>
      <webElementGuid>18eb5d87-14a9-434e-b6a1-425cfe2a41fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/section/div/div</value>
      <webElementGuid>28e8cb13-9796-42a5-b6fb-4bddc829f6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1-100 of 4574 leads.' or . = '1-100 of 4574 leads.')]</value>
      <webElementGuid>f1db134d-eda4-43e2-9d90-fb11da98708d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
