<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Artikel-keuangan</name>
   <tag></tag>
   <elementGuidId>a2dbe4ce-140c-4af8-ba27-65036f5c9746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'menuItem_submenu__OrcK_' and (text() = 'Keuangan' or . = 'Keuangan')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menuItem_submenu__OrcK_</value>
      <webElementGuid>c732cc5f-3203-46fd-a421-a7ad05e7bc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keuangan</value>
      <webElementGuid>36ceee68-b79b-44b0-8194-908d065397fa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
