<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CMS Status Filter</name>
   <tag></tag>
   <elementGuidId>937424d0-3577-43c0-bebf-f51bc52f6efc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rh:']/div/div[2]/div/div[2]/div/div/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85f80bcd-a49d-4c63-9312-fd84037d74c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full select-none rounded border-0 bg-white p-2 text-left text-xs hover:bg-primaryRed-10 focus:bg-primaryRed-50 disabled:hover:bg-white</value>
      <webElementGuid>d8fe4dac-3427-434f-8e28-f63978e72ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CMS Status</value>
      <webElementGuid>2523cea4-403a-49b8-8ecb-fb18914c9c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rh:&quot;)/div[@class=&quot;flex w-[215.6px] flex-col items-center gap-2 rounded border-[1px] border-solid border-line bg-white py-4 font-OpenSans&quot;]/div[@class=&quot;w-full px-2&quot;]/div[@class=&quot;simplebar-wrapper&quot;]/div[@class=&quot;simplebar-mask&quot;]/div[@class=&quot;simplebar-offset&quot;]/div[@class=&quot;simplebar-content-wrapper&quot;]/div[@class=&quot;simplebar-content&quot;]/button[@class=&quot;block w-full select-none rounded border-0 bg-white p-2 text-left text-xs hover:bg-primaryRed-10 focus:bg-primaryRed-50 disabled:hover:bg-white&quot;]</value>
      <webElementGuid>c5b452fc-a565-4aad-a156-70c3523a62cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rh:']/div/div[2]/div/div[2]/div/div/div/button[2]</value>
      <webElementGuid>0711e7cd-a1a8-4e1c-bbd9-b4907e569585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='y'])[1]/following::button[1]</value>
      <webElementGuid>d786ae1f-3bad-4e5e-a54a-bf031862533a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='n'])[1]/following::button[1]</value>
      <webElementGuid>46bb21c7-09b0-46df-a8b5-d6d63d37ad16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button[2]</value>
      <webElementGuid>8723c834-7dfb-4730-811b-b1b69facd359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'CMS Status' or . = 'CMS Status')]</value>
      <webElementGuid>aff9b065-4a98-4f70-99a7-3ac61212b3ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
