<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Draft</name>
   <tag></tag>
   <elementGuidId>12b2e3da-b672-4e24-8ca7-c3b8d1d68a35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'react-select-44-option-0' and (text() = 'Draft' or . = 'Draft')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bb8ce544-db91-4034-aaf8-58fbf7ddb079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-react-select__option my-react-select__option--is-focused css-lu6i3x-option</value>
      <webElementGuid>add1af28-09b8-445a-801d-cfb99b68f458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5fb26af5-552d-4ac6-8c11-01bc8c7f7a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-44-option-0</value>
      <webElementGuid>bf9d11ee-c7d9-43d8-9278-3de52c78457e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>10b99d00-83a7-4b50-8cc6-aa7171a3fea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3f437874-2d5e-4afe-8f76-b9c949a0389f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>faa32b1e-0f0a-4ab8-8d65-b8e022e505c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;my-react-select__menu css-7o8zbf-menu&quot;]/div[@id=&quot;react-select-44-listbox&quot;]/div[@id=&quot;react-select-44-option-0&quot;]</value>
      <webElementGuid>38e55b10-3610-4af0-91a2-339d829f5490</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-44-option-0' and (text() = 'Draft' or . = 'Draft')]</value>
      <webElementGuid>873b76d5-7123-40c9-9f85-11ea3bc95f6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
