<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Draft-select</name>
   <tag></tag>
   <elementGuidId>2b2beba5-5a32-4145-839b-cf6f4b3edf43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Draft' or . = 'Draft')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r2:']/div/div[2]/div/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.my-react-select__multi-value__label.css-1ps24qk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f926685-3c5e-4a18-a0ae-d4dfc0caa019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-react-select__multi-value__label css-1ps24qk</value>
      <webElementGuid>f720cbec-2703-4dc1-8969-e23da6b51b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>e8ad5c1d-3659-4106-83e0-6e9fc4b272b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r2:&quot;)/div[@class=&quot;flex flex-col gap-1&quot;]/div[2]/div[@class=&quot;my-react-select-container css-b62m3t-container&quot;]/div[@class=&quot;my-react-select__control my-react-select__control--is-focused my-react-select__control--menu-is-open css-r4rqo4-control&quot;]/div[@class=&quot;relative overflow-hidden&quot;]/div[@class=&quot;h-full w-full rounded-[inherit] [&amp;>div]:!block&quot;]/div[1]/div[@class=&quot;!max-h-none my-react-select__value-container my-react-select__value-container--is-multi my-react-select__value-container--has-value css-1dyz3mf&quot;]/div[@class=&quot;my-react-select__multi-value css-yf4tdl-multiValue&quot;]/div[@class=&quot;my-react-select__multi-value__label css-1ps24qk&quot;]</value>
      <webElementGuid>38baed06-2f85-4f8d-97a0-36b3ab61d6c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2:']/div/div[2]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>b5185b95-8ffa-49f5-b313-2f1eeb414377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live, 1 of 4.'])[1]/following::div[7]</value>
      <webElementGuid>490dfe19-49fb-4609-983d-55ed6f976e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='option Draft, selected.'])[1]/following::div[7]</value>
      <webElementGuid>136c1138-6fcc-408c-b9c8-634d52b883ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live'])[6]/preceding::div[7]</value>
      <webElementGuid>3842fa3b-1d6f-4a30-8f45-7c7a78547f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waiting'])[1]/preceding::div[8]</value>
      <webElementGuid>dea77f31-1436-4705-85ae-ee4231f3455d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>a69ca7fb-91a8-4c90-9867-998f962b0bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Draft' or . = 'Draft')]</value>
      <webElementGuid>737e24bf-7117-4b1b-882b-6b74d7a2fd27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
