<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Tahun Hingga</name>
   <tag></tag>
   <elementGuidId>7ed66744-3a3f-4c66-a8c1-6f321bab0158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[starts-with(@class, 'formSearchYear_container') and (. = 'Hingga')]//input[@type = 'tel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formSearchYear_container__wvuqm</value>
      <webElementGuid>fa61b684-1c38-44e9-af8c-d235f1985423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hingga</value>
      <webElementGuid>601ec046-a783-48d3-909b-0f983f8fb385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>120995d9-7a16-4ef0-ac34-be443fc773af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66a82f40-1b05-4a40-9809-185b7a20df2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[starts-with(@class, 'formSearchYear_container') and (. = 'Hingga')]//input[@type = 'tel']</value>
      <webElementGuid>ad4da65b-1086-4338-8e72-f49a4c6147ee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
