<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Label_Lihat Semua Testimoni</name>
   <tag></tag>
   <elementGuidId>37467a31-9e6c-443f-b18a-a69f336747be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.testimonyWidget_textLink__sliDz</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[starts-with(@class, 'testimonyWidget_textLink') and (text() = 'Lihat semua' or . = 'Lihat semua')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div[10]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98457774-3b49-4a71-aff9-e7a1b206b18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>fd7904dd-761a-4c45-9a93-f3e022b5c10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>starts with</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>testimonyWidget_textLink</value>
      <webElementGuid>16487038-6cee-4d7c-af80-07c6e1a8a8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cerita-pengguna</value>
      <webElementGuid>3e7a642f-3c57-42c3-baae-5ade5b0697bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat semua</value>
      <webElementGuid>15cce2db-e63c-412d-b0e9-20e445576fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;index_main__K2Wvo&quot;]/div[@class=&quot;index_container__KNQ8V&quot;]/div[@class=&quot;testimonyWidget_container__8vQ9D&quot;]/div[@class=&quot;testimonyWidget_row__xhNUr&quot;]/a[@class=&quot;testimonyWidget_textLink__sliDz&quot;]</value>
      <webElementGuid>c00788d8-592d-45b9-8c8d-3f0bd6548fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[10]/div/a</value>
      <webElementGuid>73c31ada-93c2-45d4-b13d-b68f36b7955f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lihat semua')])[2]</value>
      <webElementGuid>20ea1fe5-dfff-43eb-9c93-820e6a508463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerita Pengguna SEVA'])[1]/following::a[1]</value>
      <webElementGuid>6313f94f-fda7-41bc-a09e-e98a46688a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Lebih Lanjut'])[3]/following::a[1]</value>
      <webElementGuid>48bedc7a-0895-4c4f-bbf8-a3d0cb471250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='minggu lalu, Jakarta Pusat'])[1]/preceding::a[1]</value>
      <webElementGuid>dbdf7e0c-7c50-48b9-ab96-aaf80d03f5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cerita-pengguna')]</value>
      <webElementGuid>5c1d189e-ac08-4ae3-a222-4325d3014e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/a</value>
      <webElementGuid>4946a287-b979-469e-b9bc-51227bb490da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cerita-pengguna' and (text() = 'Lihat semua' or . = 'Lihat semua')]</value>
      <webElementGuid>99fc72cf-0622-4039-9e7a-ed5bcf2ac203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
