<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan Perubahan - disabled</name>
   <tag></tag>
   <elementGuidId>b0286bfb-a82f-4039-bed1-6974d1934de3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/section[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button_primaryDarkBlue__SJzXm.button_big__H6cBN.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6b2472b-452b-4a06-995f-29d74ffbf028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_primaryDarkBlue__SJzXm button_big__H6cBN undefined</value>
      <webElementGuid>1daf083f-7508-4a56-a40f-7858c29f8c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>button-simpan-perubahan</value>
      <webElementGuid>bc28388e-de88-414a-850c-90093a48983a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan Perubahan</value>
      <webElementGuid>71ca6696-547a-4d7e-b38a-474c0099bac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;pageLayout_container__Y72th&quot;]/main[@class=&quot;account-profile_wrapper__syRey&quot;]/section[@class=&quot;account-profile_wrapper__button__xEZBK&quot;]/button[@class=&quot;button_primaryDarkBlue__SJzXm button_big__H6cBN undefined&quot;]</value>
      <webElementGuid>3ce68f8f-82dc-4fbc-b0be-05820009982e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section[2]/button</value>
      <webElementGuid>ed40abac-eb6c-4681-89a8-d1a3f0203262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wanita'])[1]/following::button[1]</value>
      <webElementGuid>346f794c-304b-44ce-b7e5-4c4c8dfdd819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pria'])[1]/following::button[1]</value>
      <webElementGuid>888e287b-efae-4137-ba5e-3edc74f8b42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar Akun'])[1]/preceding::button[1]</value>
      <webElementGuid>da8d54e0-4ca4-4802-b6c6-02d7942e0a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Akun'])[1]/preceding::button[2]</value>
      <webElementGuid>46f0b275-07d5-402e-bab7-ec1c1eec9c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan Perubahan']/parent::*</value>
      <webElementGuid>ed622941-6416-42f8-8557-90b9afb33048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/button</value>
      <webElementGuid>83fa89f5-217a-42ad-8fc2-4e6cf356a397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Simpan Perubahan' or . = 'Simpan Perubahan')]</value>
      <webElementGuid>e8c13eee-9a64-4c9e-840a-8f8fbbdfc6f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
