<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Workstation</name>
   <tag></tag>
   <elementGuidId>9698123f-6a14-4c21-8cdc-ac52e2d09228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r7:']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Workstation&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>55de5c40-0d35-4626-8048-ff1f5b0cd056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden min-w-[113px] font-Kanyon text-sm/[19px] font-medium text-text-placeholder group-hover/sidebar:block group-aria-selected/item:font-bold group-aria-selected/item:text-text-critical</value>
      <webElementGuid>35efa238-d7b0-4ec6-8970-0544d799eb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Workstation</value>
      <webElementGuid>124130f1-edb6-4601-b8d1-f6afda0cca54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r7:&quot;)/div[@class=&quot;flex items-center gap-6&quot;]/p[@class=&quot;hidden min-w-[113px] font-Kanyon text-sm/[19px] font-medium text-text-placeholder group-hover/sidebar:block group-aria-selected/item:font-bold group-aria-selected/item:text-text-critical&quot;]</value>
      <webElementGuid>1e1efe4c-c74c-4c08-b019-ae072d76df35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r7:']/div/p</value>
      <webElementGuid>a07ace88-d7f3-4b4d-bf50-59f6f005c217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to SEVA CRM'])[1]/following::p[2]</value>
      <webElementGuid>93ead336-a144-411f-acd6-43ff0992936b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEVA CRM Homepage'])[1]/following::p[2]</value>
      <webElementGuid>8301e5a4-08d9-4b05-bd86-c1e59b4c3fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Workstation']/parent::*</value>
      <webElementGuid>80f418a8-048d-43db-b19c-e7542737840d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/p</value>
      <webElementGuid>1edd4387-2f25-4f52-9ea4-727db00fb868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Workstation' or . = 'Workstation')]</value>
      <webElementGuid>eee5763a-cd39-46f9-b169-50412237338f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
