<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BacaJuga</name>
   <tag></tag>
   <elementGuidId>12f536a2-cbb4-4cad-8a33-eb76385c6760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;post-967908&quot;]/div[2]/p[7]/a/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>5a58177f-4403-424d-9634-fdbed233dcbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1718249383077</value>
      <webElementGuid>858441df-1659-4bf8-9060-16240e5d98d1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
