<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pendapatan bulanan kk</name>
   <tag></tag>
   <elementGuidId>ab744228-2f14-48a1-884e-29e062661b32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Masukkan pendapatan']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@class='0 input_input__c0tP8'][count(. | //*[@placeholder = 'Masukkan pendapatan']) = count(//*[@placeholder = 'Masukkan pendapatan'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.0.input_input__c0tP8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>413ddfcf-7767-4899-973f-f69427568cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>0 input_input__c0tP8</value>
      <webElementGuid>3b6cd550-27eb-4a0a-bd60-3b6daa313351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan pendapatan</value>
      <webElementGuid>4b0710f3-fe6d-4c75-a26c-a0fecce25303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>25a6a546-f939-4bf3-a59a-af283417c4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>198bdbf2-94c6-4c9e-b80a-f37e29e6225d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rp20.000.000</value>
      <webElementGuid>442357df-416f-4f55-92e4-3db11dbdcf3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@class='0 input_input__c0tP8']</value>
      <webElementGuid>e46f0f89-a090-4e76-b3b9-14536bedb6a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Rp20.000.000']</value>
      <webElementGuid>ebc5d90b-dfd8-4bd4-8ba6-47687edf84d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div[5]/div/div/input</value>
      <webElementGuid>1403eb2b-8764-410a-bac6-ae417b0b999b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>0189c432-01f4-4ac3-a223-fa8ce498a6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan pendapatan' and @type = 'tel']</value>
      <webElementGuid>9045b7f6-f1ea-4c1e-b492-e7fbc32a1537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
