<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_All Assigned Leads422898</name>
   <tag></tag>
   <elementGuidId>4c96bd02-616e-46e5-b9ef-bdcecd7a75cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='radix-:roe:-trigger-ASSIGNED']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;All Assigned Leads 422898&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f1f8fce-6468-4522-88a0-a7f0e77d73d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7cc46406-5f3c-41f8-8d3c-6311709d5cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>d254bb35-ff10-4a42-bfc9-559ae65ef2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e7dbd3de-d872-415a-b7b8-4c1d96eb57e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:roe:-content-ASSIGNED</value>
      <webElementGuid>b46751c1-21b9-4947-98eb-47f2f27777c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>inactive</value>
      <webElementGuid>8ea61ef3-fd8b-4106-b9bf-0abf72dbc29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:roe:-trigger-ASSIGNED</value>
      <webElementGuid>27769306-3b58-44a2-b3f4-f679db627fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group/trigger relative mr-6 inline-flex min-h-12 cursor-pointer items-center justify-center gap-[10px] whitespace-nowrap border-b-[3px] border-transparent bg-transparent text-body-regular font-normal text-text-placeholder transition-all hover:border-line disabled:pointer-events-none data-[state=active]:font-semibold data-[state=active]:text-text-primary [&amp;[data-state='active']_.counter]:hover:bg-hover-brand-red</value>
      <webElementGuid>dab3a2a7-ad93-488a-951c-60b2e22cb980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7ef0ef19-8e4f-4e18-9998-84302171c2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>7fbcc383-ef59-4898-a1b4-4c95c23838c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Assigned Leads422898</value>
      <webElementGuid>d4159017-7391-4f9e-aca5-8033f2022a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:roe:-trigger-ASSIGNED&quot;)</value>
      <webElementGuid>77908796-0096-48ac-8dac-fde5ae01d704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='radix-:roe:-trigger-ASSIGNED']</value>
      <webElementGuid>fc2016ef-125d-4ef1-9d87-deb70d9c8b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/div/div/div/div/button[3]</value>
      <webElementGuid>d3243d67-5755-4c76-8296-5ff4caae8733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Assigned Leads']/parent::*</value>
      <webElementGuid>6f72a1fa-ae14-425f-88dc-2b2460cd60a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>173f7a59-690d-4683-85ef-77f77b8ab1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'radix-:roe:-trigger-ASSIGNED' and (text() = 'All Assigned Leads422898' or . = 'All Assigned Leads422898')]</value>
      <webElementGuid>a0104f21-302d-4e00-b27b-209a62c367f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
