<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp2.710.400.000_monthlyIncome</name>
   <tag></tag>
   <elementGuidId>505b0b6b-a4b4-42de-8199-ed2734b335c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.multi-kk_form__4UeYG > div:nth-of-type(2) > div.undefined.multi-kk_desktopInputWrapper__u6BEu > input[name=&quot;monthlyIncome&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='monthlyIncome'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3f568ee-4884-4cae-9ad5-87dd35512da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_input__c0tP8</value>
      <webElementGuid>f6c7ef4b-ed11-4e86-906a-079c1c887678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Pendapatan</value>
      <webElementGuid>552aeed7-a9c8-4f4c-81e5-28e4b8679060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>77ca4df4-59a3-403f-83bf-c2074af08903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>0b2b90a5-5c9f-4fb6-a6d6-5540a3be8593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>monthlyIncome</value>
      <webElementGuid>cba9e918-d15c-4b68-b2e8-870139954d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__variable_930519 __variable_28fd58 __variable_76bd07 __variable_f7241a __variable_029e55 __variable_aac15d __variable_5e7d95 __variable_85049c __variable_971c20&quot;]/div[@class=&quot;pageLayout_containerResponsive__lYUnT&quot;]/div[@class=&quot;multi-kk_wrapperMobile__ZqC1X&quot;]/div[@class=&quot;mobilleView_container__O0_sp multi-kk_container__f_WCr&quot;]/div[2]/div[@class=&quot;multi-kk_form__4UeYG&quot;]/div[2]/div[@class=&quot;undefined multi-kk_desktopInputWrapper__u6BEu&quot;]/input[@class=&quot;input_input__c0tP8&quot;]</value>
      <webElementGuid>532b7cac-cf5b-4a4a-aaec-a771ceaaa06e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='monthlyIncome'])[2]</value>
      <webElementGuid>50196393-e6b7-44c1-ad8d-a9c29f12bde9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[4]/div/div[2]/div[3]/div[2]/div/input</value>
      <webElementGuid>a2e907ea-c544-487e-b7d5-46f9b6436c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>1942ed63-92ac-4594-9fdb-29de0429d124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan Pendapatan' and @type = 'tel' and @name = 'monthlyIncome']</value>
      <webElementGuid>b46308d4-7f36-4054-b3cd-862823d9a4f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
