<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NameEmailPhone62Softphone Extension (op_462ce9</name>
   <tag></tag>
   <elementGuidId>c105ff95-4989-4f54-a18c-1fb27f04a8dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef02b0d7-e39e-4d8f-bf85-469e81ecc300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-6 mr-[22px] mt-6 flex flex-col gap-[23px] pb-6 pl-[calc(38px-24px)] pr-[calc(50px-22px)]</value>
      <webElementGuid>8873e0f1-ffa1-4261-9bbe-7b6a00050761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NameEmailPhone+62Softphone Extension (optional)Insert the user's extension number from softphone to call customerPassword ActivationPasswordRoleRole cannot be emptyBU Company (optional)Event (optional)CRM Status:CMS Status: ActiveAvatarUpload PNG Only</value>
      <webElementGuid>6eb9dfa2-1c14-4e53-9131-2cd5b9016cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;ml-20 px-3 pb-3&quot;]/div[@class=&quot;mt-[10px]&quot;]/div[@class=&quot;flex gap-4 overflow-hidden&quot;]/div[2]/div[@class=&quot;h-[calc(var(--crm-screen-height)-10px-44px-19px-18px-16px)] w-[540px] overflow-x-auto rounded-[10px] bg-white font-OpenSans text-xs text-bodyCopy&quot;]/div[@class=&quot;simplebar-wrapper&quot;]/div[@class=&quot;simplebar-mask&quot;]/div[@class=&quot;simplebar-offset&quot;]/div[@class=&quot;simplebar-content-wrapper&quot;]/div[@class=&quot;simplebar-content&quot;]/form[@class=&quot;relative&quot;]/div[@class=&quot;ml-6 mr-[22px] mt-6 flex flex-col gap-[23px] pb-6 pl-[calc(38px-24px)] pr-[calc(50px-22px)]&quot;]</value>
      <webElementGuid>2657f871-202c-4e11-b28a-23b351f77e02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div[2]/div/div/div/form/div[2]</value>
      <webElementGuid>144cdc2d-20f5-4f29-bfe2-b9aeee2cef59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Account'])[1]/following::div[1]</value>
      <webElementGuid>11252c98-5e9b-4fcb-8a83-4180ef60d062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[21]/following::div[12]</value>
      <webElementGuid>98470848-8279-49f0-8c9a-75c82e0c8da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>ca27a535-d63f-4e6d-8d67-d77c1f49f518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;NameEmailPhone+62Softphone Extension (optional)Insert the user&quot; , &quot;'&quot; , &quot;s extension number from softphone to call customerPassword ActivationPasswordRoleRole cannot be emptyBU Company (optional)Event (optional)CRM Status:CMS Status: ActiveAvatarUpload PNG Only&quot;) or . = concat(&quot;NameEmailPhone+62Softphone Extension (optional)Insert the user&quot; , &quot;'&quot; , &quot;s extension number from softphone to call customerPassword ActivationPasswordRoleRole cannot be emptyBU Company (optional)Event (optional)CRM Status:CMS Status: ActiveAvatarUpload PNG Only&quot;))]</value>
      <webElementGuid>96986610-ec99-4039-879f-9cb1e69ca713</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
