<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Peugeot 2008</name>
   <tag></tag>
   <elementGuidId>10780d4a-c2b4-4c4e-bb84-1256b9bbb540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp-upper-content']/div[2]/h1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;pdp-upper-content&quot;)/div[@class=&quot;carOverView_container__wAVF1&quot;]/h1[@class=&quot;carOverView_carBrandModelText__OLVuA&quot;][count(. | //h1[(text() = 'Toyota' or . = 'Toyota')]) = count(//h1[(text() = 'Toyota' or . = 'Toyota')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.carOverView_carBrandModelText__OLVuA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e044153e-00de-4d40-a636-6960e8b93cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carOverView_carBrandModelText__OLVuA</value>
      <webElementGuid>6c0472b2-cde7-4dba-9521-ebcbaafc21bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>text-car-brand-model</value>
      <webElementGuid>1ad6db5f-37c0-492c-ac13-b0aff849a8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toyota</value>
      <webElementGuid>16bf06e3-d8d7-4d5e-b888-561ff7e0c0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp-upper-content&quot;)/div[@class=&quot;carOverView_container__wAVF1&quot;]/h1[@class=&quot;carOverView_carBrandModelText__OLVuA&quot;]</value>
      <webElementGuid>5629ba5f-1d71-44f8-8b11-43177977dc45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp-upper-content']/div[2]/h1</value>
      <webElementGuid>12373513-ebcc-4f2e-a98e-5c79c50e1bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilihan Warna'])[1]/following::h1[1]</value>
      <webElementGuid>11f9186e-4f46-4066-83a6-b508723c8d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video'])[1]/following::h1[1]</value>
      <webElementGuid>7e784cd7-d38a-462d-94f7-b13cf6d3245e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jakarta Pusat'])[1]/preceding::h1[1]</value>
      <webElementGuid>d54eae2e-5da2-47f9-80db-66f9c30198cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Peugeot 2008']/parent::*</value>
      <webElementGuid>2ae971d1-2361-4631-bf90-37121ce895e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>992ad4fb-f56d-4a91-a88e-18a6c93ad1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Peugeot 2008' or . = 'Peugeot 2008')]</value>
      <webElementGuid>148f9e46-d32f-41f2-b9a4-c0efbc4c7c6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
