<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_3 Tahun Comprehensive  1 Tahun TLO</name>
   <tag></tag>
   <elementGuidId>9e23aa42-570d-4d84-991d-8f7752fe7507</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-56-option-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-56-option-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ad491c3b-c545-4366-8a5a-93a61f5742b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-react-select__option my-react-select__option--is-focused css-1w019hq-option</value>
      <webElementGuid>2d8ae3e0-4fe9-4439-ba0d-ea57211a6099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>163d05ec-8b57-4bdc-bc61-cb0ad9cd4f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-56-option-3</value>
      <webElementGuid>1a71e02d-af37-4d5a-a297-134e6bd7ffe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d0a2d31c-800c-4539-9814-d9cb5fe8e252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>63207cd3-b659-45c1-a00a-f7b6c60cb05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>calculator-simulation-page-option-insurance-type-4-3</value>
      <webElementGuid>39a30603-0f9d-4951-9890-963a906efa77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3 Tahun Comprehensive + 1 Tahun TLO</value>
      <webElementGuid>981194d4-cb2b-4f98-b0ea-de6cc51e4ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-56-option-3&quot;)</value>
      <webElementGuid>3b079b5f-d765-4e01-b320-01423bb28476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-56-option-3']</value>
      <webElementGuid>5550cd95-2496-4b00-96cd-0f7c61ebe4a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-56-listbox']/div[4]</value>
      <webElementGuid>eefbec5e-607f-4225-9e37-9b4a1dd3ed92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Comprehensive'])[1]/following::div[3]</value>
      <webElementGuid>d94f3655-13b2-4b06-84b3-76572fb44632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='option 2 Tahun Comprehensive + 2 Tahun TLO, selected.'])[1]/following::div[13]</value>
      <webElementGuid>8b4ca7b8-f954-4bb4-8741-99276feacd34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Total Loss Only'])[3]/preceding::div[1]</value>
      <webElementGuid>ba0f05b5-11df-478d-9f1d-f4a5c5710e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div[4]</value>
      <webElementGuid>db26c68e-974b-4001-a121-230fb2e498be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-56-option-3' and (text() = '3 Tahun Comprehensive + 1 Tahun TLO' or . = '3 Tahun Comprehensive + 1 Tahun TLO')]</value>
      <webElementGuid>ba071554-80fd-4551-b263-00714667e149</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
