<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1 Tahun Comprehensive  1 Tahun TLO</name>
   <tag></tag>
   <elementGuidId>e125d281-afc7-4990-9251-463c8e0989b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-54-option-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-54-option-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2209e975-7bf2-48e9-8f11-defb676b3b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-react-select__option my-react-select__option--is-focused css-1w019hq-option</value>
      <webElementGuid>66d4e7cf-f095-447f-b6ff-f5cf59017339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>56e65d8b-47c2-4724-a2a9-ad230859e71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-54-option-1</value>
      <webElementGuid>b4fcb3e8-a5ac-4c22-9555-f726c399ac3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f6e7fb3c-f7f8-456f-b1a2-39e24e739c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b3a8a81b-86a2-4035-aa2f-bfa5a5f347fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>calculator-simulation-page-option-insurance-type-2-1</value>
      <webElementGuid>4809d3a1-f59c-44c8-af63-f11bb86b5e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Tahun Comprehensive + 1 Tahun TLO</value>
      <webElementGuid>de38e27c-17ea-4b38-8473-7ba3e0171c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-54-option-1&quot;)</value>
      <webElementGuid>60c96870-bb5a-4312-aee3-fc9dbf77cbaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-54-option-1']</value>
      <webElementGuid>2429ee00-21f6-425a-9060-17000e4ebce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-54-listbox']/div[2]</value>
      <webElementGuid>a06adfee-b628-4f03-b9b7-06cfb246298e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Comprehensive'])[1]/following::div[1]</value>
      <webElementGuid>2802a8d6-5070-43bf-9034-b5f78c796ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Total Loss Only'])[2]/following::div[8]</value>
      <webElementGuid>26cc67cb-e574-4e42-87a0-4a59ef7eb885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Total Loss Only'])[3]/preceding::div[1]</value>
      <webElementGuid>2ee99ea7-b27b-4e37-a49b-7e381ec3b628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>8c786ec0-e555-410b-b509-1213f189e38b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-54-option-1' and (text() = '1 Tahun Comprehensive + 1 Tahun TLO' or . = '1 Tahun Comprehensive + 1 Tahun TLO')]</value>
      <webElementGuid>def02ee8-4486-4737-a93d-9c4655310866</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
