<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__otr</name>
   <tag></tag>
   <elementGuidId>d5562053-ca06-4dfc-80bb-5a1acd88ffbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='otr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;otr&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce496158-e08c-41e7-a348-0a47d0cd9ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-[4px] h-[40px] block w-full form-input dark:bg-gray-700 dark:text-gray-300 dark:border-gray-600 placeholder:dark:text-gray-400 focus:border-primary focus:ring-primary focus:ring-opacity-40 dark:focus:ring-gray-500 dark:focus:border-gray-600 focus:outline-none focus:ring-0 text-sm text-neutral-700 placeholder:text-[#404040]</value>
      <webElementGuid>ab02c66e-818e-4416-aac0-8bfc1f7ecc67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fea08ea9-135d-41c2-bd4f-8c1732e32075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otr</value>
      <webElementGuid>32f89a7a-0381-4a10-8b9f-aeb9ca081a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>calculator-simulation-page-input-otr</value>
      <webElementGuid>813b62ed-ea70-4c31-8c37-8ae91bd468af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rp. 0</value>
      <webElementGuid>b57fad01-a151-4147-9d60-8b5d6bbf30a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;mx-auto grid w-full gap-4 px-6 lg:gap-0&quot;]/div[@class=&quot;mb-5 flex flex-col gap-5&quot;]/div[@class=&quot;min-w-0 rounded-lg border border-line shadow-card bg-white dark:bg-gray-800 shadow-xs grid grid-cols-10 gap-y-2 overflow-visible p-4&quot;]/div[@class=&quot;col-span-9&quot;]/div[@class=&quot;flex flex-col gap-1&quot;]/input[@class=&quot;rounded-[4px] h-[40px] block w-full form-input dark:bg-gray-700 dark:text-gray-300 dark:border-gray-600 placeholder:dark:text-gray-400 focus:border-primary focus:ring-primary focus:ring-opacity-40 dark:focus:ring-gray-500 dark:focus:border-gray-600 focus:outline-none focus:ring-0 text-sm text-neutral-700 placeholder:text-[#404040]&quot;]</value>
      <webElementGuid>f9538ba2-ee0b-4044-9f8f-e7292dfdebb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='otr']</value>
      <webElementGuid>9293f13d-6a4e-4434-aeda-4ac3ea2cf43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>0ba25ba6-3ba6-4296-96ce-81dd4b15278e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>54ae4f7c-8c4e-4936-96bd-d4d055bdad58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'otr' and @placeholder = 'Rp. 0']</value>
      <webElementGuid>68227eb3-fc82-412e-9a08-e0e9fc1b7f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
