import homePage from "../../support/PageObject-SEVA/pageObject-Homepage/homePage"
import refinancingPage from "../../support/PageObject-SEVA/pageObject-Refinancing/refinancingPage"
import urlSeva from "../../support/PageObject-SEVA/Url/urlSeva"



describe('TC001_RefinancingLeads_HomepageDanRefinancingPage_WithoutLogin', () => {
    it('TC001_RefinancingLeads_HomepageDanRefinancingPage_WithoutLogin', () => {
    
        cy.clearSession();
    //Homepage
        cy.log('HOMEPAGE✅✅✅')
        urlSeva.visitUrl()
        cy.wait(5000)
        homePage.clickBtnTerimaCookie()
        homePage.clickTabFasilitasDana()
        cy.wait(2000)
        homePage.clickBtnAjukanSekarang()
        homePage.inputNamaLengkap('Testing')
        homePage.inputNomorHp('89676848410')
        homePage.clickDropdownPilihKota()
        homePage.inputDropdownPilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        cy.wait(5000)
        homePage.clickValuePilihKota()
        homePage.clickCheckBox()
        homePage.clickOpsiBPKBMobil()
        cy.wait(2000)
        homePage.clickBtnKirim()
        cy.wait(10000)
        homePage.verifyRefinancingHomepage()

    //Top Widget
        cy.log('TOP WIDGET✅✅✅')
        urlSeva.visitUrl()
        cy.wait(5000)
        homePage.clickBtnFasilitasDana()
        cy.wait(5000)
        refinancingPage.clickBtnAjukanSekarangTopWidget()
        cy.wait(2000)
        // refinancingPage.inputNamaLengkap('Testing')
        // refinancingPage.inputNomorHp('89676848410')
        refinancingPage.clickDropdownPilihKota()
        refinancingPage.inputDropdownPilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        cy.wait(2000)
        refinancingPage.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        refinancingPage.clickCheckBox()
        refinancingPage.clickOpsiBPKBMobil()
        cy.wait(2000)
        refinancingPage.clickBtnKirim()
        cy.wait(10000)
        refinancingPage.verifyRefinancingPage()


    //Tutorial Submit
        cy.log('TUTORIAL SUBMIT✅✅✅')
        urlSeva.visitUrl()
        cy.wait(5000)
        homePage.clickBtnFasilitasDana()
        cy.wait(5000)
        refinancingPage.clickBtnDiSini()
        cy.wait(2000)
        // refinancingPage.inputNamaLengkap('Testing')
        // refinancingPage.inputNomorHp('89676848410')
        refinancingPage.clickDropdownPilihKota()
        refinancingPage.inputDropdownPilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        cy.wait(2000)
        refinancingPage.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        refinancingPage.clickCheckBox()
        refinancingPage.clickOpsiBPKBMobil()
        cy.wait(2000)
        refinancingPage.clickBtnKirim()
        cy.wait(10000)
        refinancingPage.verifyRefinancingPage()

    //Credit Simulation
        cy.log('CREDIT SIMULATION✅✅✅')
        urlSeva.visitUrl()
        cy.wait(5000)
        homePage.clickBtnFasilitasDana()
        cy.wait(5000)
        refinancingPage.clickBtnAjukanSekarangCreditSimulation()
        cy.wait(2000)
        // refinancingPage.inputNamaLengkap('Testing')
        // refinancingPage.inputNomorHp('89676848410')
        refinancingPage.clickDropdownPilihKota()
        refinancingPage.inputDropdownPilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        cy.wait(2000)
        refinancingPage.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        refinancingPage.clickCheckBox()
        refinancingPage.clickOpsiBPKBMobil()
        cy.wait(2000)
        refinancingPage.clickBtnKirim()
        cy.wait(10000)
        refinancingPage.verifyRefinancingPage()


    //Benefit Section
        cy.log('BENEFIT SECTION✅✅✅')
        urlSeva.visitUrl()
        cy.wait(5000)
        homePage.clickBtnFasilitasDana()
        cy.wait(5000)
        refinancingPage.clickBtnAjukanSekarangBenefitSection()
        cy.wait(2000)
        // refinancingPage.inputNamaLengkap('Testing')
        // refinancingPage.inputNomorHp('89676848410')
        refinancingPage.clickDropdownPilihKota()
        refinancingPage.inputDropdownPilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        cy.wait(2000)
        refinancingPage.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        refinancingPage.clickCheckBox()
        refinancingPage.clickOpsiBPKBMobil()
        cy.wait(2000)
        refinancingPage.clickBtnKirim()
        cy.wait(10000)
        refinancingPage.verifyRefinancingPage()

    //Floating Icon
        cy.log('FLOATING ICON✅✅✅')
        urlSeva.visitUrl()
        cy.wait(5000)
        homePage.clickBtnFasilitasDana()
        cy.wait(5000)
        refinancingPage.clickBtnFloatingIcon()
        cy.wait(2000)
        // refinancingPage.inputNamaLengkap('Testing')
        // refinancingPage.inputNomorHp('89676848410')
        refinancingPage.clickDropdownPilihKota()
        refinancingPage.inputDropdownPilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        cy.wait(2000)
        refinancingPage.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        refinancingPage.clickCheckBox()
        refinancingPage.clickOpsiBPKBMobil()
        cy.wait(2000)
        refinancingPage.clickBtnKirim()
        cy.wait(10000)
        refinancingPage.verifyRefinancingPage()

    //Leads Form
        cy.log('LEADS FORM✅✅✅')
        urlSeva.visitUrl()
        cy.wait(5000)
        homePage.clickBtnFasilitasDana()
        cy.wait(5000)
        // refinancingPage.inputNamaLengkapLeadsForm('Testing')
        // refinancingPage.inputNomorHpLeadsForm('89676848410')
        refinancingPage.clickDropdownPilihKotaLeadsForm()
        refinancingPage.inputDropdownPilihKotaLeadsForm('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        cy.wait(2000)
        refinancingPage.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        refinancingPage.clickCheckBoxLeadsForm()
        refinancingPage.clickOpsiBPKBMobilLeadsForm()
        cy.wait(2000)
        refinancingPage.clickBtnKirimLeadsForm()
        cy.wait(10000)
        refinancingPage.verifyRefinancingPage()

    })
})