<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_installment ADDM</name>
   <tag></tag>
   <elementGuidId>c59e15fc-d1be-4ebf-8f73-defbaa6c4103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ADDM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ADDM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio[name=&quot;ADDM&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0daf6743-cb7e-4f9b-a843-ea2eb4abb6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d96c495-4de0-436b-aeef-0dd31ba28ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex h-10 w-full items-center justify-center rounded border border-line bg-surface-plain px-6 py-4 text-body-small text-text-placeholder transition-all duration-200 ease-out focus-within:ring-1 focus-within:ring-line-link focus-within:ring-offset-2 hover:text-text-primary disabled:border-line disabled:bg-surface-disabled disabled:text-text-placeholder data-[state=checked]:border-line-informational data-[state=checked]:bg-surface-informational data-[state=checked]:font-semibold data-[state=checked]:text-text-informational disabled:data-[state=checked]:border-line-bold disabled:data-[state=checked]:bg-surface-neutral disabled:data-[state=checked]:font-semibold disabled:data-[state=checked]:text-text-placeholder</value>
      <webElementGuid>18621273-ebc6-4977-b126-d2aa44bb04df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ca171437-6e6d-48cc-99e2-85908bb46acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>92f1534c-91c3-4c92-b4ab-008d84288800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>4908b846-1df2-4983-ad43-1f5a49972c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ADDM</value>
      <webElementGuid>29d9ac53-541f-4cac-a221-0ee8cfd64f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ADDM</value>
      <webElementGuid>7ae1b64f-24f5-4e09-a697-1f3103c41f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>718abecf-2bd3-45c5-bc83-aafbffeb5fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>166498a1-7fb4-4058-a0f2-43266510842c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADDM</value>
      <webElementGuid>f78f4ef1-ea85-4d53-83c1-9cd2484b4c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ADDM&quot;)</value>
      <webElementGuid>3c50db0c-aa59-448c-8bf2-16a6285afaf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ADDM']</value>
      <webElementGuid>6d736dd3-8bc2-4aed-a0f5-a6018bb49b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[3]/div/div/div/form/div/div[2]/div[3]/div/div/div[6]/div[2]/div/button</value>
      <webElementGuid>1f41d584-10e7-468b-9698-b4227d5629f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QL Installment Type'])[1]/following::button[1]</value>
      <webElementGuid>f68ac929-c7c8-45cc-9019-d18796f6398d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QL Tenor (in years)'])[1]/following::button[6]</value>
      <webElementGuid>0cf41a13-b658-4d37-95d3-08a47e8894c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDB'])[1]/preceding::button[1]</value>
      <webElementGuid>5655972a-fb4a-47a6-ad2b-d0513e492cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QL Purchase Timeline'])[1]/preceding::button[2]</value>
      <webElementGuid>dba90c7e-fda1-412e-907a-b59bc8366099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADDM']/parent::*</value>
      <webElementGuid>64c9cc91-37de-444a-b170-e6ebe71e73b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/button</value>
      <webElementGuid>e71d6d9e-55bd-4a7d-a9c7-a0c4648e8c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'ADDM' and (text() = 'ADDM' or . = 'ADDM')]</value>
      <webElementGuid>e577d939-ed02-4db3-8ead-cf953dd8a43f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
