<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ayu Anggraini</name>
   <tag></tag>
   <elementGuidId>3612a552-f89a-4e39-9c10-03cf8801f676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.truncate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':rvh:']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Ayu Anggraini&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a05f922b-d79e-4c32-ad58-007fa97d4e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncate</value>
      <webElementGuid>192cde67-1488-4dbc-b729-6c4338833f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ayu Anggraini</value>
      <webElementGuid>7604467d-aebe-4840-a9ac-f955e05c83f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rvh:&quot;)/div[@class=&quot;wrapper flex items-center&quot;]/span[@class=&quot;truncate&quot;]</value>
      <webElementGuid>e8d609a8-b6d4-454f-b989-2ed7b7464901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':rvh:']/div/span</value>
      <webElementGuid>2acdb157-e9fc-4eab-b5a7-0b006c0891f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAASTESTSYNC'])[1]/following::span[1]</value>
      <webElementGuid>8ec203d8-bdfa-403b-913a-9ef2a0a7bf16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ayu Anggraini']/parent::*</value>
      <webElementGuid>6ea1f813-74a5-46d7-923f-667e118d6299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/span</value>
      <webElementGuid>6e4d4ba1-1260-43fb-88e7-1c8ef10dd1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ayu Anggraini' or . = 'Ayu Anggraini')]</value>
      <webElementGuid>760b3994-2b7d-4847-a638-327a71e63ef1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
