<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lihat Detail_plp</name>
   <tag></tag>
   <elementGuidId>95448c7b-88e1-4d92-aaaf-fe976466e892</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.cardetailcard_linkLihatDetail__SnloN</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//*[@data-testid = 'button-lihat-detail'])[${id}]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[4]/div/div/a[2]/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cf8986d8-ffa5-4ab2-8cfc-796100eaaf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>825049e5-51b1-463c-9dcf-a2ea5a25e9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>starts with</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cardetailcard_linkLihatDetail__SnloN</value>
      <webElementGuid>ede49c37-bc24-4753-8947-4820df118000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>button-lihat-detail</value>
      <webElementGuid>09ba7a2f-cb35-4982-b555-3673a64f71ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Detail</value>
      <webElementGuid>2ffab5f6-c755-4215-b9ce-bba12698f7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@data-testid = 'button-lihat-detail'])[${id}]</value>
      <webElementGuid>e63b147c-c807-4301-adee-8d1f0bbc6e0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/a[2]/div/span[2]</value>
      <webElementGuid>e38f05de-2fe8-4657-9dea-5e6e8dd38e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenor'])[1]/following::span[2]</value>
      <webElementGuid>08a72ef2-fb13-4a16-a168-8948c7c38f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hitung Kemampuan'])[2]/preceding::span[1]</value>
      <webElementGuid>d620d949-e594-4303-8ea5-f4afd8815cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Detail']/parent::*</value>
      <webElementGuid>00f64673-f669-4df0-ab6c-db8940f57d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>6a3cc88d-2ba7-4035-af80-aaab7c97f44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Lihat Detail' or . = 'Lihat Detail')]</value>
      <webElementGuid>319899b9-7382-4e92-9901-f67b610131dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
