<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Anda dapat mengubah Data Pribadi di Profi_166693</name>
   <tag></tag>
   <elementGuidId>c8996601-cd02-4203-8edc-e00cac28b59d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(15)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3af9b5d5-84e2-4367-bacf-e3380b2b0970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anda dapat mengubah Data Pribadi di Profil Anda sewaktu-waktu, memilih untuk tidak menerima komunikasi dari Kami dan/atau menarik persetujuan atas Pemanfaatan Data Pribadi Anda.</value>
      <webElementGuid>3480077f-ca94-495b-bff5-461ba4037a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;shadow-lg w-full top-0 z-10 bg-transparent&quot;]/div[@class=&quot;container max-w-[1197px] py-[3rem] tablet:py-[107px]&quot;]/div[@class=&quot;entry-content font-[Open sans] text-[12px] mobile:text-[16px]&quot;]/p[15]</value>
      <webElementGuid>1e1a73b5-5dfc-4800-84f9-9287d45a74ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[15]</value>
      <webElementGuid>5996a64e-2f7b-4f62-828a-e261a9506cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Anda dapat mengubah Data Pribadi di Profil Anda sewaktu-waktu, memilih untuk tidak menerima komunikasi dari Kami dan/atau menarik persetujuan atas Pemanfaatan Data Pribadi Anda.' or . = 'Anda dapat mengubah Data Pribadi di Profil Anda sewaktu-waktu, memilih untuk tidak menerima komunikasi dari Kami dan/atau menarik persetujuan atas Pemanfaatan Data Pribadi Anda.')]</value>
      <webElementGuid>55350b67-1f1c-4d28-96fa-3e8f98b694d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
