<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Assignment</name>
   <tag></tag>
   <elementGuidId>535fb21b-93e5-4e7a-ba31-d8f4178097a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rd:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f3547ec-0139-4d42-8f3c-b238167bffeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group/item flex h-20 w-full cursor-pointer items-center justify-center gap-6 bg-surface-plain hover:bg-hover-white group-hover/sidebar:justify-start group-hover/sidebar:pl-7 group-hover/sidebar:pr-4 group-hover/sidebar:transition-all group-hover/sidebar:duration-100 group-hover/sidebar:ease-in-out aria-selected:hover:bg-surface-plain [&amp;_svg]:text-icon-disabled [&amp;_svg]:aria-selected:text-icon-brand-red</value>
      <webElementGuid>d7f1900e-a718-473e-84af-35f421673307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a93bab8-84b3-44d4-8f04-1a99e59e273c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:re:</value>
      <webElementGuid>5231607c-6ff1-4ac3-8eaf-d8270b1f6482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f664643-36e0-4501-a7e9-04e84da5b2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>da3f6ef3-3543-4856-9f02-706e161e4f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>vertical</value>
      <webElementGuid>1e74d831-ba07-44e4-a9a6-d8ad787bbcf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:rd:</value>
      <webElementGuid>a688cb73-11fc-4d87-b9e2-294bf0b20635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2e2e6b64-635b-424b-80f8-754edf775601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assignment</value>
      <webElementGuid>20843971-b288-4b6d-b6e8-ebd3ca1ebcb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rd:&quot;)</value>
      <webElementGuid>3bde2823-fe2a-45ec-9adc-d3a68339b0d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='radix-:rd:']</value>
      <webElementGuid>42157f05-330b-4751-a431-f116d34db747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarCRM']/div[2]/div/div[2]/div/div/div/div[5]/h3/div</value>
      <webElementGuid>3446bb5f-85b6-43eb-8701-c6e62d6864e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to SEVA CRM'])[1]/following::div[22]</value>
      <webElementGuid>a35257cc-7884-4a18-9b5d-98839b4529e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leads Workstation'])[1]/following::div[25]</value>
      <webElementGuid>5895b42b-54dc-4054-9f86-777b2e252ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/h3/div</value>
      <webElementGuid>6f063aed-26a4-4625-b5a4-e35af46a4897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'button' and @id = 'radix-:rd:' and (text() = 'Assignment' or . = 'Assignment')]</value>
      <webElementGuid>5577bc7b-f90b-4f95-b5ba-64c78f215237</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
