<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_igpost_rh_quiz</name>
   <tag></tag>
   <elementGuidId>26b8a844-1388-44f0-9f39-941776a5017b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='ridwanHanifUpdate_instagramPostContainerSingle__OzrHx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='ridwanHanifUpdate_instagramPostContainerSingle__OzrHx']</value>
      <webElementGuid>af3cdb22-b87c-4ddd-a84c-ec2fc1a68316</webElementGuid>
   </webElementProperties>
</WebElementEntity>
