<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kamu_bertanya_seva_menjawab_area</name>
   <tag></tag>
   <elementGuidId>72892a6d-3ad4-44f8-bfa0-b2d964823c44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Kamu Bertanya SEVA Menjawab']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='ridwanHanifFaq_header__iJ_1r']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='ridwanHanifFaq_header__iJ_1r']</value>
      <webElementGuid>f86b54aa-4db1-43b3-a29e-191f4ee6f4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apa itu SEVA?</value>
      <webElementGuid>b899d2c5-5f5b-4700-9483-f405edff52c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ridwanHanifFaq_questionText__ilgkt</value>
      <webElementGuid>0023f690-45e6-4450-bb22-92ced5599ea6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
