<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_manage column</name>
   <tag></tag>
   <elementGuidId>1e1b091b-f275-4b9d-abe4-ec6d7b2fe4aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.m-auto.size-4.text-icon-neutral</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[135]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>38ca0968-4a7b-47cd-bd5c-fbf6aadb47ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>d6093dc8-9479-4ef9-9593-63278beec145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>6acb3f15-a7a3-4f1e-8e8a-80c3fe5276d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>dfa8e1e9-d2c7-4e89-9aa6-162cc58fc8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>62add06c-1568-49e5-ae29-2cf735b120db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>2cc16edb-210c-4fb3-bcee-d03b479b7b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto size-4 text-icon-neutral</value>
      <webElementGuid>bf91ac77-15fd-41b0-b177-7616f8bb3dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rkg:-content-ALL&quot;)/div[1]/div[@class=&quot;flex gap-4 overflow-hidden&quot;]/div[@class=&quot;relative w-full overflow-hidden&quot;]/button[@class=&quot;absolute right-0 top-0 z-10 m-0 size-12 appearance-none rounded-tr-lg border-r border-t border-line bg-surface-subtle transition-all hover:bg-hover-white focus-visible:rounded-none focus-visible:ring-2 focus-visible:ring-line-link&quot;]/svg[@class=&quot;m-auto size-4 text-icon-neutral&quot;]</value>
      <webElementGuid>bee26c85-729e-4235-a496-8bc9386fe55e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[135]/following::*[name()='svg'][1]</value>
      <webElementGuid>0b7f85a9-c28b-4227-8eeb-5468612eb0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[134]/following::*[name()='svg'][1]</value>
      <webElementGuid>b2e5b12c-9fee-4735-b865-7254e717a849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::*[name()='svg'][11]</value>
      <webElementGuid>f28794c6-0ccc-4f1e-b9e3-ea03a598b24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::*[name()='svg'][11]</value>
      <webElementGuid>833e7edb-e7b0-4fe4-a3b8-87f031a2ce5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
