<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>registrasinegativecase</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>79d050e2-a98f-43cf-92c4-aa0a18d72825</testSuiteGuid>
   <testCaseLink>
      <guid>ce53fef2-9eae-4988-a549-84e7b423f917</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/RA 003 - Register Negative Case Null Input</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1ed6ba19-1d43-4a89-aca0-d73e4a5da55b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Register Negatif Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12f16fdc-7641-45a3-8191-5dc4d6ea6225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce6c12c-c9aa-4a1a-88fb-8750a11fc273</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ed6ba19-1d43-4a89-aca0-d73e4a5da55b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Nama</value>
         <variableId>9b9de51b-8dd6-4a52-857e-c810cc6a9e69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ed6ba19-1d43-4a89-aca0-d73e4a5da55b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>bd4e1d7d-049a-41aa-bf39-2c9b62325c2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ed6ba19-1d43-4a89-aca0-d73e4a5da55b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Checkbox</value>
         <variableId>86ad1270-457a-4b43-af02-9f5f6a74872c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ed6ba19-1d43-4a89-aca0-d73e4a5da55b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Tanggal lahir</value>
         <variableId>f824c801-0768-4812-8cb4-be8298bb8810</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d165b5a-297b-481b-9042-13f47c72634c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/RA 004 - Register Negative Input Email dan Reverral</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12f16fdc-7641-45a3-8191-5dc4d6ea6225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce6c12c-c9aa-4a1a-88fb-8750a11fc273</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9de51b-8dd6-4a52-857e-c810cc6a9e69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd4e1d7d-049a-41aa-bf39-2c9b62325c2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86ad1270-457a-4b43-af02-9f5f6a74872c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f824c801-0768-4812-8cb4-be8298bb8810</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55d2854d-fc1f-4da9-810d-efc45bb34024</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bcdd6d0a-dcf1-4675-82b0-b09c038211f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/RA 005 - Syarat Ketentuan dan Kebijakan Privasi</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12f16fdc-7641-45a3-8191-5dc4d6ea6225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce6c12c-c9aa-4a1a-88fb-8750a11fc273</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
