<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filter Homepage Banner Management</name>
   <tag></tag>
   <elementGuidId>dcc3f2b6-9361-4378-97c0-1a7bc09232ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b064b1a-ea23-4678-88d8-73ac9c59035c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fb43b79-eb81-4aed-b69e-373e337cdd82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>d29709de-f58c-46fa-9362-77f7f8de1992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>788505cb-03b0-49b6-adfe-560a6a1f3857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r1:</value>
      <webElementGuid>851aaa85-d9b5-466e-8d30-5df912ead660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>27e29856-282b-4627-8a0e-c19474ec562f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center gap-2 rounded-lg border border-gray-300 px-4 py-2 align-bottom text-sm/5 font-medium text-gray-600 transition-colors duration-150 hover:border-gray-500 focus:border-gray-500 focus:outline-none focus:ring focus:ring-primary-300 focus:ring-opacity-40 active:bg-transparent active:text-gray-500 disabled:pointer-events-none disabled:bg-gray-300 disabled:opacity-50 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-400</value>
      <webElementGuid>5156e39a-e5d2-4944-acbf-83ebd0750759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>8bcc7efa-d519-43a8-a3ea-48e8015f67ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;mx-auto grid gap-4 px-6 lg:gap-0&quot;]/div[@class=&quot;mb-[20px] flex flex-col items-center justify-between gap-2 lg:flex-row&quot;]/div[@class=&quot;flex gap-2&quot;]/button[@class=&quot;inline-flex items-center justify-center gap-2 rounded-lg border border-gray-300 px-4 py-2 align-bottom text-sm/5 font-medium text-gray-600 transition-colors duration-150 hover:border-gray-500 focus:border-gray-500 focus:outline-none focus:ring focus:ring-primary-300 focus:ring-opacity-40 active:bg-transparent active:text-gray-500 disabled:pointer-events-none disabled:bg-gray-300 disabled:opacity-50 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-400&quot;]</value>
      <webElementGuid>b238d9a8-e074-48f1-85db-5cc0cff7ca58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>d9f052b3-ce16-4fb9-9a71-57e4f14fad57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/button</value>
      <webElementGuid>ccc8e435-bc7f-4dc8-830d-54183b67e068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Homepage Banner Management'])[2]/following::button[1]</value>
      <webElementGuid>a70a93dd-e166-4507-bcd8-89250230dc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Management'])[1]/following::button[4]</value>
      <webElementGuid>5be230eb-f613-4cba-99b8-cd963a3ab152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New'])[1]/preceding::button[1]</value>
      <webElementGuid>c768f5bf-02db-4197-8161-10e27967c53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button</value>
      <webElementGuid>ce675723-b3c0-4a50-be0f-66c19b20d05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Filter' or . = 'Filter')]</value>
      <webElementGuid>d4952fb0-1d3b-4239-96de-ac859693746d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
