<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_All Leads</name>
   <tag></tag>
   <elementGuidId>e215a131-07e0-4cff-b640-c6b1e4dc7472</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.truncate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r162:']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>30f82a8f-c14a-4389-b9c2-a5f50e9b9b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncate</value>
      <webElementGuid>d5230cc7-dbde-41a6-89f9-d7a9143c599c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Leads</value>
      <webElementGuid>f29c19df-2af9-4a7b-93e8-ba5694e716fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r162:&quot;)/div[@class=&quot;group flex w-full cursor-pointer select-none items-center justify-between rounded border-0 p-2 text-left text-body-small hover:bg-primaryRed-10 focus:bg-primaryRed-50 disabled:hover:bg-white bg-white&quot;]/div[@class=&quot;truncate&quot;]</value>
      <webElementGuid>f9b082db-da19-4861-a514-5d5e9de7db65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r162:']/div/div</value>
      <webElementGuid>46d103ab-ab93-4fd9-a46f-56941fbfe7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public Columns'])[1]/following::div[3]</value>
      <webElementGuid>8af180d6-81ea-427d-86d8-b03ef5c0f36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Column not found. Try other keywords'])[2]/following::div[6]</value>
      <webElementGuid>8d0e8464-0f8c-4cf7-9617-9dbab2190bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test column 1'])[1]/preceding::div[4]</value>
      <webElementGuid>c9d43013-23e0-4b41-b462-a85ced48f5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::div[4]</value>
      <webElementGuid>842d3c35-c371-4054-b8c5-38a643b99cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>523d325b-f133-4a7a-8a5b-4575bfba6a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'All Leads' or . = 'All Leads')]</value>
      <webElementGuid>266b37fc-1230-4218-925b-4194daa7692d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
