<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Leads Tracking</name>
   <tag></tag>
   <elementGuidId>f93310f5-c31c-43f0-8f18-6e74018c1ea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='radix-:rb:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c6e52bd-b97c-43a4-be02-3a53e02e861c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group/item flex h-20 w-full cursor-pointer items-center justify-center gap-6 bg-surface-plain hover:bg-hover-white group-hover/sidebar:justify-start group-hover/sidebar:pl-7 group-hover/sidebar:pr-4 group-hover/sidebar:transition-all group-hover/sidebar:duration-100 group-hover/sidebar:ease-in-out aria-selected:hover:bg-surface-plain [&amp;_svg]:text-icon-disabled [&amp;_svg]:aria-selected:text-icon-brand-red aria-selected:pointer-events-none</value>
      <webElementGuid>ed011701-1d57-4e63-8420-81d1e9577f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>504db855-3274-4cda-bad2-5c456b1caa2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:rc:</value>
      <webElementGuid>a9bdcd42-5bbd-43f4-9351-f36d69c55d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>21240496-aa09-463e-b248-7a4599d7e83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>065fa2a4-e547-47c5-b51c-73840d9f38f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>vertical</value>
      <webElementGuid>554b2cf5-1cd5-47c2-8d37-db73b7c69d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:rb:</value>
      <webElementGuid>ecce19ce-741b-4989-b74e-c9e610bef303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aa2570e4-f0d2-4fc6-be0b-a21935e554b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/leads-tracking</value>
      <webElementGuid>4fbce852-1f2d-4fb2-9406-cdc1d2b7613e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leads Tracking</value>
      <webElementGuid>cfad6335-7c5a-4b7e-babb-a4845d38f211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rb:&quot;)</value>
      <webElementGuid>8eb620de-fa77-4d0b-95be-aba21acfa94b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='radix-:rb:']</value>
      <webElementGuid>2ecd153c-19b4-4dfb-96af-39063c2e65cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarCRM']/div[2]/div/div[2]/div/div/div/div[4]/h3/a</value>
      <webElementGuid>89521fd3-abc9-4f36-b52a-88b3db360516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to SEVA CRM'])[1]/following::a[4]</value>
      <webElementGuid>446e58fb-4a16-4412-a7ce-c439493a2340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leads Workstation'])[1]/following::a[4]</value>
      <webElementGuid>540446f7-778b-44f4-ab7c-823b9849a19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/leads-tracking')]</value>
      <webElementGuid>86e9e58e-d047-4016-ac3e-d4f444f400c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/h3/a</value>
      <webElementGuid>35189453-61a6-474b-a5e4-1f7701beb5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'radix-:rb:' and @href = '/leads-tracking' and (text() = 'Leads Tracking' or . = 'Leads Tracking')]</value>
      <webElementGuid>604b12d5-79bf-4b66-8aae-de8dcc5dc17a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
