<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputName</name>
   <tag></tag>
   <elementGuidId>9ac12ddd-2c4a-444e-8938-b2af0b564dcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.input_input__MAvlc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2602abc2-1e97-4b1b-9522-6f0c8e5e0102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>field-input-leads-nama-lengkap</value>
      <webElementGuid>2b98f64e-73bf-4401-9149-5f590452b77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_input__MAvlc</value>
      <webElementGuid>0d9edef3-a076-49fb-a396-24e790274387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama lengkap</value>
      <webElementGuid>a9343bcf-5fa9-4864-869d-d26c24d14e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[4]/div[@class=&quot;ant-modal-root css-p7e5j5&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal css-p7e5j5 full&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[1]/div[@class=&quot;leadsFormPrimary_foreground__fC8B5&quot;]/div[@class=&quot;leadsFormPrimary_form__P9V0v&quot;]/div[1]/input[@class=&quot;input_input__MAvlc&quot;]</value>
      <webElementGuid>591570af-2c78-4d6f-a515-019bb459236f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>9d2b5f1e-75e5-4a11-a9f4-9d1ec8629d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/input</value>
      <webElementGuid>050ed456-2b65-4482-8b6f-63c813ca042b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan nama lengkap']</value>
      <webElementGuid>36ba1093-4c29-44f1-a7f7-0681a582cf59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
