<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cmNote</name>
   <tag></tag>
   <elementGuidId>9a46dde7-e992-46aa-937a-da42c967260f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='cmNote']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cmNote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Write notes here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>26822156-0274-4d7c-8b19-226fd2aac636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmNote</value>
      <webElementGuid>580a00f9-a190-481f-9ec5-24a4ed67a9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>peer m-0 min-h-[120px] w-full !resize-none rounded border border-solid border-line bg-surface-plain p-2 pr-7 text-body-small text-text-primary outline-none placeholder:text-text-placeholder transition-all focus-within:border-line-bold read-only:bg-surface-neutral read-only:text-text-primary disabled:bg-surface-disabled disabled:text-text-disabled</value>
      <webElementGuid>643da8e5-136a-4d4e-8f57-a12183d668dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cmNote</value>
      <webElementGuid>84a5f1ea-d908-410e-b66c-8bc7c9164b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c131df4b-8cad-4642-81ce-3a152b16364a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write notes here</value>
      <webElementGuid>7582666b-4f3c-450b-b344-3b4c87e6ad4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmNote&quot;)</value>
      <webElementGuid>b4db3540-05d0-4f00-9ba5-59872a052044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='cmNote']</value>
      <webElementGuid>d24f80fe-7466-48d9-8e1b-e8e3fa2fdc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r57:']/form/div[2]/div/div[5]/div[2]/div/div[2]/div/textarea</value>
      <webElementGuid>cf3ec549-d76b-40ff-b8ce-0b89726cff41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>444f7baa-175b-4784-9d67-f52baad4dffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'cmNote' and @name = 'cmNote' and @placeholder = 'Write notes here']</value>
      <webElementGuid>11369a00-8145-4ea4-81fd-51e885fba5cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
