<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_downPaymentAmount</name>
   <tag></tag>
   <elementGuidId>5ba5ef20-7c40-4c02-9af6-6a76c5a0e706</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;downPaymentAmount&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'Masukkan DP' and @name = 'downPaymentAmount']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='downPaymentAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffa4f2f7-25bb-41d4-9089-adde3aa89029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>ffce0dee-cbb9-450a-9661-a7fc19b8564f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan DP</value>
      <webElementGuid>85d93ae4-e336-4bd3-acf7-8f1a6693e7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>downPaymentAmount</value>
      <webElementGuid>f217919e-a979-49c6-8212-9e94b5219634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>field-input-dp</value>
      <webElementGuid>c4597b69-813a-4072-b9b3-ce7652940ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-1fumvat ant-input-outlined dpFormWithPercentage_inputAmount__5D7eQ</value>
      <webElementGuid>cd781995-5f57-48d8-b60e-ad63c856e3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rp95.000.000</value>
      <webElementGuid>e7f5d60f-e443-4826-8d6b-9c0b2070b961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loan-calculator-generate-ia-form-dp&quot;)/div[@class=&quot;dpFormWithPercentage_wrapper__uK_Vx&quot;]/div[@class=&quot;dpFormWithPercentage_inputGroup__wkV0p&quot;]/input[@class=&quot;ant-input css-1fumvat ant-input-outlined dpFormWithPercentage_inputAmount__5D7eQ&quot;]</value>
      <webElementGuid>36ca61d5-76af-4c48-af81-14548d88cbf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='downPaymentAmount']</value>
      <webElementGuid>2de6241f-8f95-4677-afc2-4a9eb3fcb413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loan-calculator-generate-ia-form-dp']/div/div/input</value>
      <webElementGuid>21e33313-5721-4d17-ad57-2c48cd2a0246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>197cfee3-a815-46b6-9654-5a9f288e06e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = 'Masukkan DP' and @name = 'downPaymentAmount']</value>
      <webElementGuid>7d1fe2e6-ec89-4c5d-99b8-58aeb220a8e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
