<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Rp475.000.000</name>
   <tag></tag>
   <elementGuidId>48445d9e-a91d-448c-916c-5901ca5317a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.inputMultilineSelect_selectedLabel__Osv4Z</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c658c3e6-c1ad-450a-a80b-3c78b66516bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputMultilineSelect_selectedLabel__Osv4Z</value>
      <webElementGuid>a5cb3fc3-8ca3-431f-9814-ade8156b503f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp475.000.000</value>
      <webElementGuid>efee1e7e-f4e5-431f-a21f-321625f6f09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loan-calculator-generate-ia-form-variant&quot;)/div[@class=&quot;inputMultilineSelect_container__pfjb9&quot;]/div[@class=&quot;inputMultilineSelect_inputArea__LD9YF&quot;]/div[1]/p[@class=&quot;inputMultilineSelect_selectedLabel__Osv4Z&quot;]</value>
      <webElementGuid>7242c0af-0bd7-47b3-8a0e-c55382f6a46b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loan-calculator-generate-ia-form-variant']/div[2]/div/div/p[2]</value>
      <webElementGuid>a24129f5-9e60-47ba-9068-d630664af66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Varian mobil'])[1]/following::p[2]</value>
      <webElementGuid>c3df6ac2-887c-4137-afa1-40fdb9f36859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wuling Cloud EV'])[1]/following::p[2]</value>
      <webElementGuid>07dbf2dc-d9b1-45fd-ba3c-bac3edd7cf98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp475.000.000'])[2]/preceding::p[2]</value>
      <webElementGuid>05c291ac-d6ae-4009-8858-532b19a0c7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp545.000.000'])[1]/preceding::p[3]</value>
      <webElementGuid>c7fb10d9-d869-43b6-9d80-62ecde1ac9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp475.000.000']/parent::*</value>
      <webElementGuid>a019b5fb-7c04-4c89-9fd0-d2d9eae6e63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>63dd0148-0b5a-47d0-aab3-f1f8f97a0bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Rp475.000.000' or . = 'Rp475.000.000')]</value>
      <webElementGuid>82b69eca-9c5f-4b00-9d08-226725e306e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
