<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title text_Link Instant Approval</name>
   <tag></tag>
   <elementGuidId>faa24d6f-cef7-4014-8fed-8ddfe6ada4c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[starts-with(@class, 'lcNewCarGenerateIa_headingText')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.lcNewCarGenerateIa_headingText__ANB_5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c5f32a34-ceff-4f7b-b764-3514c0849339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>starts with</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcNewCarGenerateIa_headingText</value>
      <webElementGuid>b80d0cc3-81a5-4855-8ab1-f8f64da702ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung Kemampuan Customer</value>
      <webElementGuid>4451b76e-fcdd-4cc2-8f91-a314ca09b58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;pageLayout_container__nDevq&quot;]/div[@class=&quot;lcNewCarGenerateIa_content__Ay2NT&quot;]/div[@class=&quot;lcNewCarGenerateIa_headingSection__JpPUN&quot;]/h2[@class=&quot;lcNewCarGenerateIa_headingText__ANB_5&quot;]</value>
      <webElementGuid>5836fdd9-04d6-4df2-8e4d-bc32256cdb37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/h2</value>
      <webElementGuid>d580a987-d4d8-4ad1-9ac0-d2b49b655a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOYOTA GRAND AVANZA 1.3 G M/T 2021'])[1]/following::h2[1]</value>
      <webElementGuid>819ada42-5d92-430a-b310-d710bdedcc36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAIHATSU XENIA 1.3 X M/T GRAND 2020'])[1]/following::h2[1]</value>
      <webElementGuid>2d60b679-e8be-437a-b154-862a8aaf464e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Isi data secara lengkap untuk membuat link Instant Approval untuk customermu.'])[1]/preceding::h2[1]</value>
      <webElementGuid>d1f10446-09fb-48a7-bc0b-6857656fc9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama CSA'])[1]/preceding::h2[1]</value>
      <webElementGuid>f38254c0-c9ee-413b-b627-efb10c8f1f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Link Instant Approval']/parent::*</value>
      <webElementGuid>3623dc1d-7f4b-4aea-bf7c-4bb60fcb2add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>c3dca07a-3e85-404f-9646-955469542f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Link Instant Approval' or . = 'Link Instant Approval')]</value>
      <webElementGuid>d2d8df50-f1c7-4fbe-879a-5c676cad2bf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
