<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mau (1)</name>
   <tag></tag>
   <elementGuidId>9e8cec53-4e69-47a3-975e-dcff6abd936e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optInText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='optInText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32539025-28b6-4eb4-be04-366e9b3fc09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-id</name>
      <type>Main</type>
      <value>{{webPushPlatformData.chrome.domain_type == 'https' ? 'optInText': 'optInTextConventional'}}</value>
      <webElementGuid>a2cd4362-6e8d-4526-8391-29afbe320c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{'color': webPushPreview['bannerv2']['web']['allowButton']['color'],'background':webPushPreview['bannerv2']['web']['allowButton']['backgroundColor']}</value>
      <webElementGuid>02e34505-9450-4c19-be38-e969d356e98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>54be470c-a15d-4f72-b04d-a464196b3394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optInText</value>
      <webElementGuid>f02f2000-fda4-4b69-b0a9-dc08509c533c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mau</value>
      <webElementGuid>a6c91d2a-c759-413f-9dda-4fac9373df53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optInText&quot;)</value>
      <webElementGuid>4f2a3830-8e9a-4b9d-b910-efb6ded37f70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='optInText']</value>
      <webElementGuid>35b60994-17c1-4e88-a36f-9e3eaab2a6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktopBannerWrapped']/div/div[3]/div/button[2]</value>
      <webElementGuid>1c392630-baf8-46e5-9519-d28d26730b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>3c123f3a-2479-4016-9f5f-ffd3cd075bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'optInText' and (text() = 'Mau' or . = 'Mau')]</value>
      <webElementGuid>20721f0f-ae58-42ca-9612-552325811338</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
