<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hitung Kemampuan</name>
   <tag></tag>
   <elementGuidId>145e4653-039e-427b-8b0d-71c3338959ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div[5]/div[2]/div/div/div/div/div/button[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href=&quot;/kalkulator-kredit/${mobil}&quot;]//button[@data-testid=&quot;button-hitung-kemampuan-plp&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.alternativeCarCard_cardWrapper__If92O.cardshadow_cardShadow__Pr8Ek > button.button_primaryDarkBlue__SJzXm.button_big__H6cBN.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2141326-fc64-49a4-b929-3aa2d3262897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_primaryDarkBlue__SJzXm button_big__H6cBN undefined</value>
      <webElementGuid>2a2b771e-d567-4a0c-95e0-7aa0e2ff9d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>button-hitung-kemampuan-plp</value>
      <webElementGuid>0205e894-acf4-41f3-b02c-1cff6b337697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung Kemampuan</value>
      <webElementGuid>7986c823-3b59-4f79-82eb-5628c4f27519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href=&quot;/kalkulator-kredit/${mobil}&quot;]//button[@data-testid=&quot;button-hitung-kemampuan-plp&quot;]</value>
      <webElementGuid>ffc3e93c-25fd-4474-95ac-ac44b637e6b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[5]/div[2]/div/div/div/div/div/button[2]</value>
      <webElementGuid>1d753c97-65d7-4d06-a601-eb2f2ce908ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail'])[1]/following::button[1]</value>
      <webElementGuid>9823d340-24f6-4fbb-addd-e981fa6bb7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp2.550.000/bln'])[1]/following::button[2]</value>
      <webElementGuid>4a488708-658e-4702-98b9-2cf72c7d9266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daihatsu All New Ayla'])[1]/preceding::button[1]</value>
      <webElementGuid>9f75a1c7-77ce-424a-934d-20bbcac2afd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hitung Kemampuan']/parent::*</value>
      <webElementGuid>61ae38e0-5446-4fc0-93e5-87a39bfaebbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/button[2]</value>
      <webElementGuid>5b82bf98-07d8-428d-8256-42daa7e4763d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Hitung Kemampuan' or . = 'Hitung Kemampuan')]</value>
      <webElementGuid>479026ab-e26a-4dfc-be12-33e5cb1286a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
