<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SUV</name>
   <tag></tag>
   <elementGuidId>ebccfb36-c862-43cd-8553-a28310a71747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='MPV'])[1]/following::div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = ' SUV' or . = ' SUV')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.formSelectBrandCar_boxOnclick__5H7Ga</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c79e660a-873e-4f50-9227-753fb42b8b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>377f0a03-6a20-467b-9818-e68f954b9e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formSelectBrandCar_boxOnclick__5H7Ga</value>
      <webElementGuid>9a85e2f0-9d41-4015-9a00-681b468d77dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>type-suv</value>
      <webElementGuid>17855a36-cef3-4c9f-80d2-04faff3d3c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SUV</value>
      <webElementGuid>ec16f6e1-9624-4c10-8d6a-4c3b2a74d41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/reach-portal[1]/div[1]/div[2]/div[2]/div[1]/div[@class=&quot;formSelectBrandCar_container__JyNan&quot;]/div[@class=&quot;ant-space css-nllxry ant-space-horizontal ant-space-align-center&quot;]/div[@class=&quot;ant-space-item&quot;]/div[@class=&quot;formSelectBrandCar_boxOnclick__5H7Ga&quot;]</value>
      <webElementGuid>b4322215-7120-4cd4-af2e-e1db00ac7853</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MPV'])[1]/following::div[2]</value>
      <webElementGuid>2cab60c0-55cc-4b71-aae0-a9b3e17b06d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mulai Cari Mobil'])[1]/following::div[17]</value>
      <webElementGuid>a2428512-d782-4f97-b697-2a73f97ed16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedan'])[1]/preceding::div[2]</value>
      <webElementGuid>40ea171f-f486-4d75-8b31-54f3ab05f966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div[2]/div</value>
      <webElementGuid>8c8c5229-3bbf-4de8-97ba-c191258d8d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' SUV' or . = ' SUV')]</value>
      <webElementGuid>f563a047-512f-43f3-acf0-d1622a3eb445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
