<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TipeMobil</name>
   <tag></tag>
   <elementGuidId>aa12d304-5f55-4554-ab9e-e71c1b5b0e68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp-upper-content']/div[2]/div/div/div[2]/div/div[2]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class = 'selectWidget_placeholder__oBYXe'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5e1db17-cb09-49ad-b689-710d4f7cfd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectWidget_placeholder__oBYXe</value>
      <webElementGuid>787e5693-a2ae-4f8c-9e78-0c9a5fa061f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MPV, SUV, Sedan, Hatchback, Sport, Truk Pickup, Minivan, Coupe</value>
      <webElementGuid>978a0dea-ad62-4729-8956-c1b4f44e3cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class = 'selectWidget_placeholder__oBYXe'])[2]</value>
      <webElementGuid>092be82d-7153-41a9-94d5-9ce62498e3c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp-upper-content']/div[2]/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>f03077ed-cba7-4e04-ac6c-ad52b6015174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe'])[1]/following::div[1]</value>
      <webElementGuid>9c6e7d61-0cbb-450a-a999-34d02aa064e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toyota, Daihatsu, Isuzu, BMW, Peugeot, Hyundai'])[1]/following::div[7]</value>
      <webElementGuid>76dacfa7-4159-4fbc-9a35-2222b94eddbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimasi Harga'])[1]/preceding::div[5]</value>
      <webElementGuid>20b8dc28-2073-412e-8bad-1cf171f7acfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>b25654c6-bbba-43c8-a9ef-7f9346adcfda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'MPV, SUV, Sedan, Hatchback, Sport' or . = 'MPV, SUV, Sedan, Hatchback, Sport')]</value>
      <webElementGuid>68c71fa2-020c-4832-bd40-17d953e3bde0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
