<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>2e1fc0d7-98a3-431f-8436-feee7efbcc71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;CBQA ISO 27001&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>[H015] - verify user see about seva text - footer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0dac0da7-42fe-482c-9d79-05dfa490fb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>CBQA ISO 27001</value>
      <webElementGuid>15c7e1d8-065f-4f00-afb2-caaed2800c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatest-id</name>
      <type>Main</type>
      <value>logo-iso</value>
      <webElementGuid>8cc71d88-94b0-402b-b409-16ec11b29171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Ficon%2Fiso.webp&amp;w=32&amp;q=75 1x, /_next/image?url=%2Frevamp%2Ficon%2Fiso.webp&amp;w=64&amp;q=75 2x</value>
      <webElementGuid>8c32c2b0-48b7-47ad-81c9-480395d7be03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Ficon%2Fiso.webp&amp;w=64&amp;q=75</value>
      <webElementGuid>17d0d10c-d922-4779-b62f-8ff5833a0bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>2c03a3f3-9bba-41c4-a3e7-876d692178e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>955a9b3e-cbc2-4b9d-95c8-e4c0175ac78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>934d7f7e-5288-469a-b621-6234c256321e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>343301e7-040f-409c-a55b-713efab9d413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>88cc6b05-c918-4f2e-9325-06a35e6bafaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;index_main__K2Wvo&quot;]/div[@class=&quot;index_container__KNQ8V&quot;]/footer[@class=&quot;footerMobile_container__FOSPi&quot;]/div[@class=&quot;footerMobile_contentContainer__J40vG&quot;]/div[@class=&quot;footerMobile_isoWrapper__53r9r&quot;]/img[1]</value>
      <webElementGuid>e8b886c4-6268-46ec-b51e-fc0cde3b01f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/footer/div/div[3]/img</value>
      <webElementGuid>8d13839c-4a67-4102-857b-2904b8733fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='CBQA ISO 27001']</value>
      <webElementGuid>704ac688-f1c6-432d-a752-f7b87e2cf7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div[3]/img</value>
      <webElementGuid>739eaccc-e177-4655-87ae-656ac153569a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'CBQA ISO 27001' and @src = '/_next/image?url=%2Frevamp%2Ficon%2Fiso.webp&amp;w=64&amp;q=75']</value>
      <webElementGuid>56a2c783-57ee-4efd-8712-d0cc33ba909e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
