<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>2e1fc0d7-98a3-431f-8436-feee7efbcc71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>[H015] - verify user see about seva text - footer</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@datatest-id = 'logo-iso']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;CBQA ISO 27001&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>484fded2-691b-4a6e-b041-66466246a359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>CBQA ISO 27001</value>
      <webElementGuid>8a3841bc-f981-4347-869f-ab69e3da15a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatest-id</name>
      <type>Main</type>
      <value>logo-iso</value>
      <webElementGuid>c485eb90-1a5f-4c92-8842-b4486c15fa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Ficon%2Fiso.webp&amp;w=32&amp;q=75 1x, /_next/image?url=%2Frevamp%2Ficon%2Fiso.webp&amp;w=64&amp;q=75 2x</value>
      <webElementGuid>5f446046-beb3-4366-943e-ed8d670d55d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Ficon%2Fiso.webp&amp;w=64&amp;q=75</value>
      <webElementGuid>e342d71e-e571-4b18-bd9d-1a1248dc7737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>ae2f3d61-8d7e-4d87-af8e-8d50e0f6d661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>00f74382-cac0-4a65-bf97-3917a107ceac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>547fae9d-8e7b-4153-b4a1-84ae14c01c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>60ebaf0e-29f0-43d3-8d38-2469cf2c85b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>0a4be82b-9992-4037-8ae7-1e58f5d92f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;index_main__K2Wvo&quot;]/div[@class=&quot;index_container__KNQ8V&quot;]/footer[@class=&quot;footerMobile_container__FOSPi&quot;]/div[@class=&quot;footerMobile_contentContainer__J40vG&quot;]/div[@class=&quot;footerMobile_isoWrapper__53r9r&quot;]/img[1]</value>
      <webElementGuid>7cb7df51-b3a1-42fa-83a7-f22dbfd891f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/footer/div/div[3]/img</value>
      <webElementGuid>667f5761-6f19-4fec-8aef-3789094df546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='CBQA ISO 27001']</value>
      <webElementGuid>b2d2a2e0-4413-455f-b28c-21f05b95e200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div[3]/img</value>
      <webElementGuid>30c42bef-b61c-4d34-a916-f9c57ca63761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'CBQA ISO 27001' and @src = '/_next/image?url=%2Frevamp%2Ficon%2Fiso.webp&amp;w=64&amp;q=75']</value>
      <webElementGuid>0501ab80-c43a-4860-92bc-91093a564fd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
