<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Masuk  Register_headerMobile_logoImg__u_x0L</name>
   <tag></tag>
   <elementGuidId>42f39bf8-0fe9-420b-bc18-e333639b8b83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.headerMobile_logoImg__u_x0L</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div/header/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e655859f-9e6e-4a04-a784-e4ae0947b155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo SEVA</value>
      <webElementGuid>1b8c5a3d-247e-4fe0-b352-ad1d2b31b240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>icon-logo-seva</value>
      <webElementGuid>ac35d2d2-2f19-4018-8172-ce029bc6a456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Ficon%2Flogo-primary.webp&amp;w=64&amp;q=75 1x, /_next/image?url=%2Frevamp%2Ficon%2Flogo-primary.webp&amp;w=128&amp;q=75 2x</value>
      <webElementGuid>73d22f78-9423-4b19-bce9-3d46712e8c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Ficon%2Flogo-primary.webp&amp;w=128&amp;q=75</value>
      <webElementGuid>8d4fa51b-b05c-4949-a2f7-72a65478b23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8be5c2b6-91ef-479f-bfdc-bb7a1d22d4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>c5b4993a-9321-400a-a79a-6714c6bbf27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>b33c66d0-00ef-469f-bfd0-3ec4597c2bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6ed48c76-1e28-4e41-9fe4-0566c170cf69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headerMobile_logoImg__u_x0L</value>
      <webElementGuid>828bfe3b-a809-4de9-9143-7a6f27413afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;index_main__K2Wvo&quot;]/div[@class=&quot;index_container__KNQ8V&quot;]/div[@class=&quot;mainHeroLp_supergraphic__jZ0ws&quot;]/div[@class=&quot;mainHeroLp_mainContent___SiZg&quot;]/header[@class=&quot;headerMobile_wrapper__5EaXn headerMobile_showHeader__V_7qB headerMobile_homepage__SBKsV&quot;]/div[@class=&quot;headerMobile_wrapperAnnouncementBox__TYH_L&quot;]/div[@class=&quot;headerMobile_container__hw5N3&quot;]/div[2]/img[@class=&quot;headerMobile_logoImg__u_x0L&quot;]</value>
      <webElementGuid>9d4ae24f-0416-49fa-8923-3acd2a1a546e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div/header/div/div/div[2]/img</value>
      <webElementGuid>1be5e150-0bef-48a1-a10e-955b920c44b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo SEVA']</value>
      <webElementGuid>2fb51033-b0c5-41df-9a73-9bf7a9acc594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>c777c785-479c-40e5-819c-2e61da1ca8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Logo SEVA' and @src = '/_next/image?url=%2Frevamp%2Ficon%2Flogo-primary.webp&amp;w=128&amp;q=75']</value>
      <webElementGuid>600e4b63-231e-4ed8-a5c4-5cf69f531aba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
