<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ajukan Instant Approval</name>
   <tag></tag>
   <elementGuidId>6c5b8ec2-c950-4134-8998-6b928d0276c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div[8]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button_primaryDarkBlue__SJzXm.button_big__H6cBN.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8fcc23b-6c14-4982-9906-d82e25ac1a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_primaryDarkBlue__SJzXm button_big__H6cBN undefined</value>
      <webElementGuid>efd89feb-8b5a-46d0-8aea-8ec14e0a8044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajukan Instant Approval</value>
      <webElementGuid>425d51c4-50c0-477d-a94b-b39dd06bf389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;instant-approval-review_container__yyCk2&quot;]/div[@class=&quot;instant-approval-review_paddingButton__A5hYP&quot;]/button[@class=&quot;button_primaryDarkBlue__SJzXm button_big__H6cBN undefined&quot;]</value>
      <webElementGuid>cb93f3d0-720b-4b0a-b47d-1c9182761edd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div[8]/button</value>
      <webElementGuid>250cdcf0-d6db-4b4d-ba3c-38b2c6e51251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp115.550.000'])[1]/following::button[1]</value>
      <webElementGuid>b00dc37d-3b5c-4a1a-a323-13de2644fca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ajukan Instant Approval']/parent::*</value>
      <webElementGuid>08a54cd0-50f5-4270-a107-0f9d836979a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>e9c73e8b-4781-4dcb-b0e5-465104a8e4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Ajukan Instant Approval' or . = 'Ajukan Instant Approval')]</value>
      <webElementGuid>323f42e8-4c35-4db8-a996-e8487bebccfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
