<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect</name>
   <tag></tag>
   <elementGuidId>ab21e103-c7f5-43c9-8b02-33febe38d833</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg > rect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>1516e9cc-9fab-49c8-9956-d1cec3ef9164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0.5</value>
      <webElementGuid>2bcee7ce-eaf9-4826-91fc-df20345450de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0.5</value>
      <webElementGuid>83ba4889-ab94-4f55-9fb7-23b4bd1c1fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>eb3f9f84-7247-4988-acb5-92e2512eb45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>f689968f-8fdd-40b6-a4fb-95f8155efc54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>3.5</value>
      <webElementGuid>a42ed97c-4a8d-45a0-b339-4abe9317ca5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>3ae3237d-2e4f-46b5-9a32-3d397c07a16d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;ktp-review_container__gmh70&quot;]/div[@class=&quot;ktp-review_content__cArWc&quot;]/div[@class=&quot;ktp-review_ktpContent__uTZys&quot;]/div[@class=&quot;ktp-review_ktpSection__9NJ12&quot;]/div[@class=&quot;ktp-review_ktpDataWrapper__UtZqt&quot;]/div[@class=&quot;ktp-review_ktpDataRow__GJC6E&quot;]/div[@class=&quot;ktp-review_checkboxOptionWrapper__mhFEa&quot;]/button[@class=&quot;ktp-review_iconWrapper__LSBWY&quot;]/svg[1]/rect[1]</value>
      <webElementGuid>0bfdbac7-d746-4953-82af-8f3fe399975a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
