<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Ingin Cari Mobil Sesuai Budgetmu</name>
   <tag></tag>
   <elementGuidId>0f2ea24f-4fa1-4cd8-83a3-7652c65a2a29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.multi-kk_title__YEMo_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c2ab4d52-a5b1-4453-a238-23931c52b5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multi-kk_title__YEMo_</value>
      <webElementGuid>b6f7cdb1-c58b-401f-9639-41cdb6492c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingin Cari Mobil Sesuai Budgetmu?</value>
      <webElementGuid>5faae523-2ddf-48e3-90a8-2a693cc0442a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;pageLayout_container__Y72th&quot;]/div[@class=&quot;mobilleView_container__1XoMa multi-kk_container__XDN6h&quot;]/div[@class=&quot;multi-kk_titleWrapper__vwzRn&quot;]/h1[@class=&quot;multi-kk_title__YEMo_&quot;]</value>
      <webElementGuid>552b1c7e-cf50-4e38-834c-43a7b9732dbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/h1</value>
      <webElementGuid>a1cc2ef4-75b7-47a1-b4db-3288fe31ece1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>d10ea1cd-375b-4433-961e-3b436d65d99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Ingin Cari Mobil Sesuai Budgetmu?' or . = 'Ingin Cari Mobil Sesuai Budgetmu?')]</value>
      <webElementGuid>7045d03e-e2fa-4067-aa0c-b08719e4434b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
