<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rekomendasi Cicilan Ideal_0 input_inp_acd316</name>
   <tag></tag>
   <elementGuidId>bdfe4a41-aad1-4455-9ca2-e6db5fbeeb29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.0.input_input__MAvlc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Masukkan pendapatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;field-input-pendapatan&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6316e363-81d5-4163-b0df-988a92192c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>field-input-pendapatan</value>
      <webElementGuid>24d1fba3-aee5-46da-8368-1286bf28bf98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>0 input_input__MAvlc</value>
      <webElementGuid>a5757e04-4a89-405e-972c-fcf53805dacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan pendapatan</value>
      <webElementGuid>66731c08-454a-45e8-b49a-507d1bda2f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>6efe4cc4-b13c-45b2-b069-b1ea2a41b68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>46c32934-ec0d-4dd5-8709-dd945e37d3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rp2</value>
      <webElementGuid>e714c754-7566-4e24-b7e0-4600c6de2754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loan-calculator-form-income&quot;)/div[1]/div[1]/input[@class=&quot;0 input_input__MAvlc&quot;]</value>
      <webElementGuid>133e3e10-9460-4b95-ad07-b8681df0506f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Rp2']</value>
      <webElementGuid>0cd2c2ae-f092-4061-abd6-8ba4cc19e628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loan-calculator-form-income']/div/div/input</value>
      <webElementGuid>0a73d170-663b-40ec-a95d-2abb416cdaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/input</value>
      <webElementGuid>790dcce1-d6c9-4947-bbd8-d5d8ccfe58cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan pendapatan' and @type = 'tel']</value>
      <webElementGuid>8a6d6bc9-55eb-4ab7-8a35-a0c641c11085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
