<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_input_input__MAvlc input_error__te3cX_9f26de</name>
   <tag></tag>
   <elementGuidId>dbfcbad3-759d-41bd-b3e4-b9b74a960525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.input_input__MAvlc.input_error__te3cX.shake-animation-X</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Rp1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>691f64cd-bf94-4c28-9b78-e8e7d9637cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_input__MAvlc input_error__te3cX shake-animation-X</value>
      <webElementGuid>d809053b-b550-4de8-9003-2e96d174d85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan harga</value>
      <webElementGuid>b98fd04e-ae8a-4a96-b660-2f73153e830b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>cd695c23-cbcb-4230-bf5f-edf684fe5f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>fa3eabf1-85c3-4e72-8d0a-fd767a3ae1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rp1</value>
      <webElementGuid>c9ddbc3b-ef22-4066-bba2-cc8e5f6dcf54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;pageLayout_container__Y72th&quot;]/div[@class=&quot;mobilleView_container__1XoMa multi-kk_container__XDN6h&quot;]/div[2]/div[@class=&quot;multi-kk_formRange__ioBGw&quot;]/div[1]/div[1]/input[@class=&quot;input_input__MAvlc input_error__te3cX shake-animation-X&quot;]</value>
      <webElementGuid>8f50b88a-5907-4e3e-9ada-9ad0f1c2a8e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Rp1']</value>
      <webElementGuid>b806c0cb-0738-4d4d-a6d3-178f3985b9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>b90e9777-8bf8-4826-8938-444fed72a36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>bfc680f2-70c2-4773-af40-c0e9bc06e6e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan harga' and @type = 'tel']</value>
      <webElementGuid>9d8607b3-3767-4fd6-a803-c12dcdc630ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
