<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_icon_location</name>
   <tag></tag>
   <elementGuidId>f2613f30-729b-45ac-923a-6c68f4cbfa70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.inputSelect_iconWrapper__hApg7 > div > svg > circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>19343969-5cf2-4eb8-b808-d37e280991fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e663cc7b-bf28-449c-9095-a8968bf1434c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>9e85b019-0007-4d68-bae0-8012d65502cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>c3ab1fc1-7cec-459c-a827-4a8e9dfda861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#13131B</value>
      <webElementGuid>0454057a-472f-4302-8628-bd10a0a835cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[4]/div[@class=&quot;ant-modal-root css-1fumvat&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal css-1fumvat city-selector-custom-modal&quot;]/div[2]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;citySelectorModal_inputSelectWrapper__N9vcM&quot;]/div[@class=&quot;inputSelect_container__q11Yp undefined&quot;]/div[@class=&quot;inputSelect_inputArea__QvNq3 inputSelect_focus__8etKd&quot;]/div[@class=&quot;inputSelect_iconWrapper__hApg7&quot;]/div[1]/svg[1]/circle[1]</value>
      <webElementGuid>b4b135a1-76d6-4e79-bd4c-4919daa8da8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputSelect_iconWrapper__hApg7</value>
      <webElementGuid>dab611bd-616c-438f-8490-238ab432b3fa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
