<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>facebook_icon</name>
   <tag></tag>
   <elementGuidId>3eda87e3-7ffd-48d5-88d8-8e934ba16423</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;SEVA Facebook Icon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/footer/div/div[2]/a[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fa47c0c4-fafc-49e1-84a4-e733bc15bf94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>SEVA Facebook Icon</value>
      <webElementGuid>9969e224-1d28-4ced-9e9d-45b47cc5898b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>e6831887-ad49-40ff-97d2-8ea86a4b23fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>17.6</value>
      <webElementGuid>496afd12-3f10-4028-828f-18760055fd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>17.6</value>
      <webElementGuid>e61b1224-e35d-4d23-a429-28ce26a90f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>b5523834-d304-470a-be57-94741f27c7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e1be379e-a680-44af-9576-48475cd2755f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Ficon%2Ffacebook-outline.png&amp;w=32&amp;q=75 1x, /_next/image?url=%2Frevamp%2Ficon%2Ffacebook-outline.png&amp;w=48&amp;q=75 2x</value>
      <webElementGuid>3e445798-af40-4860-a50e-6d072e2a7029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Ficon%2Ffacebook-outline.png&amp;w=48&amp;q=75</value>
      <webElementGuid>80224378-b4d5-41b2-9a84-abdfa4040730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;index_main__PUxPm&quot;]/div[@class=&quot;index_container__B0sfV&quot;]/footer[@class=&quot;footerMobile_container__EKgOP&quot;]/div[@class=&quot;footerMobile_contentContainer__jRnMy&quot;]/div[@class=&quot;footerMobile_socialWrapper__XcMvf&quot;]/a[3]/img[1]</value>
      <webElementGuid>d436662e-9262-4a71-bc4e-9946c0ade163</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/footer/div/div[2]/a[3]/img</value>
      <webElementGuid>cf680022-e7a8-4360-8e2b-85cc92b2cc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='SEVA Facebook Icon']</value>
      <webElementGuid>93ecd2ae-eed0-4a34-92c8-eb87b26ba4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[3]/img</value>
      <webElementGuid>9fb3332f-a3e3-4266-b2cf-78012659fd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'SEVA Facebook Icon' and @src = '/_next/image?url=%2Frevamp%2Ficon%2Ffacebook-outline.png&amp;w=48&amp;q=75']</value>
      <webElementGuid>1f8c04ab-06d8-4ee7-8c56-6204e4a93439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
