<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo SEVA</name>
   <tag></tag>
   <elementGuidId>a3ff6d8b-6a71-4e2d-b806-04794f413ee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@class='headerDesktop_logoImg__Hx2E7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.headerMobile_logoImg__UxdpA</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'headerDesktop_logoImg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4915028f-fbaf-447e-933d-ffe60cb98958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo SEVA</value>
      <webElementGuid>f6ec35df-a0f6-4947-b7bd-694c101245a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>icon-logo-seva</value>
      <webElementGuid>d9d50903-7f14-46e2-9681-cd034fdc2fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>3f854fba-a0b2-436d-86c2-be6eab9c0f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>032da8a5-f2a9-455b-8cc5-d107837a7092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>44e00bfc-6097-41ee-8762-e8b8b4e5b214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>5f37c851-2fc8-42bb-91a5-41cae20bc6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>df508b3d-d50d-4062-9b1a-1c9ccd909383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headerDesktop_logoImg</value>
      <webElementGuid>efc215e6-a53f-45e1-ab8c-f36c05190177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Ficon%2Flogo-primary.webp&amp;w=64&amp;q=75 1x, /_next/image?url=%2Frevamp%2Ficon%2Flogo-primary.webp&amp;w=128&amp;q=75 2x</value>
      <webElementGuid>c55d682b-9bcf-4c91-9674-3c365731d498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Ficon%2Flogo-primary.webp&amp;w=128&amp;q=75</value>
      <webElementGuid>f75e457a-c102-40e6-b504-9d01da36dda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;index_main__PUxPm&quot;]/div[@class=&quot;index_container__B0sfV&quot;]/div[@class=&quot;mainHeroLp_supergraphic__xRwMW&quot;]/div[@class=&quot;mainHeroLp_mainContent__C_NY_&quot;]/header[@class=&quot;headerMobile_wrapper__AF_ul headerMobile_showHeader__qWGqN headerMobile_homepage__remEL&quot;]/div[@class=&quot;headerMobile_wrapperAnnouncementBox__el90Q&quot;]/div[@class=&quot;headerMobile_container__2UZwI&quot;]/a[1]/div[1]/img[@class=&quot;headerMobile_logoImg__UxdpA&quot;]</value>
      <webElementGuid>71428dfa-b327-4966-bb3c-0eaab338e466</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div/header/div/div/a/div/img</value>
      <webElementGuid>99cea113-9084-4e28-b1db-450f06c6f996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo SEVA']</value>
      <webElementGuid>ec0a8e10-cbc9-4ca3-a5d1-f1c03f2c0686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d1c591d2-279a-4e7e-8868-800653fcaa77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Logo SEVA' and @src = '/_next/image?url=%2Frevamp%2Ficon%2Flogo-primary.webp&amp;w=128&amp;q=75']</value>
      <webElementGuid>394ceab6-da6d-48e3-9c10-57a305a8d672</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
