<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect</name>
   <tag></tag>
   <elementGuidId>4fb2c26c-310a-4e3c-862c-f7ac0a5cab19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>rect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='leadsFormSecondary-module__sglaiW__formDesktop']//div[@class='agreement-module__85S08W__agreementTerms agreement-module__85S08W__primary false false']//button//*[name()='svg']//*[name()='rect']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;__next&quot;)/main[@class=&quot;__variable_3ff865 __variable_f58f01 __variable_e3bced __variable_4784a5 __variable_029e55 __variable_aac15d __variable_5e7d95 __variable_85049c __variable_971c20&quot;]/div[1]/div[@class=&quot;pageLayout-module__cJbOVq__containerResponsive&quot;]/div[@class=&quot;carVariantList-module__8U7bbG__contentDesktop&quot;]/div[2]/div[@id=&quot;pdp-lower-content&quot;]/div[@class=&quot;summary-module__XrqSca__wrapperDesktop&quot;]/div[@class=&quot;summary-module__XrqSca__containerDesktop&quot;]/div[@id=&quot;leads-form-secondary&quot;]/div[@class=&quot;leadsFormSecondary-module__sglaiW__wrapperDesktop&quot;]/div[1]/div[@class=&quot;leadsFormSecondary-module__sglaiW__foregroundDesktop&quot;]/div[@class=&quot;leadsFormSecondary-module__sglaiW__formDesktop&quot;]/div[@class=&quot;agreement-module__85S08W__agreementPromoTerms agreement-module__85S08W__primary&quot;]/button[1]/svg[1]/rect[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.agreement-module__85S08W__agreementPromoTerms > button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>a2fd7950-dd2e-4ae7-a652-2f3d52780ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0.5</value>
      <webElementGuid>de06c4cb-3a7c-4e4e-9a66-c988c645dbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0.773438</value>
      <webElementGuid>70c5cd6a-9bc7-47d2-b779-23c9eaf692cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>d3082e12-e7d4-437e-8257-c89beec5a406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>cedbbccf-e9f0-4490-b237-2f3e2429cbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>3.5</value>
      <webElementGuid>82bbfc9f-5809-419e-851a-ec304725b709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>f7f760f9-c09a-4f9b-9d6c-12d6a2be0cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__variable_3ff865 __variable_f58f01 __variable_e3bced __variable_4784a5 __variable_029e55 __variable_aac15d __variable_5e7d95 __variable_85049c __variable_971c20&quot;]/div[1]/div[@class=&quot;pageLayout-module__cJbOVq__containerResponsive&quot;]/div[@class=&quot;carVariantList-module__8U7bbG__contentDesktop&quot;]/div[2]/div[@id=&quot;pdp-lower-content&quot;]/div[@class=&quot;summary-module__XrqSca__wrapperDesktop&quot;]/div[@class=&quot;summary-module__XrqSca__containerDesktop&quot;]/div[@id=&quot;leads-form-secondary&quot;]/div[@class=&quot;leadsFormSecondary-module__sglaiW__wrapperDesktop&quot;]/div[1]/div[@class=&quot;leadsFormSecondary-module__sglaiW__foregroundDesktop&quot;]/div[@class=&quot;leadsFormSecondary-module__sglaiW__formDesktop&quot;]/div[@class=&quot;agreement-module__85S08W__agreementPromoTerms agreement-module__85S08W__primary&quot;]/button[1]/svg[1]/rect[1]</value>
      <webElementGuid>232efaf5-c349-468c-87f5-85cb4fb89793</webElementGuid>
   </webElementProperties>
</WebElementEntity>
