<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect Leads Teman SEVA</name>
   <tag></tag>
   <elementGuidId>a8417ed4-fc55-4bd4-adf5-ce492049cb7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.agreement-module__85S08W__agreementTermsDesktop.agreement-module__85S08W__primary.false.false > button > svg > rect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[name()='rect'])[12]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/div[2]/div[@class=&quot;ant-modal-root css-1fumvat&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal css-1fumvat full&quot;]/div[2]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;leadsFormPrimary-module__uU3D2a__wrapper&quot;]/div[@class=&quot;leadsFormPrimary-module__uU3D2a__foregroundDesktop&quot;]/div[@class=&quot;leadsFormPrimary-module__uU3D2a__formDesktop&quot;]/div[@class=&quot;agreement-module__85S08W__agreementTermsDesktop agreement-module__85S08W__primary false false&quot;]/button[1]/svg[1]/rect[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>3fcb33c2-9a67-4cfc-a62d-f555755d9ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0.5</value>
      <webElementGuid>47a04aad-33cf-4e42-a236-5ce4ca2b0feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0.773438</value>
      <webElementGuid>aaf1ecf2-18b5-4daf-b5de-7965e67539e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a533d793-7049-4dfd-a53a-d1f58992ad0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>bf2f4042-a5c5-4772-9d22-e4a77a0a2a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>3.5</value>
      <webElementGuid>253d5a62-7c5c-445f-a0ab-9f5149812387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>a1f38580-f731-4221-881d-6509682a663d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[@class=&quot;ant-modal-root css-1fumvat&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal css-1fumvat full&quot;]/div[2]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;leadsFormPrimary-module__uU3D2a__wrapper&quot;]/div[@class=&quot;leadsFormPrimary-module__uU3D2a__foregroundDesktop&quot;]/div[@class=&quot;leadsFormPrimary-module__uU3D2a__formDesktop&quot;]/div[@class=&quot;agreement-module__85S08W__agreementTermsDesktop agreement-module__85S08W__primary false false&quot;]/button[1]/svg[1]/rect[1]</value>
      <webElementGuid>797e5bb6-5d85-491e-8f97-440126756f12</webElementGuid>
   </webElementProperties>
</WebElementEntity>
