import danaBpkb from "../../support/PageObject-SEVA/pageObject-WebsiteBayangan/danaBpkb";
import urlSeva from "../../support/PageObject-SEVA/Url/urlSeva"



describe('TC003_WebsiteBayangan_DanaBpkb', () => {
    beforeEach(() => {
        cy.clearSession();
        urlSeva.visitUrlDanaBpkb()
        cy.wait(5000)
    })

    // it('1. Leads Form - Top Widget & Navigation Menu', () => {
    //     cy.wait(5000)
    //     danaBpkb.clickBtnAjukanSekarangTopWidget()
    //     danaBpkb.inputNamaLengkapPopUpForm('Testing')
    //     danaBpkb.inputNomorHpPopUpForm('89676848410')
    //     danaBpkb.clickDropdownPilihKotaPopUpForm()
    //     danaBpkb.inputDropdownPilihKotaPopUpForm('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     cy.wait(2000)
    //     danaBpkb.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     danaBpkb.clickCheckBoxPopUpForm()
    //     danaBpkb.clickOpsiBPKBMobilPopUpForm()
    //     cy.wait(2000)
    //     danaBpkb.clickBtnKirimPopUpForm()
    //     cy.wait(15000)
    //     danaBpkb.verifySendLeadsPopUpForm()
    //     cy.wait(2000)

    //     cy.wait(5000)
    //     danaBpkb.clickBtnAjukanSekarangNavigationMenu()
    //     danaBpkb.inputNamaLengkapPopUpForm('Testing')
    //     danaBpkb.inputNomorHpPopUpForm('89676848410')
    //     danaBpkb.clickDropdownPilihKotaPopUpForm()
    //     danaBpkb.inputDropdownPilihKotaPopUpForm('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     cy.wait(2000)
    //     danaBpkb.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     danaBpkb.clickCheckBoxPopUpForm()
    //     danaBpkb.clickOpsiBPKBMobilPopUpForm()
    //     cy.wait(2000)
    //     danaBpkb.clickBtnKirimPopUpForm()
    //     cy.wait(15000)
    //     danaBpkb.verifySendLeadsPopUpForm()
    // })

    it('2. Leads Form - About US', () => {
        cy.wait(5000)
        danaBpkb.clickBtnSelengkapnyaAboutUs()
        danaBpkb.inputNamaLengkapPopUpForm('Testing')
        danaBpkb.inputNomorHpPopUpForm('89676848410')
        danaBpkb.clickDropdownPilihKotaPopUpForm()
        danaBpkb.inputDropdownPilihKotaPopUpForm('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        cy.wait(2000)
        danaBpkb.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
        danaBpkb.clickCheckBoxPopUpForm()
        danaBpkb.clickOpsiBPKBMobilPopUpForm()
        cy.wait(2000)
        danaBpkb.clickBtnKirimPopUpForm()
        cy.wait(15000)
        danaBpkb.verifySendLeadsPopUpForm()
    })

    // it('3. Leads Form - Goals', () => {
    //     cy.wait(5000)
    //     danaBpkb.clickBtnKonsultasiGoals()
    //     danaBpkb.inputNamaLengkapPopUpForm('Testing')
    //     danaBpkb.inputNomorHpPopUpForm('89676848410')
    //     danaBpkb.clickDropdownPilihKotaPopUpForm()
    //     danaBpkb.inputDropdownPilihKotaPopUpForm('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     cy.wait(2000)
    //     danaBpkb.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     danaBpkb.clickCheckBoxPopUpForm()
    //     danaBpkb.clickOpsiBPKBMobilPopUpForm()
    //     cy.wait(2000)
    //     danaBpkb.clickBtnKirimPopUpForm()
    //     cy.wait(15000)
    //     danaBpkb.verifySendLeadsPopUpForm()
    //     cy.wait(3000)

    //     cy.wait(5000)
    //     danaBpkb.clickBtnHubungiKamiGoals()
    //     danaBpkb.inputNamaLengkapPopUpForm('Testing')
    //     danaBpkb.inputNomorHpPopUpForm('89676848410')
    //     danaBpkb.clickDropdownPilihKotaPopUpForm()
    //     danaBpkb.inputDropdownPilihKotaPopUpForm('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     cy.wait(2000)
    //     danaBpkb.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     danaBpkb.clickCheckBoxPopUpForm()
    //     danaBpkb.clickOpsiBPKBMobilPopUpForm()
    //     cy.wait(2000)
    //     danaBpkb.clickBtnKirimPopUpForm()
    //     cy.wait(15000)
    //     danaBpkb.verifySendLeadsPopUpForm()
    // })

    // it('4. Leads Form - Document', () => {
    //     cy.wait(5000)
    //     danaBpkb.clickBtnAjukanSekarangDocument()
    //     danaBpkb.inputNamaLengkapPopUpForm('Testing')
    //     danaBpkb.inputNomorHpPopUpForm('89676848410')
    //     danaBpkb.clickDropdownPilihKotaPopUpForm()
    //     danaBpkb.inputDropdownPilihKotaPopUpForm('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     cy.wait(2000)
    //     danaBpkb.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     danaBpkb.clickCheckBoxPopUpForm()
    //     danaBpkb.clickOpsiBPKBMobilPopUpForm()
    //     cy.wait(2000)
    //     danaBpkb.clickBtnKirimPopUpForm()
    //     cy.wait(15000)
    //     danaBpkb.verifySendLeadsPopUpForm()
    // })

    // it('5. Leads Form', () => {
    //     cy.wait(5000)
    //     danaBpkb.inputNamaLengkapLeadsForm('Testing')
    //     danaBpkb.inputNomorHpLeadsForm('89676848410')
    //     danaBpkb.clickDropdownPilihKotaLeadsForm()
    //     danaBpkb.inputDropdownPilihKotaLeadsForm('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     cy.wait(2000)
    //     danaBpkb.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     danaBpkb.clickCheckBoxLeadsForm()
    //     danaBpkb.clickOpsiBPKBMobilLeadsForm()
    //     cy.wait(2000)
    //     danaBpkb.clickBtnKirimLeadsForm()
    //     cy.wait(15000)
    //     danaBpkb.verifySendLeadsForm()
    // })

    // it('6. Leads Form - USP', () => {
    //     cy.wait(5000)
    //     danaBpkb.clickBtnAjukanSekarangUSP()
    //     danaBpkb.inputNamaLengkapPopUpForm('Testing')
    //     danaBpkb.inputNomorHpPopUpForm('89676848410')
    //     danaBpkb.clickDropdownPilihKotaPopUpForm()
    //     danaBpkb.inputDropdownPilihKotaPopUpForm('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     cy.wait(2000)
    //     danaBpkb.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     danaBpkb.clickCheckBoxPopUpForm()
    //     danaBpkb.clickOpsiBPKBMobilPopUpForm()
    //     cy.wait(2000)
    //     danaBpkb.clickBtnKirimPopUpForm()
    //     cy.wait(15000)
    //     danaBpkb.verifySendLeadsPopUpForm()
    //     cy.wait(3000)

    //     cy.wait(5000)
    //     danaBpkb.clickBtnHubungiKamiUSP()
    //     danaBpkb.inputNamaLengkapPopUpForm('Testing')
    //     danaBpkb.inputNomorHpPopUpForm('89676848410')
    //     danaBpkb.clickDropdownPilihKotaPopUpForm()
    //     danaBpkb.inputDropdownPilihKotaPopUpForm('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     cy.wait(2000)
    //     danaBpkb.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     danaBpkb.clickCheckBoxPopUpForm()
    //     danaBpkb.clickOpsiBPKBMobilPopUpForm()
    //     cy.wait(2000)
    //     danaBpkb.clickBtnKirimPopUpForm()
    //     cy.wait(15000)
    //     danaBpkb.verifySendLeadsPopUpForm()
    // })

    // it('7. Leads Form - FAQ', () => {
    //     cy.wait(5000)
    //     danaBpkb.clickBtnSelengkapnyaFAQ()
    //     danaBpkb.inputNamaLengkapPopUpForm('Testing')
    //     danaBpkb.inputNomorHpPopUpForm('89676848410')
    //     danaBpkb.clickDropdownPilihKotaPopUpForm()
    //     danaBpkb.inputDropdownPilihKotaPopUpForm('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     cy.wait(2000)
    //     danaBpkb.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     danaBpkb.clickCheckBoxPopUpForm()
    //     danaBpkb.clickOpsiBPKBMobilPopUpForm()
    //     cy.wait(2000)
    //     danaBpkb.clickBtnKirimPopUpForm()
    //     cy.wait(15000)
    //     danaBpkb.verifySendLeadsPopUpForm()
    // })

    // it('8. Leads Form - Credit Simulation', () => {
    //     cy.wait(5000)
    //     danaBpkb.clickBtnAjukanSekarangCreditSimulation()
    //     danaBpkb.inputNamaLengkapPopUpForm('Testing')
    //     danaBpkb.inputNomorHpPopUpForm('89676848410')
    //     danaBpkb.clickDropdownPilihKotaPopUpForm()
    //     danaBpkb.inputDropdownPilihKotaPopUpForm('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     cy.wait(2000)
    //     danaBpkb.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     danaBpkb.clickCheckBoxPopUpForm()
    //     danaBpkb.clickOpsiBPKBMobilPopUpForm()
    //     cy.wait(2000)
    //     danaBpkb.clickBtnKirimPopUpForm()
    //     cy.wait(15000)
    //     danaBpkb.verifySendLeadsPopUpForm()
    // })

    // it('9. Leads Form - Floating Icon', () => {
    //     cy.wait(5000)
    //     danaBpkb.clickBtnFloatingIcon()
    //     danaBpkb.inputNamaLengkapPopUpForm('Testing')
    //     danaBpkb.inputNomorHpPopUpForm('89676848410')
    //     danaBpkb.clickDropdownPilihKotaPopUpForm()
    //     danaBpkb.inputDropdownPilihKotaPopUpForm('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     cy.wait(2000)
    //     danaBpkb.clickValuePilihKota('Administrasi Jakarta Pusat, Tanah Abang, Bendungan Hilir')
    //     danaBpkb.clickCheckBoxPopUpForm()
    //     danaBpkb.clickOpsiBPKBMobilPopUpForm()
    //     cy.wait(2000)
    //     danaBpkb.clickBtnKirimPopUpForm()
    //     cy.wait(15000)
    //     danaBpkb.verifySendLeadsPopUpForm()
    // })

})