<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Harga Terendah</name>
   <tag></tag>
   <elementGuidId>0e72019a-f42f-4f0c-bcf9-b332debf96eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.input_input__MAvlc.input_error__te3cX.shake-animation-X</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Rp1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7db93ba2-d4dc-4c9c-99a9-5aad86d58e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_input__MAvlc input_error__te3cX shake-animation-X</value>
      <webElementGuid>5a5061e0-c04f-4799-a2d0-cce5ea1f8aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan harga terendah</value>
      <webElementGuid>7bdb4211-d09d-493f-8032-fd2e8d9a8275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>78c57952-e785-4b78-9970-c108ea59c67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>4e23a6a2-adf0-41b8-a46c-938c9a8288d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rp1</value>
      <webElementGuid>72b73c38-97f0-479a-8fac-800037baf622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;pageLayout_container__Y72th&quot;]/div[@class=&quot;mobilleView_container__1XoMa multi-kk_container__XDN6h&quot;]/div[2]/div[@class=&quot;multi-kk_formRange__ioBGw&quot;]/div[1]/div[@class=&quot;undefined undefined&quot;]/input[@class=&quot;input_input__MAvlc input_error__te3cX shake-animation-X&quot;]</value>
      <webElementGuid>c8e54583-5703-412e-98f2-5c02ed146ce6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Rp1']</value>
      <webElementGuid>f175d4e8-8a59-4504-a957-4edd76f79476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>328d58f6-fd24-4591-b7d8-d606af949c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>7a3026bc-d7f0-4cb6-a1e9-bce27a715857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan harga terendah' and @type = 'tel']</value>
      <webElementGuid>4d9ec6fd-951a-481b-acae-92b88bfd1349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
