<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-formatted-string_SEVA by ASTRA</name>
   <tag></tag>
   <elementGuidId>f6fce332-3e48-4811-8098-3200400f0ca0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[text()=('SEVA by ASTRA')])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>1502ef83-29ff-4163-8c39-698cca9967c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97c8a8d5-c838-4b4b-9bf2-b2e99c999d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope ytd-channel-name</value>
      <webElementGuid>9dcd25b2-783d-42a5-989f-804628df37d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEVA by ASTRA</value>
      <webElementGuid>71d1ffd4-fda8-42cf-b307-cdf929bb8e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inner-header-container&quot;)/div[@id=&quot;meta&quot;]/ytd-channel-name[@id=&quot;channel-name&quot;]/div[@id=&quot;container&quot;]/div[@id=&quot;text-container&quot;]/yt-formatted-string[@id=&quot;text&quot;]</value>
      <webElementGuid>9d8af2f5-6b8b-43f1-b1d6-8f2c4e86ce05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[@id='text']</value>
      <webElementGuid>e22641fb-45f6-467f-b488-6df9377c6fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='text-container']/yt-formatted-string</value>
      <webElementGuid>13d3d88d-6029-403c-9070-af558977f853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ytd-channel-name/div/div/yt-formatted-string</value>
      <webElementGuid>291f1533-d6a6-437d-acf3-e11f51bf8b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[@id = 'text' and (text() = 'SEVA by ASTRA' or . = 'SEVA by ASTRA')]</value>
      <webElementGuid>fd0b594f-8b57-4bf5-9cfa-d00f678ad091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
