<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-formatted-string_SevabyAstra</name>
   <tag></tag>
   <elementGuidId>062e7678-5c2a-4f17-b3fb-35d79dd420f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.meta-item.style-scope.ytd-c4-tabbed-header-renderer > #channel-handle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//yt-formatted-string[@id='channel-handle'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>a0d04feb-832a-4320-b824-81045f2ec568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>channel-handle</value>
      <webElementGuid>1ba2297a-7a67-4014-bda0-5440ce10a7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope ytd-c4-tabbed-header-renderer</value>
      <webElementGuid>f6b3bde8-be95-454f-8396-4b41c1fed202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>1ba58d44-ef1c-494e-9246-fb12a55551e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>@SevabyAstra</value>
      <webElementGuid>b66ac7e9-2fd9-467f-a869-e3e0967ba97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inner-header-container&quot;)/div[@id=&quot;meta&quot;]/span[@class=&quot;meta-item style-scope ytd-c4-tabbed-header-renderer&quot;]/yt-formatted-string[@id=&quot;channel-handle&quot;]</value>
      <webElementGuid>3f94ca4b-2ed2-44a7-af72-15eb3d7554e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//yt-formatted-string[@id='channel-handle'])[2]</value>
      <webElementGuid>680b70f2-3093-4422-9259-85bca9a0bf29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='meta']/span/yt-formatted-string</value>
      <webElementGuid>6fd9db18-b10b-420d-b286-8e493cd032f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/yt-formatted-string</value>
      <webElementGuid>60d6b684-2e42-4f40-8b1d-08b9ce34eadd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[@id = 'channel-handle' and (text() = '@SevabyAstra' or . = '@SevabyAstra')]</value>
      <webElementGuid>8a44c1fa-1444-4c07-9bfa-dff215b40e80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
