<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cta_Logout</name>
   <tag></tag>
   <elementGuidId>0943da7a-b95a-4457-968d-089afc17112d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r2:']/div[5]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ecbaddd-efb4-4465-8e74-76d604a576dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>59931a86-2d5d-40ad-b39d-8c4de06030d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r2:&quot;)/div[@class=&quot;relative flex cursor-pointer items-center justify-between rounded p-2 text-body-small text-text-primary outline-none transition-colors data-[highlighted]:bg-surface-neutral data-[disabled]:pointer-events-none data-[disabled]:opacity-50 [&amp;_svg]:mr-2 [&amp;_svg]:size-4 [&amp;_svg]:text-icon-neutral&quot;]/div[1]</value>
      <webElementGuid>deb364cf-37c2-44d8-af5c-0d89a65c5dd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2:']/div[5]/div</value>
      <webElementGuid>71a7b0b6-ef49-4331-a1a8-db2b8de246da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/following::div[3]</value>
      <webElementGuid>d666fe00-162c-4ee3-b582-9df0e3d0067b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::div[5]</value>
      <webElementGuid>bd42902a-a9d8-4c8c-90ad-f50197983a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>ace12a97-2b61-4aca-b876-95875f92b4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[5]/div</value>
      <webElementGuid>11ed445d-7461-4569-af39-5ae4e52e738a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>8a6f5883-c92b-4613-b341-b27969195214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
