<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hubungi Kami</name>
   <tag></tag>
   <elementGuidId>98b0f5c1-8841-4c35-941a-fe2f243f5bf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-testid='footer-hubungi-kami']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>be777af5-3ff4-4074-834c-bca5ef9a4b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://wa.me/6289690008888?text=Halo%2C%20saya%20ingin%20tahu%20informasi%20lebih%20lanjut%20tentang%20layanan%20yang%20tersedia%20di%20SEVA.</value>
      <webElementGuid>457212ea-1892-4928-a606-ec50182045a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer noopener</value>
      <webElementGuid>7f60caf4-3850-481c-9e46-4446235cc88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>9205aeed-d045-4640-bb6f-9b5f0f2b2419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>footer-hubungi-kami</value>
      <webElementGuid>5dd86b76-3406-4ac6-9b06-a83a9e8e9a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hubungi Kami</value>
      <webElementGuid>38630292-6341-4a0b-ba77-8f0ccf589538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;index_main__K2Wvo&quot;]/div[@class=&quot;index_container__KNQ8V&quot;]/footer[@class=&quot;footerMobile_container__FOSPi&quot;]/div[@class=&quot;footerMobile_contentContainer__J40vG&quot;]/div[@class=&quot;footerMobile_linkedTextWrapper__S_qgQ&quot;]/a[4]</value>
      <webElementGuid>eff18d3c-6d12-493f-a1e1-c2df2be5a65e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/footer/div/div/a[4]</value>
      <webElementGuid>8e9807c9-db1c-465b-a07c-680b84909f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hubungi Kami')]</value>
      <webElementGuid>737c4d2b-e296-4100-82f5-3a96b4e07dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://wa.me/6289690008888?text=Halo%2C%20saya%20ingin%20tahu%20informasi%20lebih%20lanjut%20tentang%20layanan%20yang%20tersedia%20di%20SEVA.')]</value>
      <webElementGuid>8f1ffad8-9ca9-4110-b8cb-f5b8e4c633a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>37e9b53d-eb29-4381-b3b6-5f6968d501cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://wa.me/6289690008888?text=Halo%2C%20saya%20ingin%20tahu%20informasi%20lebih%20lanjut%20tentang%20layanan%20yang%20tersedia%20di%20SEVA.' and (text() = 'Hubungi Kami' or . = 'Hubungi Kami')]</value>
      <webElementGuid>a8be1f3e-1042-4890-a8f7-5fddd67fb6d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
