<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_x (2)</name>
   <tag></tag>
   <elementGuidId>c15a31d8-d8cf-4619-8c36-354b16cf76f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='close-icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#close-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5d249f1-c889-4dc8-a228-aeb4387c74dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>CLOSE</value>
      <webElementGuid>07a98fa7-df94-407f-be1d-ecc5b24463c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>404ff996-d313-4c6c-bb47-7086802b39a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close close-icon moe-inapp-close moe-element</value>
      <webElementGuid>3780d9dd-be94-42dc-9a22-e0e687a1e8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>de3ae88c-9323-445c-940c-080ee9d679d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-icon</value>
      <webElementGuid>b32059da-4f4f-4b8b-88f8-dab7453ca3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> x </value>
      <webElementGuid>493ba494-625b-49ae-a3ef-c20c421b48e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-icon&quot;)</value>
      <webElementGuid>e251bdbe-bdfe-404e-b8af-2041af90631e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SEVA - Beli Mobil Baru Dengan Cicilan _bf97c5/iframe_Masuk  Register_moe-onsite-campaign-_b516d4</value>
      <webElementGuid>8bd8abe4-b810-43e4-adee-a475134178b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='close-icon']</value>
      <webElementGuid>57353085-b6b3-4359-94a5-2bf0b718d5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='x']/parent::*</value>
      <webElementGuid>acd31790-c42d-4444-9d05-92c133d82b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7c5f454a-0fb9-4117-8e8f-e9c199453259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'close-icon' and (text() = ' x ' or . = ' x ')]</value>
      <webElementGuid>714070b0-4d89-45ba-b3af-7bb577fcd1a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
