<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_x (6)</name>
   <tag></tag>
   <elementGuidId>458553ac-4429-429d-8001-c56e8ee3d42a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='close-icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#close-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49a5e687-5282-4401-8280-cdc17bb22e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>CLOSE</value>
      <webElementGuid>7f59e2b0-7587-4300-9c37-8265265ad583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0a088a8-b422-449b-b16b-8256673e3cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close close-icon moe-inapp-close moe-element</value>
      <webElementGuid>b658fc76-d5f1-44ca-bd41-6040d9927ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>f4ecaac9-82a3-4a72-a01c-c38d562dc091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-icon</value>
      <webElementGuid>908cf66b-454c-4cc2-bab8-330edc1bc71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> x </value>
      <webElementGuid>564937dc-7a5e-41c5-b53e-1492db9c07cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-icon&quot;)</value>
      <webElementGuid>dd3b49f8-4dfb-47eb-9b84-0c7ce680916d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SEVA - Beli Mobil Baru Dengan Cicilan _bf97c5/iframe_SEVA punya banyak promo  info menari_5f1c1d (3)</value>
      <webElementGuid>78f89778-a603-4851-9859-246f13e5032c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='close-icon']</value>
      <webElementGuid>0108b16e-fc6b-4036-822e-9ba894654162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'close-icon', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>8c4d4021-c248-4957-967f-b0a8a88a7efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='x']/parent::*</value>
      <webElementGuid>1b56341e-b58b-4f43-939c-5d4dbbaba49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2cf4c086-a29c-4fc6-bcc6-a4c4955ae198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'close-icon' and (text() = ' x ' or . = ' x ')]</value>
      <webElementGuid>12a20e41-bd08-4fd5-af98-bb49c426bd57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
