<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (2)</name>
   <tag></tag>
   <elementGuidId>27bc3994-b1b8-4c1e-8493-887c6cb8d31b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;CBQA ISO 27001&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@datatest-id='logo-iso']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c2487fb1-535f-4a78-a8e0-6d8ccbbc452a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>CBQA ISO 27001</value>
      <webElementGuid>079c8700-50e7-44f9-a01e-c15788000630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatest-id</name>
      <type>Main</type>
      <value>logo-iso</value>
      <webElementGuid>574d319e-b0bc-4bbc-802a-b9d77f8a556f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Ficon%2Fiso.webp&amp;w=32&amp;q=75 1x, /_next/image?url=%2Frevamp%2Ficon%2Fiso.webp&amp;w=64&amp;q=75 2x</value>
      <webElementGuid>c8ebd208-626a-448c-b91e-8dfced5e9fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Ficon%2Fiso.webp&amp;w=64&amp;q=75</value>
      <webElementGuid>89758ae8-34c0-4823-a386-57960604dda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>89fc8c74-9875-4b66-a8ab-1796d2ffce44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>6a988957-f471-4527-9656-d60b8af98eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>3a423d25-c0a5-4240-aa48-4d2226b1f32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4c25274c-aae4-4901-8b4e-280d22a76b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>ac434993-a075-43a4-8a6e-6903f5479e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;index_main__K2Wvo&quot;]/div[@class=&quot;index_container__KNQ8V&quot;]/footer[@class=&quot;footerMobile_container__FOSPi&quot;]/div[@class=&quot;footerMobile_contentContainer__J40vG&quot;]/div[@class=&quot;footerMobile_isoWrapper__53r9r&quot;]/img[1]</value>
      <webElementGuid>9be5464a-ecd1-47d4-82ea-cfbd9f37a22a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/footer/div/div[3]/img</value>
      <webElementGuid>a69014cc-42e1-4421-96ee-75a4ac77d9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='CBQA ISO 27001']</value>
      <webElementGuid>90b5cd3e-7a42-436e-aca1-443b54a0b900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div[3]/img</value>
      <webElementGuid>3d762e33-f6c1-4b81-9e39-ffd4e26fb201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'CBQA ISO 27001' and @src = '/_next/image?url=%2Frevamp%2Ficon%2Fiso.webp&amp;w=64&amp;q=75']</value>
      <webElementGuid>83a5160f-6b5b-4453-8221-70efd55f009a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
