<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cari Mobil Baru_searchComponent_styledC_9fb0ca</name>
   <tag></tag>
   <elementGuidId>edfe8de1-e3ff-4fd7-ab5f-1568cbb7223a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;swiper-wrapper-834cc268c70594e5&quot;)/div[@class=&quot;swiper-slide swiper-slide-active searchComponent_containerNewCar__y18uN&quot;]/a[1]/div[@class=&quot;searchComponent_linkCar__65Sot&quot;]/img[@class=&quot;searchComponent_styledCarImage__tSI6i&quot;][count(. | //*[@alt = 'Toyota All New Avanza']) = count(//*[@alt = 'Toyota All New Avanza'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.searchComponent_styledCarImage__tSI6i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swiper-wrapper-834cc268c70594e5']/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>da512eab-7265-49ee-a8ca-c158b261df0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Toyota All New Avanza</value>
      <webElementGuid>c4b8cc96-4b7f-46c8-8776-24f78f6476f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>65f21d45-ce08-4603-b7e0-993e8fe0c9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>e68be0d9-0db0-4d12-901c-41a7ca377294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>223b6f96-ebf0-44c4-98b3-7af35e53d7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>c21b3901-68b9-4457-b316-a5303177233f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f087904f-2bee-4874-af44-b0b3dd241da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchComponent_styledCarImage__tSI6i</value>
      <webElementGuid>3080ab8e-519f-4fd9-a15c-c2d18dd478dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fimages.prod.seva.id%2FToyota%2FAll%20New%20Avanza%2Fmain_color%2Fhitam.png&amp;w=64&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fimages.prod.seva.id%2FToyota%2FAll%20New%20Avanza%2Fmain_color%2Fhitam.png&amp;w=128&amp;q=75 2x</value>
      <webElementGuid>97b147db-54ca-470c-aa59-138c6e755538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fimages.prod.seva.id%2FToyota%2FAll%20New%20Avanza%2Fmain_color%2Fhitam.png&amp;w=128&amp;q=75</value>
      <webElementGuid>36ec050e-3e89-48f8-ac4f-c628d1d4337f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swiper-wrapper-834cc268c70594e5&quot;)/div[@class=&quot;swiper-slide swiper-slide-active searchComponent_containerNewCar__y18uN&quot;]/a[1]/div[@class=&quot;searchComponent_linkCar__65Sot&quot;]/img[@class=&quot;searchComponent_styledCarImage__tSI6i&quot;]</value>
      <webElementGuid>13b2b4ad-e2ff-4ff6-9779-41349406fb79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-834cc268c70594e5']/div/a/div/img</value>
      <webElementGuid>4854f75b-66fa-4479-b16a-e079749ddf3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Toyota All New Avanza']</value>
      <webElementGuid>107693b5-cfce-4a3f-9f9c-d224837be7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/div/img</value>
      <webElementGuid>1ecc8c03-1ac6-4cae-b70a-81429175e43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Toyota All New Avanza' and @src = '/_next/image?url=https%3A%2F%2Fimages.prod.seva.id%2FToyota%2FAll%20New%20Avanza%2Fmain_color%2Fhitam.png&amp;w=128&amp;q=75']</value>
      <webElementGuid>d1aa06b8-8ecd-49c2-9c68-9eeadd6968f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
