<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Butuh Bantuan_inputPhone_input__r86Wm false</name>
   <tag></tag>
   <elementGuidId>9d8b4926-3a64-4381-bf26-88fbb0af6d7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.inputPhone_input__r86Wm.false</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;nomor-telp-pdp-leads&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1899aca-ff2e-42fd-a6f5-6d9e5cd1b13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>42e6f30e-0c61-4cbb-b70b-a23d02d2d0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>nomor-telp-pdp-leads</value>
      <webElementGuid>4e77be26-e637-4cc5-95fd-ddebd864ad19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>50176fcc-c3a6-4b46-b8cb-2daff5ab5c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputPhone_input__r86Wm false </value>
      <webElementGuid>b06d0b91-5014-4534-943b-06238f50c786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: 812345678</value>
      <webElementGuid>6e0db93a-82ae-4a48-ad11-bb4b6909b93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>field-input-nama-lengkap</value>
      <webElementGuid>6fbbb288-d994-4753-b2e1-c9a467a1f469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landing-page-leads-form-section&quot;)/div[@class=&quot;leadsFormTertiary_container__eBNAS&quot;]/div[@class=&quot;leadsFormTertiary_wrapper__nOdZt&quot;]/div[@class=&quot;leadsFormTertiary_foreground__2I_to&quot;]/div[@class=&quot;leadsFormTertiary_form__F4vzh&quot;]/div[@class=&quot;inputPhone_wrapper__FVS9_ leadsFormTertiary_inputPhone__atuD7&quot;]/div[@class=&quot;inputPhone_wrapperInput__RCpE6 inputPhone_default__BegXK undefined false&quot;]/input[@class=&quot;inputPhone_input__r86Wm false&quot;]</value>
      <webElementGuid>f44a994d-ce42-49de-8ad6-893dcc9cb213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[4]</value>
      <webElementGuid>23a0c673-fa19-4573-9aac-f7f67c5e0138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='landing-page-leads-form-section']/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>fa7060fe-9794-47bf-9196-e972f9bfb47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>59fe7cd6-459a-4a6c-8471-fed4bf56b87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = 'Contoh: 812345678']</value>
      <webElementGuid>ad82676d-4fd8-4486-a2ed-13fe08df7894</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
