#false.
#@USER username to access database.
#@PASSWORD encrypted password.
#Wed Feb 28 15:11:33 WIB 2024
PASSWORD=
SECURE_USER_ACCOUNT=false
CONNECTION_PROPERTIES={\n  "connectionProperty"\: [],\n  "props"\: {}\n}
USER=
DRIVERCLASSNAME=
SHOW_WARNING=false
URL=
