<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status Perkawinan_marriage</name>
   <tag></tag>
   <elementGuidId>164082e5-0063-41f5-afd6-5bbc8305b367</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='marriage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#marriage</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '${marriage}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a40a45f-1b2d-48d7-b203-9ad0101a103e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>470a5a11-a56e-4ba4-8352-f0958478490f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputSelect_inputField__Zpc6V</value>
      <webElementGuid>3e81f878-fb4d-444e-8a2e-077f46c1e8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Status Perkawinan</value>
      <webElementGuid>88d5c7f2-f786-436b-ab51-8a0f2347a0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>${marriage}</value>
      <webElementGuid>d9d7e4b4-ed7f-431a-9ca9-c6f5e7db39eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>marriage</value>
      <webElementGuid>221e30ce-b5d4-462a-8e9b-c4b8303ca88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>dropdown-status-perkawinan</value>
      <webElementGuid>99051c71-8c75-4143-a7b4-24dc8df4f823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marriage&quot;)</value>
      <webElementGuid>2a256488-f477-4be9-a348-6d41d2e4bbf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='marriage']</value>
      <webElementGuid>9459df91-67d7-4db6-adc8-529c8256617c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div[5]/div/div/div/input</value>
      <webElementGuid>8e21ec0f-16e2-4860-ba2f-d13c1b91629e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>011cc671-9e86-4323-9370-c35c2527d99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Pilih Status Perkawinan' and @id = 'marriage' and @name = 'marriage']</value>
      <webElementGuid>b400a439-f56c-4d66-9a29-4c698b01e316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
