<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg- UPLOAD KTP</name>
   <tag></tag>
   <elementGuidId>bd8264a1-0b9a-45ae-85cb-2b4b8b505682</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='button']//*[name()='svg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ktp-upload_btnUpload__Ak3Et > svg</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[starts-with(@class, 'ktp-upload_input')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>e6940212-eec3-4a58-bea2-e836763ddb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>3c78de82-cfe3-4097-96a7-a9546a818431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>8b6bfdc1-1e30-45d3-83ab-3965752eb480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 40 40</value>
      <webElementGuid>260e98f4-09b4-42ed-9699-160f895ef480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>6a5257ce-4b55-4b92-a985-aa4813e7467d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>56b3e071-7ef6-4f24-9e78-1194859a1e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;ktp-upload_wrapper__d_Th2&quot;]/div[@class=&quot;ktp-upload_footerWrapper__kCyAb&quot;]/div[@class=&quot;ktp-upload_bottomWrapper__rmrHv&quot;]/div[@class=&quot;ktp-upload_btnUpload__Ak3Et&quot;]/svg[1]</value>
      <webElementGuid>aca77d11-ccc7-45f0-95cb-0f83e1f6073d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>starts with</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ktp-upload_input</value>
      <webElementGuid>c8dcb0d4-ddc2-4327-9671-e9d06fa05dbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pastikan KTP tidak rusak dan data dapat terbaca'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>62be9d26-4632-4eb1-a3d6-2634f334203c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pastikan foto KTP terlihat jelas dan tidak kabur'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>1537a90c-c186-4e2e-bc16-d85c04c4d943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>fc895b5e-9538-457c-af65-ace9c5720139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>770c540a-0e2f-4e68-977e-480d27c8d63a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
