<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SEVA Dropdown Icon</name>
   <tag></tag>
   <elementGuidId>fdd12d82-ba80-48af-8bf8-c8250fe7c031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'dropdown-pilih-kota']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loan-calculator-form-city']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.inputSelect_inputArea__gzgj4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d75143a5-e2c2-4c4a-9250-9a268b69f7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputSelect_inputArea__gzgj4</value>
      <webElementGuid>a8b0c2b4-3dfe-442a-8079-2a556d4d07e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEVA Dropdown Icon</value>
      <webElementGuid>172e7536-b033-4624-92c0-9443c57193e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loan-calculator-form-city&quot;)/div[@class=&quot;inputSelect_container__sv8Xm undefined&quot;]/div[@class=&quot;inputSelect_inputArea__gzgj4&quot;]</value>
      <webElementGuid>47c82625-8440-4e82-9637-58cb5b342ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>dropdown-pilih-kota</value>
      <webElementGuid>200dc99a-916a-4075-88b9-096c8708c599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loan-calculator-form-city']/div[2]/div</value>
      <webElementGuid>032a5964-a7b4-40c2-9c59-2acef4c6cdef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya ingin beli mobil di kota'])[1]/following::div[5]</value>
      <webElementGuid>84c800a3-4c90-427e-bbea-b7b3c99b598c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Tahu Kemampuan Finansialmu'])[1]/following::div[8]</value>
      <webElementGuid>9903683f-ff75-4b8a-b59f-4aacf0a99acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jakarta Pusat'])[1]/preceding::div[3]</value>
      <webElementGuid>ec46de99-5b5a-45c3-8486-f8b401717b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model mobil pilihan saya'])[1]/preceding::div[8]</value>
      <webElementGuid>e635cd97-7caa-4993-b961-57257f5a411d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>53a60ffb-92b7-4508-9c30-bafbebaf2d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'SEVA Dropdown Icon' or . = 'SEVA Dropdown Icon')]</value>
      <webElementGuid>fd4b0b29-3f26-4f2e-884f-86f28a9598cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
