<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Jakarta Pusat_formSelectModelCar_carIma_c786f3</name>
   <tag></tag>
   <elementGuidId>021b40a7-8322-446b-9a35-90be729870c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loan-calculator-form-car-model']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.formSelectModelCar_carImage__qkkKB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>eeb91fc8-e33e-4917-a24c-71a792bb271d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Data Kredit Mobil </value>
      <webElementGuid>b00e4c45-d372-4ba0-95a9-9e2b3e0b6bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Fillustration%2Fcar-sillhouete.webp&amp;w=128&amp;q=75 1x, /_next/image?url=%2Frevamp%2Fillustration%2Fcar-sillhouete.webp&amp;w=256&amp;q=75 2x</value>
      <webElementGuid>cf31261e-a523-4b01-889f-6124f7a236eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Frevamp%2Fillustration%2Fcar-sillhouete.webp&amp;w=256&amp;q=75</value>
      <webElementGuid>4a70286c-1421-442c-b977-098ee6ba5fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>159ebc2a-445f-4051-b22b-54801d77cc4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>96a77a34-dbd8-449c-9f3d-f5af0245609a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>6225eef1-cafb-4a18-967c-3998dff85964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>16958d6c-e49d-45c9-9821-e3850811431d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formSelectModelCar_carImage__qkkKB</value>
      <webElementGuid>5414f83d-52fa-4991-a0e6-57e6b2a21d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>363ed06a-1b55-4d26-9323-56e0675d0b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loan-calculator-form-car-model&quot;)/div[@class=&quot;formSelectModelCar_imageWrapper__U63m1&quot;]/img[@class=&quot;formSelectModelCar_carImage__qkkKB&quot;]</value>
      <webElementGuid>5b9d35a6-cb01-4869-b88a-8f802de16fd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loan-calculator-form-car-model']/div/img</value>
      <webElementGuid>bdb0573b-83bc-4274-9184-3dbd2e47c057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Data Kredit Mobil ']</value>
      <webElementGuid>1b94a92b-c9fe-4d86-bd01-09af03c51a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/img</value>
      <webElementGuid>a79644ad-2c4d-4e8e-aa9e-2adb2b92437d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Data Kredit Mobil ' and @src = '/_next/image?url=%2Frevamp%2Fillustration%2Fcar-sillhouete.webp&amp;w=256&amp;q=75']</value>
      <webElementGuid>c46bb503-20bf-427a-96ca-4918f26c996b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
