<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CTA Text Announcement Box Management</name>
   <tag></tag>
   <elementGuidId>a7c4d18b-8e4b-45bd-9c9e-d5d9122c4f49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cta_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cta_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3deebf4b-90a9-4b69-ab98-fcc6681fc6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0 block h-full w-full border-none bg-transparent p-0 text-sm outline-none placeholder:text-shadesSecondaryGray dark:text-gray-100 placeholder:dark:text-gray-400</value>
      <webElementGuid>4e7d6487-f34e-4b90-94af-bbb3c87a1ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cta_text</value>
      <webElementGuid>c3761eb9-2d53-4f5d-8e17-b63c557199ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. Cek Promo</value>
      <webElementGuid>2ef287e8-5a91-42d5-bd06-0d42cdec779a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cta_text</value>
      <webElementGuid>4e1be0b5-3d3e-4d8b-bbf9-44727bf9ca2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16c2a438-373c-4112-ab81-04d6d9855c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cta_text&quot;)</value>
      <webElementGuid>5e6b841b-b060-4b10-85c5-78409d50d76c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cta_text']</value>
      <webElementGuid>4287d6b6-e297-4a86-bfdd-c540920a3fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/form/div[3]/div/div[5]/div/div/div[2]/input</value>
      <webElementGuid>b7438a2a-ddec-4e93-906f-fe3de35f8e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/input</value>
      <webElementGuid>19c390c0-6c07-497b-b0ec-90747adcf97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cta_text' and @placeholder = 'e.g. Cek Promo' and @id = 'cta_text' and @type = 'text']</value>
      <webElementGuid>8b9cd090-0c9b-42e4-887e-957009fe10c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
