<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Temansevatestsuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8efd4543-4cb7-43d4-88f8-2172b4c616b1</testSuiteGuid>
   <testCaseLink>
      <guid>8ae8a9b7-c86f-4814-bbcd-79407ddaa84c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Teman Seva/TS 001 Masuk akun teman seva</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e00f082d-6c3f-4089-b30a-32aa163c4587</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e89a7bf1-7b19-425d-a4c1-470feb69870e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4ce0763-0d3f-49bc-8781-99380123e924</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53fd9d4f-65eb-46d2-8529-7298f5e81939</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Teman Seva/TS 002 Lihat riwayat transaksi</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e00f082d-6c3f-4089-b30a-32aa163c4587</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e89a7bf1-7b19-425d-a4c1-470feb69870e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4ce0763-0d3f-49bc-8781-99380123e924</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49df9dc5-79b2-48b4-ae40-f2b106057f1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Teman Seva/TS 003 Lihat daftar teman seva</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e00f082d-6c3f-4089-b30a-32aa163c4587</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e89a7bf1-7b19-425d-a4c1-470feb69870e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4ce0763-0d3f-49bc-8781-99380123e924</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7001c2a3-1070-4e7a-8d27-1260a506b411</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Teman Seva/TS 004 Bagikan kode referal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e00f082d-6c3f-4089-b30a-32aa163c4587</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e89a7bf1-7b19-425d-a4c1-470feb69870e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4ce0763-0d3f-49bc-8781-99380123e924</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09ba2ba4-1a36-4126-8d6a-003966c17f08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Teman Seva/TS 005 Referal mobil baru teman seva</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e00f082d-6c3f-4089-b30a-32aa163c4587</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e89a7bf1-7b19-425d-a4c1-470feb69870e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4ce0763-0d3f-49bc-8781-99380123e924</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce452cc5-b43c-49d9-b5e4-b3fa4032273b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Teman Seva/TS 006 Referal fasilitas dana teman seva</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35acc39e-6905-42d9-8c55-95c5ba1eb8f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86bb13e1-b01e-49e1-840c-4a3b55990584</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>663090b5-7957-4787-9833-e6e48bf52d72</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
