<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Rekomendasi</name>
   <tag></tag>
   <elementGuidId>b8d9b705-54f7-4e18-ab87-ce13a768b9fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div[5]/h2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[starts-with(@class, 'lpCarRecommendations_title') and (text() = 'Rekomendasi' or . = 'Rekomendasi')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.lpCarRecommendations_title__MWC3Y</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>6f351668-ae72-43fa-9390-e28541594c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>starts with</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lpCarRecommendations_title</value>
      <webElementGuid>f91a6771-1e95-44e3-90bd-511943181b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rekomendasi</value>
      <webElementGuid>a3b0fd90-173e-4a01-ac83-1baab88182e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;index_main__K2Wvo&quot;]/div[@class=&quot;index_container__KNQ8V&quot;]/div[@class=&quot;testimonyWidget_container__8vQ9D&quot;]/h2[@class=&quot;lpCarRecommendations_title__MWC3Y&quot;]</value>
      <webElementGuid>fd5a66e8-6bf1-40ab-9f39-c9adeb8f8b77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[5]/h2</value>
      <webElementGuid>582cf756-93b0-44a3-8486-7eda53a4a3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat semua'])[1]/following::h2[1]</value>
      <webElementGuid>2e77ad65-208c-4cda-bbea-3972ba608075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo Eksklusif'])[1]/following::h2[1]</value>
      <webElementGuid>266d7fc9-4eca-4931-a4b9-589044cd0199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[1]/preceding::h2[1]</value>
      <webElementGuid>c1e3ab04-ec2c-4a9b-88a9-8e3c5ebfaa3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toyota'])[1]/preceding::h2[1]</value>
      <webElementGuid>5d967dc6-888e-4310-9cfc-e2c843086fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rekomendasi']/parent::*</value>
      <webElementGuid>5b1a6c62-5ce0-4334-b55e-64fc815ec527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/h2</value>
      <webElementGuid>f2e46a2c-0c8c-4ae2-9f2f-6656bc49327d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Rekomendasi' or . = 'Rekomendasi')]</value>
      <webElementGuid>ebee2f4b-2669-402a-924b-26407ed2c239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
