<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_city</name>
   <tag></tag>
   <elementGuidId>1899716a-db78-4e23-bfc5-ab3afaac1a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[3]/div/div/div/div[3]/div/div[2]/div[2]/div/div[2]/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'inputSelect_dropdownItemText__7p2jg inputSelect_greyLabelText__j_t1M' and (text() = '${city}' or . = '${city}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7ba64c6d-1909-4e9e-ba5d-d5705db45cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputSelect_dropdownItemText__7p2jg inputSelect_greyLabelText__j_t1M</value>
      <webElementGuid>a50994fc-a84c-4fd8-9a3b-568bdc5405e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${city}</value>
      <webElementGuid>35c29256-c650-4d74-b740-50b74b9b39c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;dealer_container__hkOVF&quot;]/div[@class=&quot;pageLayout_container__Y72th&quot;]/div[@class=&quot;dealer_searchContainer__HFsqI&quot;]/div[@class=&quot;dealer_cardContainer__NizkU cardshadow_alternativeCardShadow__Q_ufV&quot;]/div[@class=&quot;dealerSearchWidget_container__TYbqq&quot;]/div[@class=&quot;dealerSearchWidget_cardContainer__t4hpH&quot;]/div[@class=&quot;selectWidgetUsedCar_container__oFwOH&quot;]/div[@class=&quot;selectWidgetUsedCar_fieldContainer__w3IIw&quot;]/div[@class=&quot;selectWidgetUsedCar_fieldWrapper__1VXrk&quot;]/div[2]/div[@class=&quot;inputSelect_container__sv8Xm undefined&quot;]/div[@class=&quot;inputSelect_dropdown__2SfXo inputSelect_dropdownActive__cH79b&quot;]/div[@class=&quot;inputSelect_dropdownItem__BIFMK&quot;]/span[@class=&quot;inputSelect_dropdownItemText__7p2jg&quot;]</value>
      <webElementGuid>2b2b8bf1-fffa-47a0-91ef-64e475c612d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/div/div/div/div[3]/div/div[2]/div[2]/div/div[2]/div[2]/span</value>
      <webElementGuid>df581ae5-b28a-49a2-8556-c18bafc764bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bandar Lampung'])[1]/following::span[1]</value>
      <webElementGuid>e5fc1540-68c4-403c-9944-036cd38b3107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota'])[1]/following::span[2]</value>
      <webElementGuid>336be443-b4b5-4efc-a6bf-92edb5d97979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banjarmasin'])[1]/preceding::span[1]</value>
      <webElementGuid>cc278c2c-5ab4-44bb-86a9-0895199d3773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batam'])[1]/preceding::span[2]</value>
      <webElementGuid>48c3bce4-6bf9-4cdd-b073-4877fad87ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bandung']/parent::*</value>
      <webElementGuid>dd776c1f-9661-41a0-a345-3a629bde039f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span</value>
      <webElementGuid>21c8baf2-cf38-4e85-b01a-ca88dbb0e7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Bandung' or . = 'Bandung')]</value>
      <webElementGuid>b022fa6c-2e07-4ce9-ab2b-82edcfe2f113</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
