<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Follow Up HistoryNotesActivity Log</name>
   <tag></tag>
   <elementGuidId>7db747e1-dccc-4362-a252-7d7227d28464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.h-12.items-center.border-b.border-line.py-4.text-text-primary.mx-4.flex.w-auto.bg-surface-plain</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[3]/div/div/div/section/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7e9a7045-de93-4531-aa9f-92c5df97e2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tablist</value>
      <webElementGuid>105b3820-1b61-45ce-88e3-be13b7d6e511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>900801c3-b509-4043-96f3-544168d5b8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-12 items-center border-b border-line py-4 text-text-primary mx-4 flex w-auto bg-surface-plain</value>
      <webElementGuid>3bd96414-94a5-405d-94ed-815eb7fc3e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8d8f8fd3-c8f9-47f9-b013-8ed4ff9675fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>e9db42a0-b2cf-4b10-a609-7c3f2343e2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Follow Up HistoryNotesActivity Log</value>
      <webElementGuid>797e9844-7c06-4db2-b5f9-dae2e802f442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;ml-20 px-3 pb-3&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;overflow-x-clip py-4&quot;]/div[1]/div[@class=&quot;flex gap-4 text-body-small text-text-primary&quot;]/div[@class=&quot;flex flex-1 flex-col gap-4&quot;]/section[@class=&quot;overflow-hidden rounded-[10px] bg-surface-plain&quot;]/div[@class=&quot;overflow-clip&quot;]/div[@class=&quot;h-12 items-center border-b border-line py-4 text-text-primary mx-4 flex w-auto bg-surface-plain&quot;]</value>
      <webElementGuid>fd686855-fe05-4960-83c6-3240d3551533</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[3]/div/div/div/section/div/div</value>
      <webElementGuid>495dc15f-a081-40be-b466-da3562243af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supported File Formats'])[1]/following::div[2]</value>
      <webElementGuid>131c1c30-e17e-4ccb-9bd9-495b570a991c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload File'])[1]/following::div[4]</value>
      <webElementGuid>a2dd5534-29a7-407e-aa9a-fbb50dc2fd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/section/div/div</value>
      <webElementGuid>4abbdec1-378f-4f9e-a96e-042ca19fb14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Follow Up HistoryNotesActivity Log' or . = 'Follow Up HistoryNotesActivity Log')]</value>
      <webElementGuid>9eb659e8-9135-4bbc-978e-668cf550ea68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
