<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_edit</name>
   <tag></tag>
   <elementGuidId>e6611a2b-71e5-4f56-9979-d081651b56c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e60173ee-7dd1-4374-8697-1cd8e7a7fd71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-bottom inline-flex items-center justify-center leading-5 transition-colors duration-150 font-medium rounded-lg text-gray-600 border-gray-300 border dark:text-gray-400 focus:outline-none active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:ring-primary-300 focus:ring-opacity-40 focus:ring p-1</value>
      <webElementGuid>ba90ebe0-ee2d-40c2-bfd7-788d8f123de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ae98118-96e9-490e-aa1e-a3d1ce9b4a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;mx-auto grid w-full gap-4 px-6 lg:gap-0&quot;]/div[@class=&quot;overflow-hidden rounded-lg shadow-card border border-line relative w-full gap-x-3 overflow-x-auto scrollbar-thin scrollbar-track-gray-50 scrollbar-thumb-gray-200 scrollbar-corner-line dark:scrollbar-track-gray-700&quot;]/div[@class=&quot;w-full overflow-x-auto bg-white dark:bg-gray-800&quot;]/table[@class=&quot;w-full whitespace-nowrap text-sm&quot;]/tbody[@class=&quot;bg-white divide-y dark:divide-gray-700 dark:bg-gray-800 text-primaryDarkGray dark:text-gray-400&quot;]/tr[@class=&quot;group hover:bg-gray-50 dark:hover:bg-gray-600&quot;]/td[@class=&quot;px-4 py-3 z-1 sticky right-0 bg-white group-hover:bg-[#f9fafb] dark:bg-gray-800 dark:group-hover:bg-gray-600&quot;]/button[@class=&quot;min-w-[150px] truncate text-left&quot;]/div[@class=&quot;flex w-full justify-end&quot;]/div[@class=&quot;flex w-full items-center justify-end gap-x-2&quot;]/a[@class=&quot;flex w-full justify-end&quot;]/button[@class=&quot;align-bottom inline-flex items-center justify-center leading-5 transition-colors duration-150 font-medium rounded-lg text-gray-600 border-gray-300 border dark:text-gray-400 focus:outline-none active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:ring-primary-300 focus:ring-opacity-40 focus:ring p-1&quot;]</value>
      <webElementGuid>d461cb4f-de92-4aff-8f7c-ba83c3de7693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>1dc94029-21ff-426c-8f2f-a12bbac2cddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div[4]/div/table/tbody/tr/td[7]/button/div/div/a/button</value>
      <webElementGuid>d3bb2db7-684c-4d04-85c8-149a9e9444c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Superadmin'])[1]/following::button[2]</value>
      <webElementGuid>9ec6a4e1-3563-47c9-a09a-192d2d61b0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[3]</value>
      <webElementGuid>7b111536-4f71-4b0a-a0cd-bddb7fdebb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1-1 of 1'])[1]/preceding::button[2]</value>
      <webElementGuid>49d71518-a7d6-4d11-8291-5c1c1ea88059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/a/button</value>
      <webElementGuid>563663da-8893-46f7-b30f-ac54d85302e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>de195fee-7c00-4196-a7d7-43a25e270e74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
