<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-RecentlyView</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e45c96f3-4094-439c-86cc-3a6f8cb7ec08</testSuiteGuid>
   <testCaseLink>
      <guid>aff561ca-da97-4e43-b5d4-04a952d981ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recently View/RV001 - Verify User Can View Recently View Card Lihat on Homepage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66f3f4ac-64ea-40f2-a5ed-9b2bbf1ce40d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6e21b7b-6941-4dfd-9214-c033d7612632</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recently View/RV002 - Verify User Can Access PDP From Recently View Lihat From Homepage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f34594f-af97-4cc8-9d4d-bbe2893aeb92</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>595d3922-9a9e-4ab3-83b6-a02b5870675f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recently View/RV003 - Verify User Can View Recently View Card Simulasi Kredit on Homepage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc271aea-4931-4e6e-9a82-84582f4c6158</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9acdcd17-d683-4380-a239-fd5aaf0afb0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recently View/RV004 - Verify User Can Access Recently View Simulasi Kredit From Homepage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bacdffe3-2fa8-4caa-8680-5dfbf5f814bb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
