<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Full Comprehensive_Tenor2</name>
   <tag></tag>
   <elementGuidId>85e4d233-50c2-46ef-9ee4-fe7958968623</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-54-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-54-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c89cde80-3caf-4a8c-b380-f4a8a864feee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-react-select__option my-react-select__option--is-focused css-1w019hq-option</value>
      <webElementGuid>cb8124f3-0148-4f37-804d-ab6694338de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6038fa37-87db-4971-bb34-b69f64077b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-54-option-0</value>
      <webElementGuid>6cbb5d9f-eb17-4284-b8d9-3c8d39205522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>87ffcdb9-a47c-4769-85b1-6266dfefb386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>925695cd-e617-4fe1-8cb1-45cba345a784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>calculator-simulation-page-option-insurance-type-2-0</value>
      <webElementGuid>cd9c4f83-7f3c-4887-84bb-138974af372d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Full Comprehensive</value>
      <webElementGuid>00bdd815-1873-47ea-b3fd-580fa46582ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-54-option-0&quot;)</value>
      <webElementGuid>517b9093-9268-48db-aa93-8abb018fa197</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-54-option-0']</value>
      <webElementGuid>2484e0c9-e857-4660-b863-e07cfcd104ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-54-listbox']/div</value>
      <webElementGuid>e049c030-93f0-4565-a978-bb94ab1bca74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Comprehensive, 1 of 2.'])[1]/following::div[8]</value>
      <webElementGuid>3da9b789-395a-4733-a716-6f5d817824fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Total Loss Only'])[2]/preceding::div[1]</value>
      <webElementGuid>75812868-5b6a-4f58-b30c-204b82ae9c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>561780b4-83dc-4227-91cc-f638bb6b154d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-54-option-0' and (text() = 'Full Comprehensive' or . = 'Full Comprehensive')]</value>
      <webElementGuid>cc30a6a4-5348-4cea-a2a6-6a6e6c8c873e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
