<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__otr</name>
   <tag></tag>
   <elementGuidId>c07632b8-09fd-4233-b7a7-4eade1e64915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='otr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;otr&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f84bcd3-0e66-4f27-87a0-e9049b025df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-[4px] h-[40px] block w-full form-input dark:bg-gray-700 dark:text-gray-300 dark:border-gray-600 placeholder:dark:text-gray-400 focus:border-primary focus:ring-primary focus:ring-opacity-40 dark:focus:ring-gray-500 dark:focus:border-gray-600 focus:outline-none focus:ring-0 text-sm text-neutral-700 placeholder:text-[#404040]</value>
      <webElementGuid>032b8064-0ccc-4e11-b7f8-2e1e36c6eb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55e25508-ff8b-408d-ad15-91b6576c651c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otr</value>
      <webElementGuid>948c0b88-fd89-47f6-85a7-6928ee1d3423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>calculator-simulation-page-input-otr</value>
      <webElementGuid>51c319cb-355b-456c-839d-a7aef9c7ebc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rp. 0</value>
      <webElementGuid>9191a3e9-f495-4660-af6e-3988c5fecc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;mx-auto grid w-full gap-4 px-6 lg:gap-0&quot;]/div[@class=&quot;mb-5 flex flex-col gap-5&quot;]/div[@class=&quot;min-w-0 rounded-lg border border-line shadow-card bg-white dark:bg-gray-800 shadow-xs grid grid-cols-10 gap-y-2 overflow-visible p-4&quot;]/div[@class=&quot;col-span-9&quot;]/div[@class=&quot;flex flex-col gap-1&quot;]/input[@class=&quot;rounded-[4px] h-[40px] block w-full form-input dark:bg-gray-700 dark:text-gray-300 dark:border-gray-600 placeholder:dark:text-gray-400 focus:border-primary focus:ring-primary focus:ring-opacity-40 dark:focus:ring-gray-500 dark:focus:border-gray-600 focus:outline-none focus:ring-0 text-sm text-neutral-700 placeholder:text-[#404040]&quot;]</value>
      <webElementGuid>f9621fdc-2afc-499b-a70e-e01adea82c07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='otr']</value>
      <webElementGuid>89e98420-7fc9-4f99-8d26-6ac41d8d8915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>03155e56-fff9-4d01-89a5-93aa0b7500bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d3500933-3d2c-460f-8819-4eb42ebaab1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'otr' and @placeholder = 'Rp. 0']</value>
      <webElementGuid>303e92a1-1787-4640-84b1-265c3d6c6446</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
