<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Table FIFO 2</name>
   <tag></tag>
   <elementGuidId>24c36f9c-96b3-4511-80f7-a97b20abab8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='radix-:r1c:-trigger-fifo_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22dc5a05-82ef-4d3d-bbf1-a16a4d9d719a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4bd1c6dd-cc3c-4f69-b000-b05417fd774e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>5d54da7a-3587-41c4-93a5-7c1e1bab73f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b4cfbd9b-4aa9-429d-b6b1-787572e3499e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r1c:-content-fifo_2</value>
      <webElementGuid>2b0b7bc8-4ebb-40b8-8af5-234416b5a47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>89e4cbe6-93c9-488d-91ff-fceb3a7d056b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:r1c:-trigger-fifo_2</value>
      <webElementGuid>123cb130-3a50-4470-8ba3-79f61f6a03f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group/trigger relative mr-6 inline-flex min-h-12 cursor-pointer items-center justify-center gap-[10px] whitespace-nowrap border-b-[3px] border-transparent bg-transparent text-body-regular font-normal text-text-placeholder transition-all hover:border-line disabled:pointer-events-none data-[state=active]:font-semibold data-[state=active]:text-text-primary [&amp;[data-state='active']_.counter]:hover:bg-hover-brand-red</value>
      <webElementGuid>b1b7a360-503b-457f-833a-d1f76830e5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3f65cb63-ce98-4b9a-8fe2-e7ef62233b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>4579e6d8-99a0-4575-b723-6edfd9249ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Table FIFO 20</value>
      <webElementGuid>b42a171e-eabb-47b1-9513-681739ef169b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1c:-trigger-fifo_2&quot;)</value>
      <webElementGuid>7bddb9cb-c913-49b8-a10c-f8b28f5bb0bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='radix-:r1c:-trigger-fifo_2']</value>
      <webElementGuid>af45ba01-7efd-4f0b-a7f5-5dc3281c7036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='table-container']/div/div/div/button[3]</value>
      <webElementGuid>3c3093c3-446d-42d8-94bb-b2265aa2b840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Table FIFO 2']/parent::*</value>
      <webElementGuid>cfa3e0ab-818d-45e5-8233-cb57d5208734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>3abf50c0-6f3f-4dff-9e7f-03e1726656b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'radix-:r1c:-trigger-fifo_2' and (text() = 'Table FIFO 20' or . = 'Table FIFO 20')]</value>
      <webElementGuid>dfbef28a-f420-41f2-b63d-2aa06824ba78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
