<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Max. Waiting Time_flex w-full items-cente_7837c6</name>
   <tag></tag>
   <elementGuidId>72b45e57-aa37-4ee2-8186-5e5f063a7af7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebarCRM']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.flex.w-full.items-center.justify-center.py-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>266be7f4-d2e0-4180-9460-c79601c657df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex w-full items-center justify-center py-5</value>
      <webElementGuid>c256c107-8365-40c7-9a03-39443a53cc9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>787808f0-52ef-486a-9ac3-053487ca0030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarCRM&quot;)/div[1]/a[@class=&quot;flex w-full items-center justify-center py-5&quot;]</value>
      <webElementGuid>46f7a1d5-548d-41ad-a3eb-61ff81352095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarCRM']/div/a</value>
      <webElementGuid>22bbadd3-2820-4be7-9bb3-d611340dfa64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max. Waiting Time'])[2]/following::a[1]</value>
      <webElementGuid>37b1a0fd-52c7-4f4a-ba49-44971193af95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/following::a[1]</value>
      <webElementGuid>14a92eca-4aa0-4b38-8ba8-dad633d6e44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/')]</value>
      <webElementGuid>ab653f3a-373f-4b29-8f6b-ee703b3c1104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>df5c94ad-ab55-4e12-ba35-c604dcb1a638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/']</value>
      <webElementGuid>95239469-2c02-494d-9bf3-424733f5b6cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
