<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_City_Bandung</name>
   <tag></tag>
   <elementGuidId>8984184d-fc93-49ef-b41d-734ecb2d5ff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.wrapper.flex.items-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='Bandung']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13876319-830b-4774-a9d4-712ac1ce6300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wrapper flex items-center</value>
      <webElementGuid>b384be43-144f-479d-80c2-d5fa3c206bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Denpasar</value>
      <webElementGuid>1f1a8805-82c3-49cc-90c2-f6438e314786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r84:&quot;)/div[@class=&quot;wrapper flex items-center&quot;]</value>
      <webElementGuid>12bc3a40-ba03-4926-ba4d-b03c5b0850d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r84:']/div</value>
      <webElementGuid>e8b57287-1b89-4616-9ff4-dcaf4ad425ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send to CM'])[1]/following::div[29]</value>
      <webElementGuid>2b71f998-7f84-4c08-9b1a-bfac8a969d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/following::div[37]</value>
      <webElementGuid>d5a26f19-7adf-4e66-8eb6-5436ccb57b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div</value>
      <webElementGuid>e38ede08-0015-40bb-9e7c-05b0ed3a6ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Denpasar' or . = 'Denpasar')]</value>
      <webElementGuid>06d72799-ed1b-4662-86c7-e0932c8b8597</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
