<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Deskripsi_pertanyaan</name>
   <tag></tag>
   <elementGuidId>bca0be1f-66e1-4df6-aabc-e0e75f438ced</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='formModal_styledInputTextArea__YUy8U']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='formModal_styledInputTextArea__YUy8U']</value>
      <webElementGuid>0d112114-a37b-499e-b985-bd0540a801db</webElementGuid>
   </webElementProperties>
</WebElementEntity>
