<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form2_tahunMobil</name>
   <tag></tag>
   <elementGuidId>4b139d64-6cac-495b-9d98-03896e108b61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@class='inputSelectRefinancing_inputField__ZkMfJ'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@class='inputSelectRefinancing_inputField__ZkMfJ'])[3]</value>
      <webElementGuid>42f6e1c6-a2ab-4e47-9820-ba9ed2db2994</webElementGuid>
   </webElementProperties>
</WebElementEntity>
