<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form2_modelMobil</name>
   <tag></tag>
   <elementGuidId>1420783e-4eda-43aa-b3f5-bf4587ee2e3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@class='inputSelectRefinancing_inputField__ZkMfJ'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@class='inputSelectRefinancing_inputField__ZkMfJ'])[2]</value>
      <webElementGuid>5d48568f-b46c-4efe-bc97-c78c14ec8ba3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
