<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp2.659.100.000_downPaymentAmount</name>
   <tag></tag>
   <elementGuidId>0d5eab7a-b8f9-4b63-93c4-119328192b32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;downPaymentAmount&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='multi-kk_form__4UeYG']//div//input[@placeholder='Masukkan DP']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='downPaymentAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c216f13a-0851-4830-8340-73114b3beeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_input__c0tP8 input_error__0fAdE shake-animation-X</value>
      <webElementGuid>342b71c2-a5fb-456e-81b4-b90a6f64de1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan DP</value>
      <webElementGuid>dc1eecbb-a6c6-4959-9208-c8a6859436b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>31600346-e897-446f-bc05-f712742e1e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>32ac0073-beff-4957-9dd7-3f975ffa9e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>downPaymentAmount</value>
      <webElementGuid>f976cf3e-920a-4488-9821-b630f2b4bec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rp6</value>
      <webElementGuid>ece65eb2-99ac-4aa5-9cee-baa784295765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='multi-kk_form__4UeYG']//div//input[@placeholder='Masukkan DP']</value>
      <webElementGuid>b6dc68db-8c61-459d-a153-bbd4554d66ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='downPaymentAmount']</value>
      <webElementGuid>47962f1e-5d27-42e9-b624-3a98b55a1e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[3]/div/div/input</value>
      <webElementGuid>59d648d0-c3c1-44ea-9049-64f4a1ec240a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>72494e34-1edc-4ca8-9a12-c09ce179d7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan DP' and @type = 'tel' and @name = 'downPaymentAmount']</value>
      <webElementGuid>384d3c88-ad51-4aba-8773-a9bec28d8cf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
