<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filter (1)</name>
   <tag></tag>
   <elementGuidId>13b3e3ac-7298-4869-aa79-cbe6e24ee48d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Filter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff5be61d-81e4-4f80-a863-185ea333c421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8645b3a4-505e-4067-8bbe-c7b5fc1e6956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>cfdcc3a6-c14d-440c-81d3-dcf03fa6471c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b5107be0-3c0f-4026-aa62-b3e4114b50fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r1:</value>
      <webElementGuid>4c6d3c1b-8de2-4c6f-9185-2d07d3a588b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>6ca87b9b-159b-4762-9215-201a96067b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center gap-2 rounded-lg border border-gray-300 px-4 py-2 align-bottom text-sm/5 font-medium text-gray-600 transition-colors duration-150 hover:border-gray-500 focus:border-gray-500 focus:outline-none focus:ring focus:ring-primary-300 focus:ring-opacity-40 active:bg-transparent active:text-gray-500 disabled:pointer-events-none disabled:bg-gray-300 disabled:opacity-50 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-400</value>
      <webElementGuid>cb852afb-aafa-4881-9261-2c7393e5ba8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>ab2e2a3a-b613-447d-825a-3c918e368887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;mx-auto grid gap-4 px-6 lg:gap-0&quot;]/div[@class=&quot;mb-6 flex items-center justify-between&quot;]/div[@class=&quot;flex items-center gap-2&quot;]/button[@class=&quot;inline-flex items-center justify-center gap-2 rounded-lg border border-gray-300 px-4 py-2 align-bottom text-sm/5 font-medium text-gray-600 transition-colors duration-150 hover:border-gray-500 focus:border-gray-500 focus:outline-none focus:ring focus:ring-primary-300 focus:ring-opacity-40 active:bg-transparent active:text-gray-500 disabled:pointer-events-none disabled:bg-gray-300 disabled:opacity-50 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-400&quot;]</value>
      <webElementGuid>96e27e95-3c45-4432-bd1a-534d9133f0e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>fe647f4f-277b-4d07-a9b6-28da157fbf7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div[2]/div/button</value>
      <webElementGuid>2caf9f6e-110b-4dc7-8e07-96c5437fc987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testimony Management'])[2]/following::button[1]</value>
      <webElementGuid>eb6e339b-a096-422e-8d54-7d4fec864e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Management'])[1]/following::button[4]</value>
      <webElementGuid>eea6d678-7123-49f7-a338-d84aaf06b0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::button[1]</value>
      <webElementGuid>2a48369f-b474-441b-a212-76ee4cca4f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>5550d7fb-c94e-4b6b-b1d4-35a53d8bb8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Filter' or . = 'Filter')]</value>
      <webElementGuid>0d8fcd3a-e5e6-4ae7-88e2-d6ed7ecd34d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
