<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_Account</name>
   <tag></tag>
   <elementGuidId>30af7304-5633-4816-8211-f7d6990d849d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Yo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1803878-981e-4c56-80e2-7b5de477f73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-[40px] block w-full text-gray-700 form-input dark:bg-gray-700 dark:text-gray-300 dark:border-gray-600 text-sm leading-10 placeholder:dark:text-gray-400 focus:ring-primary focus:ring-opacity-40 dark:focus:ring-gray-500 dark:focus:border-gray-600 rounded-md pl-8 pr-8 placeholder:text-shadesSecondaryGray focus:border-primary focus:shadow-none focus:outline-none focus:ring-0</value>
      <webElementGuid>06d48ff3-ce41-439d-8294-bc67786229b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4015dc37-6813-4d96-9273-5a69685ce038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>94ca6bb1-9de4-4609-a5dc-b8b19ece2901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yo</value>
      <webElementGuid>b486fda9-5b61-492f-bc23-086f2a7c1962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;mx-auto grid gap-4 px-6 lg:gap-0&quot;]/div[@class=&quot;flex flex-row items-center justify-between&quot;]/div[@class=&quot;flex flex-col items-center gap-3 md:flex-row&quot;]/div[@class=&quot;md:w-2/5&quot;]/div[@class=&quot;relative max-w-xl focus-within:text-purple-500&quot;]/input[@class=&quot;h-[40px] block w-full text-gray-700 form-input dark:bg-gray-700 dark:text-gray-300 dark:border-gray-600 text-sm leading-10 placeholder:dark:text-gray-400 focus:ring-primary focus:ring-opacity-40 dark:focus:ring-gray-500 dark:focus:border-gray-600 rounded-md pl-8 pr-8 placeholder:text-shadesSecondaryGray focus:border-primary focus:shadow-none focus:outline-none focus:ring-0&quot;]</value>
      <webElementGuid>b967c915-ac1e-42c7-8b6f-700a26ea3200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Yo']</value>
      <webElementGuid>f46a48ea-42eb-4c25-8cb3-d7a486f37d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/div/div/input</value>
      <webElementGuid>89218cec-8808-416c-a824-329262df5ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c4f24c2f-a2c6-4a6a-90f4-003e055b1196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search']</value>
      <webElementGuid>38a306f7-936f-4ea1-a3fe-aef014eb8d49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
