<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DropdownList</name>
   <tag></tag>
   <elementGuidId>bda5dd8d-2be1-4f59-a20f-7dfa0c47b2e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.downpayment-percentage-select-element > div.sc-kQoPux.cTnhST > div.sc-ekRyGy.jBRUTI > input.sc-gwNDlS.eXSZcw.select-element</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-gwNDlS eXSZcw select-element</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fUCuFg jVCaID&quot;]/div[@class=&quot;sc-dSaQTq bHgxLy&quot;]/div[@class=&quot;sc-gWDJhD kOxUdY&quot;]/div[@class=&quot;sc-bhiFeW ketuSZ&quot;]/div[@class=&quot;sc-cdFzKX ifobDW&quot;]/div[@class=&quot;sc-kZJZaN fFnABz&quot;]/div[@class=&quot;sc-dqhCBx ghGbpY&quot;]/div[@class=&quot;downpayment-percentage-select-element&quot;]/div[@class=&quot;sc-kQoPux cTnhST&quot;]/div[@class=&quot;sc-ekRyGy jBRUTI&quot;]/input[@class=&quot;sc-gwNDlS eXSZcw select-element&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div[4]/div[3]/div[3]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
