<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LowtoHigh</name>
   <tag></tag>
   <elementGuidId>79abd92d-58ce-4a90-89f2-fd0b47c121ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ksdxgE sc-bAhZh eLMWbu hovTjk</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Harga: Rendah ke tinggi</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-ieCETs fvJaeC&quot;]/div[@class=&quot;sc-deghWO pUGiw&quot;]/div[@class=&quot;sc-iiCSmI jbLvZL&quot;]/div[@class=&quot;sc-gWDJhD ljELnR&quot;]/div[@class=&quot;sc-hqyYpk hRmStc&quot;]/div[@class=&quot;sc-hatQeL dkYIbf&quot;]/div[@class=&quot;sc-ksDcAU hHhapM&quot;]/div[@class=&quot;sc-jVslSq cubNQq&quot;]/div[@class=&quot;sc-egiyK hfDbKX&quot;]/div[@class=&quot;sc-crHmcD chwCSK&quot;]/div[@class=&quot;sc-heudyb hzrDDf sort-by-item-element&quot;]/span[@class=&quot;sc-ksdxgE sc-bAhZh eLMWbu hovTjk&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/div/div[2]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BMW X7 xDrive40i Opulence'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 2.620-2.620 jt'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span</value>
   </webElementXpaths>
</WebElementEntity>
