<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PercentageList</name>
   <tag></tag>
   <elementGuidId>a30f29d8-5f6b-4603-8537-8e3b06389c34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-cOLXoO.iLVbVW.select-item-element</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div/div/div[4]/div[3]/div[3]/div/div[2]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[@class=&quot;sc-fUCuFg jVCaID&quot;]/div[@class=&quot;sc-dSaQTq bHgxLy&quot;]/div[@class=&quot;sc-gWDJhD kOxUdY&quot;]/div[@class=&quot;sc-bhiFeW ketuSZ&quot;]/div[@class=&quot;sc-cdFzKX ifobDW&quot;]/div[@class=&quot;sc-kZJZaN fFnABz&quot;]/div[@class=&quot;sc-dqhCBx ghGbpY&quot;]/div[@class=&quot;downpayment-percentage-select-element&quot;]/div[@class=&quot;sc-kQoPux cTnhST&quot;]/div[@class=&quot;sc-lVTEl NYEWE&quot;]/div[@class=&quot;sc-cOLXoO iLVbVW select-item-element&quot;][count(. | //*[@class = 'sc-cOLXoO iLVbVW select-item-element' and (text() = '${Jumlah}' or . = '${Jumlah}')]) = count(//*[@class = 'sc-cOLXoO iLVbVW select-item-element' and (text() = '${Jumlah}' or . = '${Jumlah}')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-cOLXoO iLVbVW select-item-element</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${Jumlah}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fUCuFg jVCaID&quot;]/div[@class=&quot;sc-dSaQTq bHgxLy&quot;]/div[@class=&quot;sc-gWDJhD kOxUdY&quot;]/div[@class=&quot;sc-bhiFeW ketuSZ&quot;]/div[@class=&quot;sc-cdFzKX ifobDW&quot;]/div[@class=&quot;sc-kZJZaN fFnABz&quot;]/div[@class=&quot;sc-dqhCBx ghGbpY&quot;]/div[@class=&quot;downpayment-percentage-select-element&quot;]/div[@class=&quot;sc-kQoPux cTnhST&quot;]/div[@class=&quot;sc-lVTEl NYEWE&quot;]/div[@class=&quot;sc-cOLXoO iLVbVW select-item-element&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div[4]/div[3]/div[3]/div/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/preceding::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sortir'])[1]/preceding::div[24]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10%']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
