<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_searchBar</name>
   <tag></tag>
   <elementGuidId>ee2b825d-2c8e-4799-98e6-5d60b3b4dc4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.m-0.w-full.appearance-none.border-0.bg-transparent.p-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Search Keyword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb809eda-e0ef-4c29-b6bf-75eeb29fff90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4881cdb7-9128-4cda-8ea2-e34a8e13e4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>da31bc27-c4cb-4c79-835b-947dac2d3705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0 w-full appearance-none border-0 bg-transparent p-0</value>
      <webElementGuid>c809d9df-f4b8-47ba-9759-9c43e2dfcf85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r2s:&quot;)/div[@class=&quot;flex min-h-[34px] items-center rounded border border-line&quot;]/div[@class=&quot;flex max-h-[108px] flex-1 flex-wrap gap-1 overflow-y-auto p-2.5&quot;]/input[@class=&quot;m-0 w-full appearance-none border-0 bg-transparent p-0&quot;]</value>
      <webElementGuid>9c6f19dd-3811-485d-83c6-1d3e9a54593a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>4c745ce7-21a8-469b-bb35-d394a1f0f2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2s:']/div[2]/div[2]/input</value>
      <webElementGuid>cefef6da-f1b4-4204-9447-61264b93820a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7855a86b-4de9-44fe-857d-dcb62ca2f62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search...']</value>
      <webElementGuid>9ac1b236-8af8-4e2b-9bef-eeb2aab375f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r6o:']/div[2]/div[2]/input</value>
      <webElementGuid>dc1415bd-c711-45c7-9e8d-dc4662d80452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>7bee76fb-c418-4456-8b92-58e8be584421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/input</value>
      <webElementGuid>5418aeb9-0c83-45d2-a285-17f1f8cf923e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5149af27-d21b-433b-87e9-2202138f18c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search Keyword']</value>
      <webElementGuid>94f2de69-1324-4d0e-9e3e-fef7bc0e4630</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
