<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_pendapatan_bulanan_kk_review</name>
   <tag></tag>
   <elementGuidId>2cd52a73-d610-4de4-81a8-1d084a3c18ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div[5]/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.kualifikasi-kredit-review_textIncome__dmA1T</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5b0a7658-541c-4dbf-b1b9-33c427179236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kualifikasi-kredit-review_textIncome__dmA1T</value>
      <webElementGuid>65ba47e8-5a8b-464d-95b4-ebe0829d5746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp20.000.000</value>
      <webElementGuid>c0d6c707-e8fd-471a-90d6-67ef287cf107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;pageLayoutV2_container__KegP2&quot;]/div[@class=&quot;kualifikasi-kredit-review_container__6NYOD&quot;]/div[@class=&quot;kualifikasi-kredit-review_paddingFormIncome__jH26w&quot;]/p[@class=&quot;kualifikasi-kredit-review_textIncome__dmA1T&quot;]</value>
      <webElementGuid>3fc8e252-59a3-468a-9884-9b88e16ecccc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div[5]/p[2]</value>
      <webElementGuid>4fb4ae96-5ee7-4865-a608-299aa258257d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periksa kembali informasi kamu sebelum mengecek Kualifikasi Kredit.'])[1]/following::p[4]</value>
      <webElementGuid>c962902e-59a0-43fd-b68b-60e8fdb1648e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Datamu'])[1]/following::p[4]</value>
      <webElementGuid>1402e0e9-a28f-48c5-b41f-b942b8cafc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobil yang kamu pilih:'])[1]/preceding::p[1]</value>
      <webElementGuid>16ebbbdd-ad69-4fde-9832-3dc606246bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daihatsu Sigra'])[1]/preceding::p[1]</value>
      <webElementGuid>3ab391ac-82ff-4692-9633-fc1de3505b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp']/parent::*</value>
      <webElementGuid>d0c47f84-0b2e-4dc1-80f8-614fcb1e2ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/p[2]</value>
      <webElementGuid>522c961f-18af-4893-a1f0-fb0db5d99e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Rp20.000.000' or . = 'Rp20.000.000')]</value>
      <webElementGuid>17f1a211-12c0-4ff7-a3b6-38581a84cc6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
