<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hitung KemampuanDapatkan hasil perhitun_da483e</name>
   <tag></tag>
   <elementGuidId>a484bab7-0267-48da-8908-3e74b29e44f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div[6]/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>69c4b950-ecbe-4852-a666-04c0093fca64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung KemampuanDapatkan hasil perhitungan cicilan mobil yang sesuai dengan kemampuan finansialmu!</value>
      <webElementGuid>c452d68e-87df-4ea4-add4-6fc4038807f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;index_main__K2Wvo&quot;]/div[@class=&quot;index_container__KNQ8V&quot;]/div[@class=&quot;howToUse_wrapper__ORgWe&quot;]/div[@class=&quot;howToUse_cardSpacing__bpirt&quot;]/div[@class=&quot;howToUse_cardHowToUse__HZeMc&quot;]/div[1]</value>
      <webElementGuid>cc1bacd6-2ce2-4b26-ae04-ad5652d78b71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[6]/div/div[2]/div</value>
      <webElementGuid>0bbce85c-bd0b-4b30-a09f-6374a89a5e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara Dapatkan Mobil Impian di SEVA'])[1]/following::div[8]</value>
      <webElementGuid>ef81334c-341e-4ae1-9bd0-5fdd1b3247ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat semua mobil'])[1]/following::div[9]</value>
      <webElementGuid>333a35b2-5d78-4e12-925d-89d6067c0acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEVA Car of The Month'])[1]/preceding::div[10]</value>
      <webElementGuid>c3b75fa7-2730-496e-bbd7-30a38e09c762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All New Kijang Innova Zenix'])[1]/preceding::div[11]</value>
      <webElementGuid>b65e1783-f344-491e-bd99-7d98b4cc5d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div</value>
      <webElementGuid>f646eb18-64c5-45f7-961f-baf54d0e79ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hitung KemampuanDapatkan hasil perhitungan cicilan mobil yang sesuai dengan kemampuan finansialmu!' or . = 'Hitung KemampuanDapatkan hasil perhitungan cicilan mobil yang sesuai dengan kemampuan finansialmu!')]</value>
      <webElementGuid>f0554975-1fed-457a-ba1b-098eb6b11c48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
