<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS - Register and Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1817a29e-655d-46cd-b96a-c5498e1d61c2</testSuiteGuid>
   <testCaseLink>
      <guid>fb531a2d-582f-4555-82e5-2e04e69ba587</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/LR001-TC-Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f36f9fe-cd27-440d-9a45-f5b110b26cb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b4fb5ab-e57f-4309-b540-fffbe58f35f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cbeef3d-966f-4b07-a9bd-a718d499b217</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e74fae4-ca4c-4979-86cd-e4ad91254bb9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>46a95188-6fa2-4511-9f1a-e31035042e8e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/LR002-TC-FailValidateOTP</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f36f9fe-cd27-440d-9a45-f5b110b26cb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b4fb5ab-e57f-4309-b540-fffbe58f35f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cbeef3d-966f-4b07-a9bd-a718d499b217</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e74fae4-ca4c-4979-86cd-e4ad91254bb9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54ebf46d-7d19-4c73-aae2-e2ea1f085a0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/LR003-TC-Fail Input</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f36f9fe-cd27-440d-9a45-f5b110b26cb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfc4e475-7603-47c7-aa6f-f18997c53a30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4efe05f2-8bcc-41d1-8bcb-ec97ea7c7290</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56c59aa0-32ee-42c4-bc9b-e45baab4ff0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cbeef3d-966f-4b07-a9bd-a718d499b217</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e74fae4-ca4c-4979-86cd-e4ad91254bb9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90659e81-87f9-453e-ab92-af676ab53843</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/RA 001 - Register</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12f16fdc-7641-45a3-8191-5dc4d6ea6225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce6c12c-c9aa-4a1a-88fb-8750a11fc273</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9de51b-8dd6-4a52-857e-c810cc6a9e69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd4e1d7d-049a-41aa-bf39-2c9b62325c2d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6893926-b651-489e-99a0-b7d9a1737a6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/RA 002 - Register dan delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12f16fdc-7641-45a3-8191-5dc4d6ea6225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce6c12c-c9aa-4a1a-88fb-8750a11fc273</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9de51b-8dd6-4a52-857e-c810cc6a9e69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd4e1d7d-049a-41aa-bf39-2c9b62325c2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a191291-ee2e-4d18-9867-5d0afb4a789e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4613159-3dcf-4ccf-821f-832195d8d5da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>258a0945-bed8-45a2-9ca9-610eb73cfadb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8394a2d-297f-47e4-8768-6377bdbb45d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af1d0811-e0b4-4507-b846-a0e02ec4cc96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>272721a3-1a88-4753-8c39-e2e7a852365c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/RA 003 - Register Negative Case Null Input</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12f16fdc-7641-45a3-8191-5dc4d6ea6225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce6c12c-c9aa-4a1a-88fb-8750a11fc273</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9de51b-8dd6-4a52-857e-c810cc6a9e69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd4e1d7d-049a-41aa-bf39-2c9b62325c2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86ad1270-457a-4b43-af02-9f5f6a74872c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f824c801-0768-4812-8cb4-be8298bb8810</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7895fbc4-5199-449d-bed3-9d1d3aab85c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/RA 004 - Register Negative Input Email dan Reverral</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12f16fdc-7641-45a3-8191-5dc4d6ea6225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce6c12c-c9aa-4a1a-88fb-8750a11fc273</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9de51b-8dd6-4a52-857e-c810cc6a9e69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd4e1d7d-049a-41aa-bf39-2c9b62325c2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86ad1270-457a-4b43-af02-9f5f6a74872c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f824c801-0768-4812-8cb4-be8298bb8810</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55d2854d-fc1f-4da9-810d-efc45bb34024</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17b2063d-4879-4887-8052-0385a86b2266</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/RA 005 - Syarat Ketentuan dan Kebijakan Privasi</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12f16fdc-7641-45a3-8191-5dc4d6ea6225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce6c12c-c9aa-4a1a-88fb-8750a11fc273</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
