<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS - Register and Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1817a29e-655d-46cd-b96a-c5498e1d61c2</testSuiteGuid>
   <testCaseLink>
      <guid>0b5f59d8-5977-41cc-8885-e10a4c21c17d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/LR001-TC-Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f36f9fe-cd27-440d-9a45-f5b110b26cb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b4fb5ab-e57f-4309-b540-fffbe58f35f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cbeef3d-966f-4b07-a9bd-a718d499b217</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e74fae4-ca4c-4979-86cd-e4ad91254bb9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e71464b0-6c9b-4018-9351-009f7895e769</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed6b8656-c033-489b-865a-7f1f1becf16d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/LR002-TC-FailValidateOTP</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f36f9fe-cd27-440d-9a45-f5b110b26cb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b4fb5ab-e57f-4309-b540-fffbe58f35f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cbeef3d-966f-4b07-a9bd-a718d499b217</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e74fae4-ca4c-4979-86cd-e4ad91254bb9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>318e36f7-3718-416a-982b-8b9dc0edc90e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/LR003-TC-Fail Input</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f36f9fe-cd27-440d-9a45-f5b110b26cb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfc4e475-7603-47c7-aa6f-f18997c53a30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4efe05f2-8bcc-41d1-8bcb-ec97ea7c7290</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56c59aa0-32ee-42c4-bc9b-e45baab4ff0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cbeef3d-966f-4b07-a9bd-a718d499b217</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e74fae4-ca4c-4979-86cd-e4ad91254bb9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b301b9cd-f766-4e76-b7f8-14bbf4b7cc9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/RA 001 - Register Mobile View</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8be0248-7751-4ebb-ab5e-94addd073df3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80afa157-a215-49cd-9520-3b15630c4581</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9a7750a-eeb6-4b2a-a936-20c447879d5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c960610-2095-4bcb-8ca5-b59a5e158cc7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f962d1dc-1f13-46e1-833f-47507db491ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/RA 002 - Register dan delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12f16fdc-7641-45a3-8191-5dc4d6ea6225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce6c12c-c9aa-4a1a-88fb-8750a11fc273</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9de51b-8dd6-4a52-857e-c810cc6a9e69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd4e1d7d-049a-41aa-bf39-2c9b62325c2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a191291-ee2e-4d18-9867-5d0afb4a789e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4613159-3dcf-4ccf-821f-832195d8d5da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>258a0945-bed8-45a2-9ca9-610eb73cfadb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8394a2d-297f-47e4-8768-6377bdbb45d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af1d0811-e0b4-4507-b846-a0e02ec4cc96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>13bc6499-aeb4-41ff-89bc-84802f6804d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/RA 003 - Register Negative Case Null Input</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12f16fdc-7641-45a3-8191-5dc4d6ea6225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce6c12c-c9aa-4a1a-88fb-8750a11fc273</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9de51b-8dd6-4a52-857e-c810cc6a9e69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd4e1d7d-049a-41aa-bf39-2c9b62325c2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86ad1270-457a-4b43-af02-9f5f6a74872c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f824c801-0768-4812-8cb4-be8298bb8810</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b4cf483-75e4-4d7b-ab7f-4e4c41d29494</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/RA 004 - Register Negative Input Email dan Reverral</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12f16fdc-7641-45a3-8191-5dc4d6ea6225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce6c12c-c9aa-4a1a-88fb-8750a11fc273</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9de51b-8dd6-4a52-857e-c810cc6a9e69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd4e1d7d-049a-41aa-bf39-2c9b62325c2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86ad1270-457a-4b43-af02-9f5f6a74872c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f824c801-0768-4812-8cb4-be8298bb8810</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55d2854d-fc1f-4da9-810d-efc45bb34024</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a68a449-c98d-4e9a-a939-fd2f7654154d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Register/RA 005 - Syarat Ketentuan dan Kebijakan Privasi</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12f16fdc-7641-45a3-8191-5dc4d6ea6225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce6c12c-c9aa-4a1a-88fb-8750a11fc273</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
