<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tambah_mbl_2</name>
   <tag></tag>
   <elementGuidId>c7b5f2fb-2a8d-4742-b94b-574b9bd1e6f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class=&quot;carComparisonEmptyItemCard_container__fduy7&quot;][2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='carComparisonPageContent-module__-c6buG__container']//button[1]//div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class=&quot;carComparisonEmptyItemCard_container__fduy7&quot;][2]</value>
      <webElementGuid>0c7033e3-2cf8-4427-8ce7-c0a885f014aa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
