<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>loan-calculator</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>84c8c628-81bd-4f03-8db2-9de27faa1840</testSuiteGuid>
   <testCaseLink>
      <guid>dd9ba3a6-ce1f-43ff-bb28-2451555bc55c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC001 - Loan Calculator Access Homepage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f41dff0-5060-401c-9583-17298c09288a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a740894-53f6-4fd7-9870-cf2562ceccb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC002 - Loan Calculator Form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e17a4443-e926-4b51-9e53-24bc4c125336</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b7a2ea5-a9ae-48d8-9909-0860ec289a8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbfb7136-3a5f-490e-ac31-a4e1078ba802</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e3ce0e5-a6bf-4133-bb9e-e79fb76c28a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fd870c8-53ea-4cc1-9f82-6b7c9a6a832f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25bc274f-0ed8-4e4e-9a8f-c85c4525742a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC003 - Loan Calculator - Homepage - Car Recomendation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9c16091-26b6-4253-80bd-f64852028920</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7525959-bc76-491b-967a-8548d857dd3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84cf2bdf-58a9-40a5-a9a7-9c60b8277514</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd5ab3f3-5d3e-45b8-96b5-821afa99443d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11b65a82-64be-42e2-8d41-a3ed6284a1e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC004 - Loan Calculator - Homepage - Yuk SEVA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2db62915-ad32-4cab-a3cd-3e71b6472245</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC005 - Loan Calculator - PLP - Cari Mobil</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac0cd610-e350-4c86-bd37-f961e169ef1f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
