<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS Loan Calculator</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>84c8c628-81bd-4f03-8db2-9de27faa1840</testSuiteGuid>
   <testCaseLink>
      <guid>09cf0a88-a820-4dde-930a-a775f0ae4983</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC001 - VerifyUserCanAccessLoanCalculatorFromHomepage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f41dff0-5060-401c-9583-17298c09288a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fb2f671-b7b8-42ef-abf7-9a724b138819</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7418311-5e1e-44a1-a563-c0276060db14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC002 - VerifyUserCanInputLoanCalculatorForm</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e17a4443-e926-4b51-9e53-24bc4c125336</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b7a2ea5-a9ae-48d8-9909-0860ec289a8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbfb7136-3a5f-490e-ac31-a4e1078ba802</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e3ce0e5-a6bf-4133-bb9e-e79fb76c28a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fd870c8-53ea-4cc1-9f82-6b7c9a6a832f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6344a26-633d-450b-aefa-823ca6743f7c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a20979d6-e74e-4fee-9f09-0fec74e7a437</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC003 - VerifyUserCanAccessLoanCalculatorFromCarRecomendation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7525959-bc76-491b-967a-8548d857dd3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84cf2bdf-58a9-40a5-a9a7-9c60b8277514</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9c16091-26b6-4253-80bd-f64852028920</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd5ab3f3-5d3e-45b8-96b5-821afa99443d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2621738-d9be-44db-95ac-f85dca206810</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC004 - VerifyUserCanAcessLoanCalculatorFromYukSevaSection</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f0aa375e-495f-4f79-b221-58aef0d8dc12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC005 - VerifyUserCanAccessLoanCalculatorFromPLP</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac0cd610-e350-4c86-bd37-f961e169ef1f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4649e9e3-289b-49ec-a036-884bb78b3823</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC006 - VerifyUserCanAccessLoanCalculatorFromPDP</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8cad235-0003-4cce-b841-7e4dc2007b1f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92cd4e6f-6c61-4d80-ad48-e9e9fa0369d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC007 - VerifyErrorMessageEmptyDPField</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5689bb20-bb44-4748-af1d-14ac1b4275bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11612324-3d38-4e24-8091-8f3187dac476</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6b3cfe1-6ed6-48fe-9706-4bfe0dc349b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>915063a1-9cca-490a-b6a4-0a0a15425f69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b44c5d6b-bebf-4a36-baa9-ef3080a4667e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dce493da-ed56-4f09-bb29-50440f0102d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC008 - VerifyErrorMessageMinimumDPField</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b525e6a1-2861-455a-96d4-60edb6222971</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e911df69-72b5-47ea-8d39-62de02093b5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ce8cb89-28a2-449e-aa24-1421099933fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f83e44a0-5876-41ae-b1c4-063934d75e4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a70ed4b-95f8-4c16-b4c4-03008a23f33d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37e5465f-019e-41fc-89a7-d7235be23de4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC009 - VerifyErrorMessageMaximumDPField</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4832eebe-a050-4a9d-8785-d2ca6ae14def</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7739a61f-7eaa-4dda-a257-bd518e686465</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18091c98-a41e-4aff-b76a-f95402b1458a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03df3f85-387d-4b3d-a709-3380bfecbdf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ce6f4e1-8ecb-4b18-a55c-d99c3cf0031b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4885e022-403c-4bc5-957c-c41e46e46ff0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC010 - VerifyErrorMessageEmptyIncomeField</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a654b2c4-0cdf-4eda-9ee8-4d13f4b3fdc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e550d083-4f1b-4146-b217-58d8d1090247</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1996e618-8f3c-4da4-abaf-5635841bdf64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07a127ce-9c9a-4c6e-9f4e-4558bdc19ebf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38a56ade-957a-4723-beb5-bac953f45383</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f5e36daf-3c54-4bb5-bfb3-d2d1edba2662</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC011 - VerifyErrorMessageMinimumIncomeField</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3d3b1b1-2e61-435a-b347-1a78d00e0b4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09a49cf5-d1cf-454e-8950-4887b17f09d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dcd74e1-58a1-4812-948c-dd2818dd4770</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08d40e98-fc6e-4d67-a8b7-415b27ee4401</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>702f2903-6a24-46b8-b0d2-dfb0f6f663df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca2f3efc-b2f5-46bb-9929-8185229d77e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC012 - VerifyErrorMessageEmptyAgeField</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34887b91-4267-44ba-87b8-ddfcea4787f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47ca3342-550d-4b92-a3f0-801fe51e7258</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>557f4aec-cbf1-43f0-8a4a-0a7900103cdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8de73c6-e4b4-457a-a4af-42615719fd1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f99c0a4-9cc8-47b2-b4c9-47caa16ed664</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9894507-c53f-4cfd-85ce-89da354b7024</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loan Calculator/LC013 - VerifyUserCanClickPromoLain</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41828f95-12e5-4a9b-b218-1790cff2f249</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4da2d69b-104b-41f1-afdf-d98da6732c59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f40434f-f43c-445e-b7d4-3d837a5c9f96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd50da8a-261b-474c-9191-e7d4775bf70d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa7c427a-76e8-4b47-b84b-542901fc8dfd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
